function result = solve_anchor_ik(robot, taskPlaneConfig, ikConfig)
%SOLVE_ANCHOR_IK Solve and independently validate one robot-anchor IK pose.
%
% Inputs:
%   robot           - Stage 1 Legacy 5DOF rigidBodyTree with DataFormat row
%   taskPlaneConfig - Stage 3 task-plane config containing robot_anchor_m [m]
%   ikConfig        - Position-Only IK config from default_ik_config
%
% Output:
%   result - canonical per-target IK result, plus anchor-only target-pose and
%            position-tolerance evidence.
%
% This is deliberately a single-anchor baseline. It neither consumes nor
% changes TaskTrajectory/SegmentSet data and does not solve a continuous run.

    validate_inputs(robot, taskPlaneConfig, ikConfig);

    endEffector = char(string(ikConfig.end_effector));
    targetXYZ = reshape(taskPlaneConfig.robot_anchor_m, 3, 1);

    % The baseline seed is explicitly the model home configuration, not a
    % previous trajectory solution. This keeps the isolated anchor result
    % repeatable and avoids introducing continuous-IK behavior prematurely.
    initialGuess = row_configuration(homeConfiguration(robot));
    homePose = getTransform(robot, initialGuess, endEffector);

    % A valid homogeneous transform still needs an orientation. Reuse the
    % stable end-effector orientation at home as a placeholder. Its weights
    % are zero, so it is not an orientation tracking target in this stage.
    targetPose = eye(4);
    targetPose(1:3, 1:3) = homePose(1:3, 1:3);
    targetPose(1:3, 4) = targetXYZ;

    ik = inverseKinematics( ...
        'RigidBodyTree', robot, ...
        'SolverAlgorithm', ikConfig.solver_algorithm);

    % R2024a provides AllowRandomRestart inside SolverParameters. Preserve
    % the solver's other version-specific values instead of hard-coding a
    % complete parameter struct from memory.
    solverParameters = ik.SolverParameters;

    if ~isfield(solverParameters, 'AllowRandomRestart')
        error( ...
            'MonoTeach:UnsupportedInverseKinematicsAPI', ...
            'R2024a SolverParameters must contain AllowRandomRestart.');
    end

    solverParameters.AllowRandomRestart = ikConfig.allow_random_restart;
    ik.SolverParameters = solverParameters;

    [qAnchor, solutionInfo] = ik( ...
        endEffector, ...
        targetPose, ...
        ikConfig.weights, ...
        initialGuess);
    qAnchor = row_configuration(qAnchor);

    % A solver status describes its numerical termination, not independent
    % robot-frame geometry. Recompute FK and measure the requested XYZ error
    % before treating this anchor result as acceptable.
    fkPose = getTransform(robot, qAnchor, endEffector);
    fkXYZ = fkPose(1:3, 4)';

    % The solver is configured to enforce limits, but pass the explicit five
    % limits into the shared result contract as independent evidence. This
    % detects model/config changes and makes boundary proximity visible to
    % later safety stages.
    jointLimits = five_joint_limits(robot);
    result = ik_result_contract( ...
        targetXYZ', ...
        initialGuess, ...
        qAnchor, ...
        solutionInfo.Status, ...
        solutionInfo.PoseErrorNorm, ...
        fkXYZ, ...
        jointLimits);

    % Anchor-specific evidence augments the common per-target result without
    % changing the field semantics used by a later trajectory solver.
    result.target_pose = targetPose;
    result.position_error_tolerance_m = ikConfig.position_error_tolerance_m;
    result.within_position_tolerance = ...
        result.position_error_m <= ikConfig.position_error_tolerance_m;
    result.joint_limits_rad = jointLimits;
end


function validate_inputs(robot, taskPlaneConfig, ikConfig)

    if ~isa(robot, 'rigidBodyTree') || ~strcmp(robot.DataFormat, 'row')
        error( ...
            'MonoTeach:InvalidAnchorIKRobot', ...
            'robot must be a rigidBodyTree with DataFormat set to row.');
    end

    if ~isstruct(taskPlaneConfig) || ~isscalar(taskPlaneConfig) || ...
            ~isfield(taskPlaneConfig, 'robot_anchor_m')
        error( ...
            'MonoTeach:InvalidAnchorIKTaskPlaneConfig', ...
            'taskPlaneConfig must contain robot_anchor_m.');
    end

    require_finite_row_vector( ...
        taskPlaneConfig.robot_anchor_m, ...
        3, ...
        'taskPlaneConfig.robot_anchor_m');

    if ~isstruct(ikConfig) || ~isscalar(ikConfig)
        error( ...
            'MonoTeach:InvalidAnchorIKConfig', ...
            'ikConfig must be one scalar config struct.');
    end

    requiredFields = { ...
        'end_effector', ...
        'weights', ...
        'position_error_tolerance_m', ...
        'allow_random_restart', ...
        'solver_algorithm'};
    missingFields = requiredFields(~isfield(ikConfig, requiredFields));

    if ~isempty(missingFields)
        error( ...
            'MonoTeach:MissingAnchorIKConfigField', ...
            'ikConfig is missing required fields: %s.', ...
            strjoin(missingFields, ', '));
    end

    if ~(ischar(ikConfig.end_effector) || ...
            (isstring(ikConfig.end_effector) && isscalar(ikConfig.end_effector)))
        error( ...
            'MonoTeach:InvalidAnchorIKEndEffector', ...
            'ikConfig.end_effector must be one body name.');
    end

    endEffector = char(string(ikConfig.end_effector));
    if ~any(strcmp(robot.BodyNames, endEffector))
        error( ...
            'MonoTeach:UnknownAnchorIKEndEffector', ...
            'End effector body "%s" is not in robot.BodyNames.', ...
            endEffector);
    end

    require_finite_row_vector(ikConfig.weights, 6, 'ikConfig.weights');

    if any(ikConfig.weights < 0) || ...
            any(ikConfig.weights(1:3) ~= 0) || ...
            any(ikConfig.weights(4:6) <= 0)
        error( ...
            'MonoTeach:InvalidPositionOnlyWeights', ...
            ['ikConfig.weights must have zero orientation weights and ' ...
             'positive position weights.']);
    end

    if ~isnumeric(ikConfig.position_error_tolerance_m) || ...
            ~isscalar(ikConfig.position_error_tolerance_m) || ...
            ~isreal(ikConfig.position_error_tolerance_m) || ...
            ~isfinite(ikConfig.position_error_tolerance_m) || ...
            ikConfig.position_error_tolerance_m <= 0
        error( ...
            'MonoTeach:InvalidAnchorIKTolerance', ...
            'position_error_tolerance_m must be one positive finite scalar.');
    end

    if ~islogical(ikConfig.allow_random_restart) || ...
            ~isscalar(ikConfig.allow_random_restart)
        error( ...
            'MonoTeach:InvalidAnchorIKRestartPolicy', ...
            'allow_random_restart must be one logical scalar.');
    end

    if ~strcmp(string(ikConfig.solver_algorithm), "BFGSGradientProjection")
        error( ...
            'MonoTeach:InvalidAnchorIKSolver', ...
            ['This baseline requires the R2024a ' ...
             'BFGSGradientProjection solver.']);
    end
end


function q = row_configuration(configuration)

    if ~isnumeric(configuration) || ~isreal(configuration) || ...
            any(~isfinite(configuration), 'all')
        error( ...
            'MonoTeach:InvalidAnchorIKConfiguration', ...
            'The robot configuration must be finite real numeric data.');
    end

    q = reshape(configuration, 1, []);

    if numel(q) ~= 5
        error( ...
            'MonoTeach:UnexpectedAnchorIKDof', ...
            'The Legacy anchor baseline requires exactly five joint values.');
    end
end


function limits = five_joint_limits(robot)

    if robot.NumBodies ~= 5
        error( ...
            'MonoTeach:UnexpectedAnchorIKRobot', ...
            'The Legacy anchor baseline requires exactly five robot bodies.');
    end

    limits = zeros(5, 2);

    for i = 1:5
        joint = robot.Bodies{i}.Joint;

        if ~strcmp(joint.Type, 'revolute')
            error( ...
                'MonoTeach:UnexpectedAnchorIKJoint', ...
                'Legacy body %d must have a revolute joint.', ...
                i);
        end

        limits(i, :) = joint.PositionLimits;
    end
end


function require_finite_row_vector(value, expectedLength, context)

    if ~isnumeric(value) || ~isreal(value) || ...
            ~isequal(size(value), [1, expectedLength]) || ...
            any(~isfinite(value), 'all')
        error( ...
            'MonoTeach:InvalidAnchorIKInput', ...
            '%s must be one finite 1-by-%d numeric vector.', ...
            context, ...
            expectedLength);
    end
end
