function comparison = summarize_task_path_ik_ab( ...
        rawCount, rawSummary, rawCoverage, resampledCount, resampledSummary, ...
        resampledCoverage)
%SUMMARIZE_TASK_PATH_IK_AB Comparable sampled-path IK evidence for A/B.

    comparison = struct();
    comparison.frame_driven = summarize_case(rawCount, rawSummary, rawCoverage);
    comparison.uniform_arclength = summarize_case( ...
        resampledCount, resampledSummary, resampledCoverage);
end


function result = summarize_case(sampleCount, summary, coverage)
    result = struct( ...
        'sample_count', sampleCount, ...
        'writing_success_rate', summary.ik_success_rate, ...
        'writing_success_point_count', summary.success_point_count, ...
        'writing_failure_count', summary.failure_count, ...
        'ik_success_execution_segment_count', summary.ik_success_segment_count, ...
        'accepted_sampled_arclength_m', coverage.accepted_sampled_arclength_m, ...
        'total_arclength_m', coverage.total_arclength_m, ...
        'accepted_sampled_coverage_fraction', ...
            coverage.accepted_sampled_coverage_fraction, ...
        'failed_points', coverage.failed_points, ...
        'max_joint_step_rad', summary.overall_max_joint_step, ...
        'minimum_joint_limit_margin', summary.minimum_joint_limit_margin, ...
        'mean_position_error_m', summary.mean_fk_position_error_m, ...
        'max_position_error_m', summary.max_fk_position_error_m, ...
        'mean_direction_error_deg', summary.mean_tool_direction_error_deg, ...
        'max_direction_error_deg', summary.max_tool_direction_error_deg);
end
