function adapter = resampled_task_to_preik_segments(resampled)
%RESAMPLED_TASK_TO_PREIK_SEGMENTS Adapt derived arc-length runs for IK.
%
% source_index in the adapter is the globally unique resampled_index, never
% an original camera sample identity.  Full source-bracket provenance is kept
% in both each sample and a lookup for post-solver result decoration.

    validate_input(resampled);
    segments = repmat(empty_segment(), 1, 0);
    provenance = repmat(empty_provenance(), 1, 0);
    for runIndex = 1:numel(resampled.runs)
        run = resampled.runs(runIndex);
        samples = repmat(empty_sample(), 1, 0);
        for pointIndex = 1:numel(run.points)
            point = run.points(pointIndex);
            sample = struct( ...
                't_ms', point.interpolated_t_ms, ...
                'valid', true, ...
                'inside_workspace', true, ...
                'invalid_reason', '', ...
                'x_m', point.xyz_m(1), ...
                'y_m', point.xyz_m(2), ...
                'z_m', point.xyz_m(3), ...
                'resampled_index', point.resampled_index, ...
                'source_bracket_indices', point.source_bracket_indices, ...
                'interpolation_ratio', point.interpolation_ratio, ...
                'original_run_index', point.original_run_index, ...
                'source_arclength_m', point.source_arclength_m);
            samples(end + 1) = sample; %#ok<AGROW>
            provenance(end + 1) = provenance_from_point(point); %#ok<AGROW>
        end
        segments(end + 1) = struct( ...
            'source_indices', [samples.resampled_index], ...
            'samples', samples, ...
            'original_run_index', run.original_run_index); %#ok<AGROW>
    end
    if numel(unique([provenance.resampled_index])) ~= numel(provenance)
        error('MonoTeach:DuplicateResampledIKIndex', ...
            'Every resampled_index must be globally unique for IK adaptation.');
    end
    adapter = struct();
    adapter.artifact_type = 'resampled_task_preik_adapter';
    adapter.coordinate_frame = resampled.coordinate_frame;
    adapter.units = 'm';
    adapter.metadata = struct('units', 'm', ...
        'source_artifact_type', resampled.artifact_type, ...
        'target_spacing_m', resampled.target_spacing_m);
    adapter.segments = segments;
    adapter.provenance_lookup = provenance;
    adapter.summary = struct('preik_segment_count', numel(segments), ...
        'resampled_point_count', numel(provenance), ...
        'original_run_indices', [segments.original_run_index]);
end


function provenance = provenance_from_point(point)

    provenance = struct( ...
        'resampled_index', point.resampled_index, ...
        'xyz_m', point.xyz_m, ...
        'source_bracket_indices', point.source_bracket_indices, ...
        'interpolation_ratio', point.interpolation_ratio, ...
        'original_run_index', point.original_run_index, ...
        'source_arclength_m', point.source_arclength_m);
end


function segment = empty_segment()
    segment = struct('source_indices', zeros(1,0), 'samples', struct([]), ...
        'original_run_index', NaN);
end


function sample = empty_sample()
    sample = struct('t_ms', NaN, 'valid', true, 'inside_workspace', true, ...
        'invalid_reason', '', 'x_m', NaN, 'y_m', NaN, 'z_m', NaN, ...
        'resampled_index', NaN, 'source_bracket_indices', NaN(1,2), ...
        'interpolation_ratio', NaN, 'original_run_index', NaN, ...
        'source_arclength_m', NaN);
end


function provenance = empty_provenance()
    provenance = struct('resampled_index', NaN, 'xyz_m', NaN(1,3), ...
        'source_bracket_indices', NaN(1,2), 'interpolation_ratio', NaN, ...
        'original_run_index', NaN, 'source_arclength_m', NaN);
end


function validate_input(resampled)
    if ~isstruct(resampled) || ~isscalar(resampled) || ...
            ~isfield(resampled, 'artifact_type') || ...
            ~strcmp(string(resampled.artifact_type), ...
                "task_trajectory_arclength_resampling") || ...
            ~isfield(resampled, 'coordinate_frame') || ...
            ~strcmp(string(resampled.coordinate_frame), "robot_base") || ...
            ~isfield(resampled, 'runs') || ~isstruct(resampled.runs)
        error('MonoTeach:InvalidResampledTaskArtifact', ...
            'Expected a robot-base arc-length resampling artifact.');
    end
end
