%% MonoTeach Stage 3.1B
% Final verification for pre-IK eligibility and contiguous candidate segments.
% This script validates existing segment semantics only; it does not run IK,
% interpolate gaps, plan motion, or command the Legacy robot.

clear;
clc;

format long g;


%% ------------------------------------------------------------
% 0. Resolve paths
% -------------------------------------------------------------

stage3Dir = fileparts(fileparts(mfilename('fullpath')));
fixturePath = fullfile( ...
    stage3Dir, ...
    'data', ...
    'workspace_trajectory_fixture.json');

addpath(genpath(stage3Dir));

fprintf('============================================\n');
fprintf('MonoTeach Stage 3.1B Final Verification\n');
fprintf('============================================\n');

allPassed = true;


%% ------------------------------------------------------------
% 1. Build the fixture TaskTrajectory and segment set
% -------------------------------------------------------------

fprintf('\n[1] Fixture load, task transform, and segmentation\n');

fixtureExists = isfile(fixturePath);
allPassed = report_result( ...
    allPassed, ...
    'Fixture file exists', ...
    fixtureExists);

if ~fixtureExists
    error( ...
        'MonoTeach:MissingWorkspaceTrajectoryFixture', ...
        'Missing Stage 3.1 fixture: %s', ...
        fixturePath);
end

workspaceTrajectory = load_workspace_trajectory(fixturePath);
taskTrajectory = workspace_to_task_trajectory( ...
    workspaceTrajectory, ...
    default_task_plane_config());
taskTrajectoryBefore = taskTrajectory;
segmentSet = build_preik_segments(taskTrajectory);

expectedEligibleMask = logical([true, true, false, true, false]);
eligibleMaskPassed = isequal( ...
    segmentSet.eligible_mask, ...
    expectedEligibleMask);

fprintf( ...
    'Eligible mask : %s\n', ...
    logical_mask_text(segmentSet.eligible_mask));
fprintf('Segment count : %d\n', numel(segmentSet.segments));

allPassed = report_result( ...
    allPassed, ...
    'Fixture eligibility mask', ...
    eligibleMaskPassed);


%% ------------------------------------------------------------
% 2. Confirm contiguous source indices and barrier behavior
% -------------------------------------------------------------

fprintf('\n[2] Contiguous segments and barriers\n');

segmentCountPassed = numel(segmentSet.segments) == 2;
allPassed = report_result( ...
    allPassed, ...
    'Fixture has two pre-IK segments', ...
    segmentCountPassed);

for i = 1:numel(segmentSet.segments)
    segment = segmentSet.segments(i);

    fprintf( ...
        'Segment %d: source_indices=%s, points=%d, t_ms=%.3f -> %.3f\n', ...
        i, ...
        mat2str(segment.source_indices), ...
        numel(segment.samples), ...
        segment.start_t_ms, ...
        segment.end_t_ms);
end

if numel(segmentSet.segments) == 2
    segmentOnePassed = isequal( ...
        segmentSet.segments(1).source_indices, ...
        [1, 2]);
    segmentTwoPassed = isequal( ...
        segmentSet.segments(2).source_indices, ...
        4);
else
    segmentOnePassed = false;
    segmentTwoPassed = false;
end

allPassed = report_result( ...
    allPassed, ...
    'Segment 1 source indices are [1 2]', ...
    segmentOnePassed);
allPassed = report_result( ...
    allPassed, ...
    'Segment 2 source indices are [4]', ...
    segmentTwoPassed);

includedIndices = [segmentSet.segments.source_indices];
invalidSample = taskTrajectory.samples(3);
invalidPassed = ...
    ~ismember(3, includedIndices) && ...
    ~invalidSample.valid && ...
    isempty(invalidSample.x_m) && ...
    isempty(invalidSample.y_m) && ...
    isempty(invalidSample.z_m);

allPassed = report_result( ...
    allPassed, ...
    'Invalid sample is a segment barrier with empty XYZ', ...
    invalidPassed);

outsideSample = taskTrajectory.samples(5);
outsidePassed = ...
    ~ismember(5, includedIndices) && ...
    outsideSample.valid && ...
    ~outsideSample.inside_workspace && ...
    all(isfinite([outsideSample.x_m, outsideSample.y_m, outsideSample.z_m]));

fprintf( ...
    'Outside sample base XYZ [m]: [%.6f %.6f %.6f]\n', ...
    outsideSample.x_m, ...
    outsideSample.y_m, ...
    outsideSample.z_m);

allPassed = report_result( ...
    allPassed, ...
    'Valid-but-outside sample remains evidence but is not segmented', ...
    outsidePassed);


%% ------------------------------------------------------------
% 3. Output contract and non-mutation check
% -------------------------------------------------------------

fprintf('\n[3] SegmentSet contract\n');

contractPassed = ...
    strcmp(string(segmentSet.coordinate_frame), "robot_base") && ...
    strcmp(string(segmentSet.units), "m") && ...
    strcmp(string(segmentSet.metadata.coordinate_frame), "robot_base") && ...
    strcmp(string(segmentSet.metadata.units), "m");

allPassed = report_result( ...
    allPassed, ...
    'SegmentSet coordinate frame and units', ...
    contractPassed);

taskInputUnchangedPassed = isequaln( ...
    taskTrajectory, ...
    taskTrajectoryBefore);

allPassed = report_result( ...
    allPassed, ...
    'TaskTrajectory input remains unchanged', ...
    taskInputUnchangedPassed);


%% ------------------------------------------------------------
% 4. Final result
% -------------------------------------------------------------

fprintf('\n============================================\n');

if allPassed
    fprintf('FINAL RESULT: PASS\n');
else
    fprintf('FINAL RESULT: FAIL\n');
end

fprintf('============================================\n');

if ~allPassed
    error( ...
        'MonoTeach:Stage3_1BVerificationFailed', ...
        'Stage 3.1B verification failed.');
end


%% ------------------------------------------------------------
% Local helpers
% -------------------------------------------------------------

function allPassed = report_result(allPassed, label, condition)

    if condition
        result = 'PASS';
    else
        result = 'FAIL';
    end

    fprintf('%s -> %s\n', label, result);
    allPassed = allPassed && condition;
end


function textValue = logical_mask_text(mask)

    values = repmat({'false'}, 1, numel(mask));
    values(mask) = repmat({'true'}, 1, sum(mask));
    textValue = ['[', strjoin(values, ' '), ']'];
end
