function tests = test_stage3_3
%TEST_STAGE3_3 Writing-posture geometry tests for Stage 3.3 Task 1 Step 1.
%
% Run from the repository root:
%   results = runtests('tests/test_stage3_3.m');

    tests = functiontests(localfunctions);
end


function setupOnce(testCase)

    testFile = mfilename('fullpath');
    repoRoot = fileparts(fileparts(testFile));
    stage3Dir = fullfile(repoRoot, 'stage3');
    stage1Dir = fullfile(repoRoot, 'stage1');
    stage3Path = genpath(stage3Dir);
    addpath(stage3Path);
    addpath(stage1Dir);

    testCase.TestData.stage3Dir = stage3Dir;
    testCase.TestData.stage3Path = stage3Path;
    testCase.TestData.stage1Dir = stage1Dir;
    testCase.TestData.taskPlaneConfig = default_task_plane_config();
    testCase.TestData.ikConfig = default_ik_config();
    testCase.TestData.writingPostureConfig = default_writing_posture_config();
    testCase.TestData.robot = build_legacy_robot();
    testCase.TestData.feasibility = evaluate_writing_anchor_feasibility( ...
        testCase.TestData.robot, ...
        testCase.TestData.taskPlaneConfig, ...
        testCase.TestData.ikConfig, ...
        testCase.TestData.writingPostureConfig);
end


function teardownOnce(testCase)

    rmpath(testCase.TestData.stage3Path);
    rmpath(testCase.TestData.stage1Dir);
end


function testWritingPostureConfigKeepsNormalSignUndecided(testCase)

    config = default_writing_posture_config();

    requiredFields = { ...
        'end_effector', ...
        'tool_axis', ...
        'plane_normal_sign', ...
        'candidate_plane_normal_signs', ...
        'aim_distance_m', ...
        'position_tolerance_m', ...
        'aiming_angular_tolerance_rad', ...
        'solver_algorithm', ...
        'allow_random_restart'};
    verifyTrue(testCase, all(isfield(config, requiredFields)));
    verifyEqual(testCase, config.end_effector, 'body5');
    verifyEqual(testCase, config.tool_axis, 'z');
    verifyEqual(testCase, config.plane_normal_sign, 'undecided');
    verifyEqual(testCase, config.candidate_plane_normal_signs, [+1, -1]);
    verifyGreaterThan(testCase, config.aim_distance_m, 0.0);
end


function testDefaultTaskPlaneNormalIsBasePositiveY(testCase)

    [nPlane, ~] = derive_task_plane_normal(testCase.TestData.taskPlaneConfig);

    verifyEqual(testCase, nPlane, [0; 1; 0], 'AbsTol', 1e-12);
    verifyEqual(testCase, norm(nPlane), 1.0, 'AbsTol', 1e-12);
end


function testSyntheticRotatedPlaneReadsRotationThirdColumn(testCase)

    syntheticConfig = testCase.TestData.taskPlaneConfig;
    syntheticRotation = [ ...
        0, 0, 1; ...
        1, 0, 0; ...
        0, 1, 0];
    syntheticConfig.T_base_taskplane(1:3, 1:3) = syntheticRotation;

    nPlane = derive_task_plane_normal(syntheticConfig);

    verifyEqual(testCase, nPlane, syntheticRotation(:, 3), 'AbsTol', 1e-12);
    verifyGreaterThan(testCase, norm(nPlane - [0; 1; 0]), 0.1);
end


function testCandidateNormalsAreOpposites(testCase)

    [nPlane, candidateNormals] = derive_task_plane_normal( ...
        testCase.TestData.taskPlaneConfig);

    verifyEqual(testCase, candidateNormals(:, 1), nPlane, 'AbsTol', 1e-12);
    verifyEqual(testCase, candidateNormals(:, 2), -nPlane, 'AbsTol', 1e-12);
    verifyEqual( ...
        testCase, ...
        candidateNormals(:, 1) + candidateNormals(:, 2), ...
        zeros(3, 1), ...
        'AbsTol', 1e-12);
end


function testAnchorCandidateAimTargetsFollowTheirSignedNormals(testCase)

    feasibility = testCase.TestData.feasibility;
    config = testCase.TestData.writingPostureConfig;
    candidates = feasibility.candidates;

    verifyEqual(testCase, [candidates.sign], [+1, -1]);
    for candidateIndex = 1:numel(candidates)
        candidate = candidates(candidateIndex);
        aimOffset = candidate.aim_target_m - candidate.target_xyz_m;

        verifyEqual( ...
            testCase, ...
            aimOffset, ...
            config.aim_distance_m * candidate.signed_normal, ...
            'AbsTol', 1e-12);
        verifyEqual( ...
            testCase, ...
            norm(aimOffset), ...
            config.aim_distance_m, ...
            'AbsTol', 1e-12);
    end

    verifyEqual( ...
        testCase, ...
        candidates(1).signed_normal, ...
        -candidates(2).signed_normal, ...
        'AbsTol', 1e-12);
end


function testAnchorFeasibilityRecordsCompleteCandidateEvidence(testCase)

    candidates = testCase.TestData.feasibility.candidates;
    requiredFields = { ...
        'sign', ...
        'target_xyz_m', ...
        'signed_normal', ...
        'aim_target_m', ...
        'q', ...
        'solver_status', ...
        'fk_xyz_m', ...
        'position_error_m', ...
        'fk_tool_z_direction', ...
        'tool_direction_error_rad', ...
        'tool_direction_error_deg', ...
        'within_joint_limits', ...
        'joint_limit_margin', ...
        'distance_to_position_only_q_anchor'};

    verifyEqual(testCase, numel(candidates), 2);
    for candidateIndex = 1:numel(candidates)
        verifyTrue(testCase, all(isfield(candidates(candidateIndex), requiredFields)));
        verifyNotEmpty(testCase, candidates(candidateIndex).solver_status);
    end
end


function testAcceptedCandidatePassesIndependentBackChecks(testCase)

    candidates = testCase.TestData.feasibility.candidates;
    config = testCase.TestData.writingPostureConfig;

    for candidateIndex = 1:numel(candidates)
        candidate = candidates(candidateIndex);
        if candidate.accepted
            verifySize(testCase, candidate.q, [1, 5]);
            verifyTrue(testCase, all(isfinite(candidate.q)));
            verifyLessThanOrEqual( ...
                testCase, ...
                candidate.position_error_m, ...
                config.position_tolerance_m);
            verifyLessThanOrEqual( ...
                testCase, ...
                candidate.tool_direction_error_rad, ...
                config.aiming_angular_tolerance_rad);
            verifyTrue(testCase, candidate.within_joint_limits);
            verifyGreaterThanOrEqual( ...
                testCase, ...
                min(candidate.joint_limit_margin), ...
                -1e-12);
        else
            verifyNotEmpty(testCase, candidate.failure_reason);
        end
    end
end


function testMultiStartDiagnosticSeedSetAndRunsAreDeterministic(testCase)

    diagnosticConfig = default_writing_anchor_diagnostic_config();
    diagnosticConfig.random_seed_count = 1;
    diagnosticConfig.solver_algorithms = {'BFGSGradientProjection'};

    first = diagnose_writing_anchor_multistart( ...
        testCase.TestData.robot, ...
        testCase.TestData.taskPlaneConfig, ...
        testCase.TestData.ikConfig, ...
        testCase.TestData.writingPostureConfig, ...
        diagnosticConfig);
    second = diagnose_writing_anchor_multistart( ...
        testCase.TestData.robot, ...
        testCase.TestData.taskPlaneConfig, ...
        testCase.TestData.ikConfig, ...
        testCase.TestData.writingPostureConfig, ...
        diagnosticConfig);

    verifyEqual(testCase, [first.seed_set.initial_q], [second.seed_set.initial_q], ...
        'AbsTol', 1e-12);
    verifyEqual(testCase, {first.seed_set.name}, {second.seed_set.name});
    verifyEqual(testCase, numel(first.seed_set), 3);
    verifyEqual(testCase, numel(first.runs), 2);
    verifyEqual(testCase, [first.runs.sign], [+1, -1]);
    verifyEqual(testCase, {first.runs.solver_algorithm}, ...
        {'BFGSGradientProjection', 'BFGSGradientProjection'});
    verifyEqual(testCase, [first.runs.accepted_count], [second.runs.accepted_count]);
end


function testMultiStartDiagnosticRetainsTrialAndSummarySemantics(testCase)

    diagnosticConfig = default_writing_anchor_diagnostic_config();
    diagnosticConfig.random_seed_count = 0;
    diagnosticConfig.solver_algorithms = {'LevenbergMarquardt'};
    diagnostic = diagnose_writing_anchor_multistart( ...
        testCase.TestData.robot, ...
        testCase.TestData.taskPlaneConfig, ...
        testCase.TestData.ikConfig, ...
        testCase.TestData.writingPostureConfig, ...
        diagnosticConfig);

    requiredTrialFields = { ...
        'initial_q', ...
        'solver_algorithm', ...
        'candidate_q', ...
        'position_error_m', ...
        'tool_direction_error_rad', ...
        'within_joint_limits', ...
        'joint_limit_margin', ...
        'accepted'};
    requiredSummaryFields = { ...
        'trials_count', ...
        'accepted_count', ...
        'best_position_error_m', ...
        'best_direction_error_rad', ...
        'best_combined_trial_index', ...
        'has_simultaneous_position_and_direction_solution'};

    for runIndex = 1:numel(diagnostic.runs)
        run = diagnostic.runs(runIndex);
        verifyTrue(testCase, all(isfield(run, requiredSummaryFields)));
        verifyEqual(testCase, run.trials_count, 2);
        verifyEqual(testCase, run.accepted_count, sum([run.trials.accepted]));
        for trialIndex = 1:numel(run.trials)
            trial = run.trials(trialIndex);
            verifyTrue(testCase, all(isfield(trial, requiredTrialFields)));
            verifySize(testCase, trial.initial_q, [1, 5]);
            if trial.accepted
                verifyLessThanOrEqual( ...
                    testCase, trial.position_error_m, ...
                    testCase.TestData.writingPostureConfig.position_tolerance_m);
                verifyLessThanOrEqual( ...
                    testCase, trial.tool_direction_error_rad, ...
                    testCase.TestData.writingPostureConfig.aiming_angular_tolerance_rad);
                verifyTrue(testCase, trial.within_joint_limits);
            end
        end
    end
end


function testWritingTaskDofDiagnosisHasVerifiedJacobianSemantics(testCase)

    before = testCase.TestData.robot;
    diagnosis = diagnose_writing_task_dof( ...
        testCase.TestData.robot, ...
        testCase.TestData.taskPlaneConfig, ...
        testCase.TestData.ikConfig, ...
        testCase.TestData.writingPostureConfig);

    verifyEqual(testCase, testCase.TestData.robot, before);
    verifyEqual(testCase, diagnosis.jacobian_shape, [6, 5]);
    verifySize(testCase, diagnosis.angular_contribution, [3, 5]);
    verifySize(testCase, diagnosis.linear_contribution, [3, 5]);
    verifyEqual( ...
        testCase, diagnosis.j5_angular_contribution, ...
        diagnosis.jacobian(1:3, 5), 'AbsTol', 1e-12);
    verifyEqual( ...
        testCase, diagnosis.j5_linear_contribution, ...
        diagnosis.jacobian(4:6, 5), 'AbsTol', 1e-12);

    finiteDifference = diagnosis.finite_difference;
    verifyEqual( ...
        testCase, ...
        finiteDifference.central_position_derivative_m_per_rad', ...
        diagnosis.j5_linear_contribution, ...
        'AbsTol', 1e-8);
    verifyEqual( ...
        testCase, ...
        finiteDifference.central_tool_z_derivative_per_rad', ...
        diagnosis.tool_direction_jacobian_3d(:, 5), ...
        'AbsTol', 1e-8);
end


function testWritingTaskDofDiagnosisIsReproducibleAndKeepsTaskDimensions(testCase)

    first = diagnose_writing_task_dof( ...
        testCase.TestData.robot, ...
        testCase.TestData.taskPlaneConfig, ...
        testCase.TestData.ikConfig, ...
        testCase.TestData.writingPostureConfig);
    second = diagnose_writing_task_dof( ...
        testCase.TestData.robot, ...
        testCase.TestData.taskPlaneConfig, ...
        testCase.TestData.ikConfig, ...
        testCase.TestData.writingPostureConfig);

    verifyEqual(testCase, first.q_anchor, second.q_anchor, 'AbsTol', 1e-12);
    verifyEqual(testCase, first.jacobian, second.jacobian, 'AbsTol', 1e-12);
    verifyEqual(testCase, first.writing_task_jacobian_shape, [5, 5]);
    verifyEqual( ...
        testCase, ...
        first.writing_task_rank, ...
        rank(first.writing_task_jacobian));
    verifyEqual( ...
        testCase, ...
        first.writing_task_singular_values, ...
        svd(first.writing_task_jacobian), ...
        'AbsTol', 1e-12);
end


function testHeightSweepPreservesTaskPlaneGeometryAndResultProvenance(testCase)

    originalTaskPlaneConfig = testCase.TestData.taskPlaneConfig;
    sweepConfig = default_writing_height_sweep_config();
    sweepConfig.anchor_z_values_m = [0.245, 0.255];
    sweepConfig.random_seed_count = 0;

    sweep = sweep_writing_anchor_height( ...
        testCase.TestData.robot, ...
        testCase.TestData.taskPlaneConfig, ...
        testCase.TestData.ikConfig, ...
        testCase.TestData.writingPostureConfig, ...
        sweepConfig);

    verifyEqual(testCase, testCase.TestData.taskPlaneConfig, originalTaskPlaneConfig);
    verifyEqual(testCase, numel(sweep.records), 4);
    verifyEqual(testCase, [sweep.records.anchor_z_m], ...
        [0.245, 0.245, 0.255, 0.255], 'AbsTol', 1e-12);
    verifyEqual(testCase, [sweep.records.sign], [+1, -1, +1, -1]);

    requiredFields = { ...
        'anchor_z_m', ...
        'sign', ...
        'best_candidate_q', ...
        'position_error_m', ...
        'direction_error_rad', ...
        'within_joint_limits', ...
        'minimum_joint_limit_margin', ...
        'solver_status', ...
        'seed_provenance'};
    for recordIndex = 1:numel(sweep.records)
        record = sweep.records(recordIndex);
        heightConfig = record.task_plane_config;
        verifyTrue(testCase, all(isfield(record, requiredFields)));
        verifyEqual( ...
            testCase, ...
            heightConfig.robot_anchor_m(3), ...
            heightConfig.T_base_taskplane(3, 4), ...
            'AbsTol', 1e-12);
        verifyEqual( ...
            testCase, ...
            heightConfig.T_base_taskplane(1:3, 1:3), ...
            originalTaskPlaneConfig.T_base_taskplane(1:3, 1:3), ...
            'AbsTol', 1e-12);
        verifyEqual( ...
            testCase, ...
            heightConfig.robot_anchor_m(1:2), ...
            originalTaskPlaneConfig.robot_anchor_m(1:2), ...
            'AbsTol', 1e-12);
        verifyEqual(testCase, heightConfig.scale, originalTaskPlaneConfig.scale);
        verifyNotEmpty(testCase, record.seed_provenance);
        verifyNotEmpty(testCase, record.solver_status);
    end
end


function testYawHeightSweepPreservesVerticalTaskPlaneAndProvenance(testCase)

    originalTaskPlaneConfig = testCase.TestData.taskPlaneConfig;
    R0 = originalTaskPlaneConfig.T_base_taskplane(1:3, 1:3);
    sweepConfig = default_writing_yaw_sweep_config();
    sweepConfig.yaw_deg_values = [-10, 0];
    sweepConfig.center_z_values_m = [0.245, 0.255];
    sweepConfig.random_seed_count = 0;

    sweep = sweep_writing_task_plane_yaw( ...
        testCase.TestData.robot, ...
        testCase.TestData.taskPlaneConfig, ...
        testCase.TestData.ikConfig, ...
        testCase.TestData.writingPostureConfig, ...
        sweepConfig);

    verifyEqual(testCase, testCase.TestData.taskPlaneConfig, originalTaskPlaneConfig);
    verifyEqual(testCase, numel(sweep.records), 8);
    verifyEqual( ...
        testCase, ...
        [sweep.records.center_z_m], ...
        [0.245, 0.245, 0.245, 0.245, 0.255, 0.255, 0.255, 0.255], ...
        'AbsTol', 1e-12);
    verifyEqual(testCase, [sweep.records.yaw_deg], ...
        [-10, -10, 0, 0, -10, -10, 0, 0]);
    verifyEqual(testCase, [sweep.records.normal_sign], ...
        [+1, -1, +1, -1, +1, -1, +1, -1]);

    zeroYawRecord = sweep.records( ...
        [sweep.records.yaw_deg] == 0 & [sweep.records.normal_sign] == +1);
    verifyEqual(testCase, zeroYawRecord.R_base_taskplane, R0, 'AbsTol', 1e-12);

    requiredFields = { ...
        'yaw_deg', ...
        'R_base_taskplane', ...
        'plane_normal_base', ...
        'normal_sign', ...
        'accepted', ...
        'position_error_m', ...
        'direction_error_rad', ...
        'candidate_q', ...
        'minimum_joint_limit_margin', ...
        'solver_status', ...
        'seed_provenance'};
    for recordIndex = 1:numel(sweep.records)
        record = sweep.records(recordIndex);
        geometry = record.task_plane_geometry;
        verifyTrue(testCase, all(isfield(record, requiredFields)));
        verifyTrue(testCase, geometry.rotation_orthonormal);
        verifyTrue(testCase, geometry.proper_rotation);
        verifyTrue(testCase, geometry.task_y_is_base_negative_z);
        verifyTrue(testCase, geometry.plane_normal_is_horizontal);
        verifyEqual( ...
            testCase, ...
            record.task_plane_translation_m, ...
            [ ...
                originalTaskPlaneConfig.T_base_taskplane(1:2, 4)', ...
                record.center_z_m], ...
            'AbsTol', 1e-12);
        verifyEqual( ...
            testCase, ...
            record.task_plane_config.robot_anchor_m(1:2), ...
            originalTaskPlaneConfig.robot_anchor_m(1:2), ...
            'AbsTol', 1e-12);
        verifyEqual( ...
            testCase, ...
            record.task_plane_config.robot_anchor_m(3), ...
            record.center_z_m, ...
            'AbsTol', 1e-12);
        verifyNotEmpty(testCase, record.seed_provenance);
        verifyNotEmpty(testCase, record.solver_status);
    end
end


function testLocalXYSweepPreservesFixedTaskPlaneGeometryAndProvenance(testCase)

    originalTaskPlaneConfig = testCase.TestData.taskPlaneConfig;
    sweepConfig = default_writing_xy_sweep_config();
    sweepConfig.x_values_m = [0.095, 0.100];
    sweepConfig.y_values_m = [0.035, 0.040];
    sweepConfig.random_seed_count = 0;

    sweep = sweep_writing_task_plane_xy( ...
        testCase.TestData.robot, ...
        testCase.TestData.taskPlaneConfig, ...
        testCase.TestData.ikConfig, ...
        testCase.TestData.writingPostureConfig, ...
        sweepConfig);

    fixedRotation = [ ...
        cosd(-60), -sind(-60), 0; ...
        sind(-60),  cosd(-60), 0; ...
        0,          0,         1] * ...
        originalTaskPlaneConfig.T_base_taskplane(1:3, 1:3);

    verifyEqual(testCase, testCase.TestData.taskPlaneConfig, originalTaskPlaneConfig);
    verifyEqual(testCase, numel(sweep.records), 4);
    verifyEqual( ...
        testCase, [sweep.records.x_m], [0.095, 0.100, 0.095, 0.100], ...
        'AbsTol', 1e-12);
    verifyEqual( ...
        testCase, [sweep.records.y_m], [0.035, 0.035, 0.040, 0.040], ...
        'AbsTol', 1e-12);

    requiredFields = { ...
        'x_m', ...
        'y_m', ...
        'accepted', ...
        'position_error_m', ...
        'direction_error_deg', ...
        'candidate_q', ...
        'minimum_joint_limit_margin', ...
        'solver_status', ...
        'seed_provenance'};
    for recordIndex = 1:numel(sweep.records)
        record = sweep.records(recordIndex);
        config = record.task_plane_config;
        geometry = record.task_plane_geometry;
        verifyTrue(testCase, all(isfield(record, requiredFields)));
        verifyEqual( ...
            testCase, config.robot_anchor_m(1:2), [record.x_m, record.y_m], ...
            'AbsTol', 1e-12);
        verifyEqual( ...
            testCase, config.T_base_taskplane(1:2, 4)', ...
            [record.x_m, record.y_m], 'AbsTol', 1e-12);
        verifyEqual( ...
            testCase, config.robot_anchor_m(3), sweepConfig.fixed_center_z_m, ...
            'AbsTol', 1e-12);
        verifyEqual( ...
            testCase, config.T_base_taskplane(3, 4), ...
            sweepConfig.fixed_center_z_m, 'AbsTol', 1e-12);
        verifyEqual( ...
            testCase, config.T_base_taskplane(1:3, 1:3), fixedRotation, ...
            'AbsTol', 1e-12);
        verifyTrue(testCase, geometry.rotation_unchanged);
        verifyTrue(testCase, geometry.translation_matches_anchor);
        verifyTrue(testCase, geometry.translation_z_matches_fixed_center);
        verifyEqual(testCase, config.scale, originalTaskPlaneConfig.scale);
        verifyNotEmpty(testCase, record.seed_provenance);
        verifyNotEmpty(testCase, record.solver_status);
    end
end


function testFullTaskPlaneScanUsesStage31MappingAndIndependentGridOrder(testCase)

    originalTaskPlaneConfig = testCase.TestData.taskPlaneConfig;
    scanConfig = default_writing_full_plane_scan_config();
    scanConfig.workspace_x_values_mm = [0.0, 95.0, 190.0];
    scanConfig.workspace_y_values_mm = [0.0, 145.0, 290.0];
    scanConfig.random_seed_count = 0;

    first = scan_writing_full_task_plane( ...
        testCase.TestData.robot, ...
        testCase.TestData.taskPlaneConfig, ...
        testCase.TestData.ikConfig, ...
        testCase.TestData.writingPostureConfig, ...
        scanConfig);
    reverseConfig = scanConfig;
    reverseConfig.traversal_order = 'workspace_y_then_x';
    second = scan_writing_full_task_plane( ...
        testCase.TestData.robot, ...
        testCase.TestData.taskPlaneConfig, ...
        testCase.TestData.ikConfig, ...
        testCase.TestData.writingPostureConfig, ...
        reverseConfig);

    candidateConfig = first.candidate_task_plane_config;
    R0 = originalTaskPlaneConfig.T_base_taskplane(1:3, 1:3);
    expectedRotation = [ ...
        cosd(-60), -sind(-60), 0; ...
        sind(-60),  cosd(-60), 0; ...
        0,          0,         1] * R0;

    verifyEqual(testCase, testCase.TestData.taskPlaneConfig, originalTaskPlaneConfig);
    verifyEqual(testCase, numel(first.records), 9);
    verifyEqual(testCase, numel(second.records), 9);
    verifyEqual( ...
        testCase, candidateConfig.robot_anchor_m, [0.105, 0.060, 0.195], ...
        'AbsTol', 1e-12);
    verifyEqual( ...
        testCase, candidateConfig.T_base_taskplane(1:3, 4)', ...
        [0.105, 0.060, 0.195], 'AbsTol', 1e-12);
    verifyEqual( ...
        testCase, candidateConfig.T_base_taskplane(1:3, 1:3), ...
        expectedRotation, 'AbsTol', 1e-12);

    requiredFields = { ...
        'workspace_x_mm', ...
        'workspace_y_mm', ...
        'task_plane_xyz_m', ...
        'base_xyz_m', ...
        'accepted', ...
        'position_error_m', ...
        'direction_error_deg', ...
        'candidate_q', ...
        'minimum_joint_limit_margin', ...
        'solver_status', ...
        'seed_provenance'};
    for recordIndex = 1:numel(first.records)
        record = first.records(recordIndex);
        expectedTaskPoint = candidateConfig.scale * ( ...
            [record.workspace_x_mm, record.workspace_y_mm] - ...
            candidateConfig.workspace_center_mm);
        expectedBasePointH = candidateConfig.T_base_taskplane * ...
            [expectedTaskPoint, 0.0, 1.0]';
        verifyTrue(testCase, all(isfield(record, requiredFields)));
        verifyEqual( ...
            testCase, record.base_xyz_m, expectedBasePointH(1:3)', ...
            'AbsTol', 1e-12);
        verifyEqual( ...
            testCase, record.task_plane_xyz_m, ...
            [expectedTaskPoint, 0.0], 'AbsTol', 1e-12);
        verifyEqual( ...
            testCase, record.task_plane_config.T_base_taskplane, ...
            candidateConfig.T_base_taskplane, 'AbsTol', 1e-12);
        verifyNotEmpty(testCase, record.seed_provenance);
        verifyNotEmpty(testCase, record.solver_status);
    end

    firstTargets = sortrows([[first.records.workspace_x_mm]', ...
        [first.records.workspace_y_mm]']);
    secondTargets = sortrows([[second.records.workspace_x_mm]', ...
        [second.records.workspace_y_mm]']);
    verifyEqual(testCase, firstTargets, secondTargets, 'AbsTol', 1e-12);

    firstEvidence = sortrows([[first.records.workspace_x_mm]', ...
        [first.records.workspace_y_mm]', ...
        double([first.records.accepted])', ...
        [first.records.position_error_m]', ...
        [first.records.direction_error_deg]', ...
        [first.records.minimum_joint_limit_margin]']);
    secondEvidence = sortrows([[second.records.workspace_x_mm]', ...
        [second.records.workspace_y_mm]', ...
        double([second.records.accepted])', ...
        [second.records.position_error_m]', ...
        [second.records.direction_error_deg]', ...
        [second.records.minimum_joint_limit_margin]']);
    verifyEqual(testCase, firstEvidence, secondEvidence, 'AbsTol', 1e-9);

    centerRecord = first.records( ...
        [first.records.workspace_x_mm] == 95.0 & ...
        [first.records.workspace_y_mm] == 145.0);
    verifyEqual( ...
        testCase, centerRecord.base_xyz_m, scanConfig.candidate_center_m, ...
        'AbsTol', 1e-12);
    verifyEqual(testCase, numel(first.summary.corner_records), 4);
end


function testUniformScaleSweepKeepsSourceWorkspaceAndScalesTargets(testCase)

    originalTaskPlaneConfig = testCase.TestData.taskPlaneConfig;
    sweepConfig = default_writing_scale_sweep_config();
    sweepConfig.scale_values_m_per_mm = [0.00010, 0.00020];
    sweepConfig.coarse_workspace_x_values_mm = [0.0, 95.0, 190.0];
    sweepConfig.coarse_workspace_y_values_mm = [0.0, 145.0, 290.0];
    sweepConfig.verification_workspace_x_values_mm = ...
        sweepConfig.coarse_workspace_x_values_mm;
    sweepConfig.verification_workspace_y_values_mm = ...
        sweepConfig.coarse_workspace_y_values_mm;
    sweepConfig.random_seed_count = 0;

    sweep = sweep_writing_task_plane_scale( ...
        testCase.TestData.robot, ...
        testCase.TestData.taskPlaneConfig, ...
        testCase.TestData.ikConfig, ...
        testCase.TestData.writingPostureConfig, ...
        sweepConfig);

    verifyEqual(testCase, testCase.TestData.taskPlaneConfig, originalTaskPlaneConfig);
    verifyEqual(testCase, numel(sweep.coarse_records), 2);
    for recordIndex = 1:numel(sweep.coarse_records)
        record = sweep.coarse_records(recordIndex);
        scan = record.scan;
        candidateConfig = scan.candidate_task_plane_config;
        verifyEqual( ...
            testCase, record.robot_physical_width_m, ...
            190.0 * record.scale_m_per_mm, 'AbsTol', 1e-12);
        verifyEqual( ...
            testCase, record.robot_physical_height_m, ...
            290.0 * record.scale_m_per_mm, 'AbsTol', 1e-12);
        verifyEqual(testCase, candidateConfig.workspace_width_mm, 190.0);
        verifyEqual(testCase, candidateConfig.workspace_height_mm, 290.0);
        verifyEqual( ...
            testCase, candidateConfig.robot_anchor_m, ...
            sweepConfig.candidate_center_m, 'AbsTol', 1e-12);
        verifyEqual( ...
            testCase, candidateConfig.T_base_taskplane(1:3, 4)', ...
            sweepConfig.candidate_center_m, 'AbsTol', 1e-12);
        verifyEqual(testCase, numel(scan.records), 9);
        for pointIndex = 1:numel(scan.records)
            point = scan.records(pointIndex);
            verifyNotEmpty(testCase, point.seed_provenance);
            verifyNotEmpty(testCase, point.solver_status);
        end
    end

    lowScaleCorner = sweep.coarse_records(1).scan.records( ...
        [sweep.coarse_records(1).scan.records.workspace_x_mm] == 0.0 & ...
        [sweep.coarse_records(1).scan.records.workspace_y_mm] == 0.0);
    highScaleCorner = sweep.coarse_records(2).scan.records( ...
        [sweep.coarse_records(2).scan.records.workspace_x_mm] == 0.0 & ...
        [sweep.coarse_records(2).scan.records.workspace_y_mm] == 0.0);
    lowOffsetM = norm(lowScaleCorner.base_xyz_m - sweepConfig.candidate_center_m);
    highOffsetM = norm(highScaleCorner.base_xyz_m - sweepConfig.candidate_center_m);
    verifyEqual( ...
        testCase, highOffsetM / lowOffsetM, ...
        sweepConfig.scale_values_m_per_mm(2) / ...
            sweepConfig.scale_values_m_per_mm(1), ...
        'AbsTol', 1e-12);
end


function testWritingCandidateConfigIsSeparateAndUsesApprovedGeometry(testCase)

    baselineConfig = testCase.TestData.taskPlaneConfig;
    candidate = default_writing_candidate_config();
    candidateTaskPlaneConfig = build_writing_candidate_task_plane_config( ...
        baselineConfig, candidate);
    expectedRotation = [ ...
        cosd(-60), -sind(-60), 0; ...
        sind(-60),  cosd(-60), 0; ...
        0,          0,         1] * ...
        baselineConfig.T_base_taskplane(1:3, 1:3);

    verifyEqual(testCase, baselineConfig, testCase.TestData.taskPlaneConfig);
    verifyEqual(testCase, candidate.center_m, [0.105, 0.060, 0.195]);
    verifyEqual(testCase, candidate.scale_m_per_mm, 0.00020);
    verifyEqual(testCase, candidateTaskPlaneConfig.robot_anchor_m, ...
        candidate.center_m, 'AbsTol', 1e-12);
    verifyEqual(testCase, candidateTaskPlaneConfig.scale, ...
        candidate.scale_m_per_mm, 'AbsTol', 1e-12);
    verifyEqual(testCase, candidateTaskPlaneConfig.T_base_taskplane(1:3, 4)', ...
        candidate.center_m, 'AbsTol', 1e-12);
    verifyEqual(testCase, candidateTaskPlaneConfig.T_base_taskplane(1:3, 1:3), ...
        expectedRotation, 'AbsTol', 1e-12);
    verifyEqual(testCase, candidateTaskPlaneConfig.workspace_width_mm, 190.0);
    verifyEqual(testCase, candidateTaskPlaneConfig.workspace_height_mm, 290.0);
end


function testWritingRecoveryLadderOrdersMapsAndDeduplicatesSeeds(testCase)

    centerSeed = struct('q', [0.10, 0.20, 0.30, 0.40, 0.50]);
    previousQ = [0.11, 0.21, 0.31, 0.41, 0.51];
    positionLookup = struct( ...
        'source_indices', [700, 701], ...
        'q_rad', [ ...
            0.12, 0.22, 0.32, 0.42, 0.52; ...
            centerSeed.q], ...
        'provenance', 'same_source_position_only_q');
    homeQ = [0.13, 0.23, 0.33, 0.43, 0.53];
    policy = default_writing_recovery_policy('position_only_recovery');

    mapped = build_writing_recovery_ladder( ...
        previousQ, positionLookup, 700, centerSeed, homeQ, policy);
    verifyEqual(testCase, {mapped.provenance}, { ...
        'previous_success_q', 'same_source_position_only_q', ...
        'candidate_center_writing_q', 'home_configuration'});
    verifyEqual(testCase, mapped(1).q, previousQ, 'AbsTol', 1e-12);
    verifyEqual(testCase, mapped(2).q, positionLookup.q_rad(1, :), ...
        'AbsTol', 1e-12);

    missing = build_writing_recovery_ladder( ...
        [], positionLookup, 999, centerSeed, homeQ, policy);
    verifyEqual(testCase, {missing.provenance}, ...
        {'candidate_center_writing_q', 'home_configuration'});

    duplicate = build_writing_recovery_ladder( ...
        previousQ, positionLookup, 701, centerSeed, centerSeed.q, policy);
    verifyEqual(testCase, {duplicate.provenance}, { ...
        'previous_success_q', 'same_source_position_only_q'});
end


function testPositionOnlySeedLookupUsesAcceptedSourceIndexQ(testCase)

    pointA = struct('source_index', 41, 'q', [1, 2, 3, 4, 5]);
    pointB = struct('source_index', 43, 'q', [6, 7, 8, 9, 10]);
    positionResultSet = struct('segments', struct('results', [pointA, pointB]));
    lookup = build_position_only_seed_lookup(positionResultSet);

    verifyEqual(testCase, lookup.source_indices, [41, 43]);
    verifyEqual(testCase, lookup.q_rad, [pointA.q; pointB.q], 'AbsTol', 1e-12);
    verifyEqual(testCase, lookup.provenance, 'same_source_position_only_q');
end


function testWritingContinuousSolverRecordsRecoveryAttemptsAndBarriers(testCase)

    candidate = default_writing_candidate_config();
    candidateTaskPlaneConfig = build_writing_candidate_task_plane_config( ...
        testCase.TestData.taskPlaneConfig, candidate);
    centerSeed = resolve_writing_candidate_center_seed( ...
        testCase.TestData.robot, candidateTaskPlaneConfig, ...
        testCase.TestData.ikConfig, ...
        testCase.TestData.writingPostureConfig, candidate);
    segmentSet = synthetic_writing_failure_segment_set(candidate.center_m);

    positionLookup = struct( ...
        'source_indices', 503, ...
        'q_rad', centerSeed.q + [0.01, 0.01, 0.01, 0.01, 0.01], ...
        'provenance', 'same_source_position_only_q');
    policy = default_writing_recovery_policy('position_only_recovery');
    result = solve_writing_ik_segments( ...
        testCase.TestData.robot, segmentSet, centerSeed, ...
        candidateTaskPlaneConfig, testCase.TestData.writingPostureConfig, ...
        candidate, positionLookup, policy);

    verifyEqual(testCase, result.task_definition, ...
        'xyz_plus_body5_local_z_aiming');
    verifyEqual(testCase, result.tool_axis, 'body5_local_z');
    verifyEqual( ...
        testCase, result.restart_policy, ...
        'position_only_recovery');
    verifyEqual(testCase, result.summary.success_point_count, 3);
    verifyEqual(testCase, result.summary.failure_count, 1);
    verifyEqual(testCase, result.summary.ik_success_segment_count, 2);
    verifyEqual(testCase, result.failures(1).source_index, 503);
    verifyEmpty(testCase, result.failures(1).q);
    verifyEqual(testCase, result.failures(1).attempt_count, ...
        numel(result.failures(1).attempts));
    verifyEqual(testCase, result.failures(1).attempted_seed_provenances(1:2), ...
        {'previous_success_q', 'same_source_position_only_q'});
    verifyEqual(testCase, result.segments(1).source_indices, [501, 502]);
    verifyEqual(testCase, result.segments(2).source_indices, 504);
    verifyEqual( ...
        testCase, result.segments(1).results(1).seed_q, centerSeed.q, ...
        'AbsTol', 1e-12);
    verifyEqual( ...
        testCase, result.segments(1).results(2).seed_q, ...
        result.segments(1).results(1).q, 'AbsTol', 1e-12);
    verifyEqual( ...
        testCase, result.segments(1).results(2).seed_provenance, ...
        'previous_success_q');
    verifyEqual( ...
        testCase, result.segments(1).results(2).accepted_seed_provenance, ...
        'previous_success_q');
    verifyEqual(testCase, result.segments(1).results(2).attempt_count, 1);
    verifyEqual( ...
        testCase, result.segments(1).results(2).attempted_seed_provenances, ...
        {'previous_success_q'});
    verifyEqual( ...
        testCase, result.segments(2).results(1).seed_q, centerSeed.q, ...
        'AbsTol', 1e-12);
    verifyEqual( ...
        testCase, result.segments(2).results(1).seed_provenance, ...
        'candidate_center_writing_q');
    verifyEqual(testCase, result.segments(2).results(1).attempt_count, 1);
    verifyLessThanOrEqual( ...
        testCase, result.segments(1).results(1).position_error_m, ...
        testCase.TestData.writingPostureConfig.position_tolerance_m);
    verifyLessThanOrEqual( ...
        testCase, result.segments(1).results(1).tool_direction_error_rad, ...
        testCase.TestData.writingPostureConfig.aiming_angular_tolerance_rad);

    forwardBeforeRescue = result;
    backward = rescue_writing_ik_backward( ...
        testCase.TestData.robot, segmentSet, result, candidateTaskPlaneConfig, ...
        testCase.TestData.writingPostureConfig, candidate);
    verifyEqual(testCase, result, forwardBeforeRescue);
    verifyEqual(testCase, backward.summary.success_point_count, 3);
    verifyEqual(testCase, backward.summary.failure_count, 1);
    verifyEqual(testCase, backward.summary.ik_success_segment_count, 2);
    verifyEqual(testCase, backward.backward_rescue_attempts.source_index, 503);
    verifyFalse(testCase, backward.backward_rescue_attempts.accepted);
    remaining = backward.result_set.failures(1);
    verifyTrue(testCase, remaining.backward_rescue_attempted);
    verifyEqual(testCase, remaining.backward_rescue_provenance, ...
        'next_success_writing_q');
    verifyTrue(testCase, isfield(remaining, 'best_position_error_m'));
    verifyTrue(testCase, isfield(remaining, ...
        'all_deterministic_attempt_provenances'));
    verifyTrue(testCase, isfield(backward.summary, ...
        'accepted_seed_provenance_distribution'));
end


function testBackwardRescuePlanMapsNextSuccessWithoutCrossingBarrier(testCase)

    segmentSet = struct('segments', [ ...
        struct('source_indices', [11, 12, 13]), ...
        struct('source_indices', 21)]);
    point11 = struct('source_index', 11, 'q', [1, 0, 0, 0, 0]);
    point13 = struct('source_index', 13, 'q', [3, 0, 0, 0, 0]);
    forward = struct( ...
        'segments', [ ...
            struct('results', [point11, point13])], ...
        'failures', [struct('source_index', 12), struct('source_index', 21)]);

    plan = build_backward_writing_rescue_plan(segmentSet, forward);
    verifyEqual(testCase, [plan.records.source_index], [12, 21]);
    verifyTrue(testCase, plan.records(1).eligible_for_backward_rescue);
    verifyEqual(testCase, plan.records(1).next_success_source_index, 13);
    verifyEqual(testCase, plan.records(1).next_success_q, point13.q, ...
        'AbsTol', 1e-12);
    verifyFalse(testCase, plan.records(2).eligible_for_backward_rescue);
    verifyTrue(testCase, isnan(plan.records(2).next_success_source_index));
    verifyEmpty(testCase, plan.records(2).next_success_q);
end


function testBackwardRescueCanMergeAdjacentForwardSuccessSegments(testCase)

    candidate = default_writing_candidate_config();
    taskPlane = build_writing_candidate_task_plane_config( ...
        testCase.TestData.taskPlaneConfig, candidate);
    centerSeed = resolve_writing_candidate_center_seed( ...
        testCase.TestData.robot, taskPlane, testCase.TestData.ikConfig, ...
        testCase.TestData.writingPostureConfig, candidate);
    segmentSet = synthetic_two_center_segment_set(candidate.center_m);
    forward = solve_writing_ik_segments( ...
        testCase.TestData.robot, synthetic_writing_failure_segment_set( ...
        candidate.center_m), centerSeed, taskPlane, ...
        testCase.TestData.writingPostureConfig, candidate, ...
        struct('source_indices', zeros(1, 0), 'q_rad', zeros(0, 5), ...
        'provenance', 'same_source_position_only_q'), ...
        default_writing_recovery_policy('legacy_previous_then_center'));
    rescuedForward = forward;
    point = forward.segments(1).results(1);
    point.source_index = 602;
    point.t_ms = 100.0;
    point.target_xyz_m = candidate.center_m;
    point.aim_target_m = candidate.center_m + 0.050 * [0.866025403784, 0.5, 0.0];
    failure = forward.failures(1);
    failure.source_index = 601;
    failure.t_ms = 0.0;
    failure.target_xyz_m = candidate.center_m;
    failure.aim_target_m = point.aim_target_m;
    rescuedForward.segments = struct( ...
        'preik_segment_index', 1, 'source_indices', 602, 't_ms', 100.0, ...
        'q_rad', point.q, 'results', point);
    rescuedForward.failures = failure;

    backward = rescue_writing_ik_backward( ...
        testCase.TestData.robot, segmentSet, rescuedForward, taskPlane, ...
        testCase.TestData.writingPostureConfig, candidate);
    verifyEqual(testCase, backward.backward_rescued_source_indices, 601);
    verifyEqual(testCase, backward.summary.success_point_count, 2);
    verifyEqual(testCase, backward.summary.failure_count, 0);
    verifyEqual(testCase, backward.summary.ik_success_segment_count, 1);
    verifyEqual(testCase, backward.result_set.segments.source_indices, [601, 602]);
    verifyEqual(testCase, ...
        backward.result_set.segments.results(1).accepted_seed_provenance, ...
        'next_success_writing_q');
end


function testTaskArcLengthResamplingMakesLineWaypointsUniform(testCase)

    taskTrajectory = synthetic_task_trajectory([ ...
        0.000, 0.000, 0.000; ...
        0.005, 0.000, 0.000; ...
        0.010, 0.000, 0.000], [true, true, true], [true, true, true]);
    config = default_task_resampling_config();
    config.target_spacing_m = 0.0025;
    resampled = resample_task_trajectory_arclength(taskTrajectory, config);
    points = resampled.runs(1).points;

    verifyEqual(testCase, vertcat(points.xyz_m), [ ...
        0.0000, 0.0000, 0.0000; ...
        0.0025, 0.0000, 0.0000; ...
        0.0050, 0.0000, 0.0000; ...
        0.0075, 0.0000, 0.0000; ...
        0.0100, 0.0000, 0.0000], 'AbsTol', 1e-12);
    verifyEqual(testCase, [points.resampled_index], 1:5);
    verifyEqual(testCase, points(2).source_bracket_indices, [1, 2]);
    verifyEqual(testCase, points(2).interpolation_ratio, 0.5, 'AbsTol', 1e-12);
    statistics = resampled.summary.spacing_statistics_m;
    verifyEqual(testCase, [statistics.min_m, statistics.mean_m, statistics.max_m], ...
        [0.0025, 0.0025, 0.0025], 'AbsTol', 1e-12);
end


function testTaskArcLengthResamplingPreservesPolylineEndpoints(testCase)

    taskTrajectory = synthetic_task_trajectory([ ...
        0.000, 0.000, 0.000; ...
        0.010, 0.000, 0.000; ...
        0.010, 0.010, 0.000], [true, true, true], [true, true, true]);
    config = default_task_resampling_config();
    config.target_spacing_m = 0.006;
    resampled = resample_task_trajectory_arclength(taskTrajectory, config);
    points = resampled.runs(1).points;

    verifyEqual(testCase, points(1).xyz_m, [0.000, 0.000, 0.000], 'AbsTol', 1e-12);
    verifyEqual(testCase, points(end).xyz_m, [0.010, 0.010, 0.000], 'AbsTol', 1e-12);
    verifyEqual(testCase, points(3).xyz_m, [0.010, 0.002, 0.000], 'AbsTol', 1e-12);
    verifyEqual(testCase, points(3).source_bracket_indices, [2, 3]);
    verifyEqual(testCase, points(3).interpolation_ratio, 0.2, 'AbsTol', 1e-12);
end


function testTaskArcLengthResamplingNeverCrossesInvalidOrOutsideBarrier(testCase)

    taskTrajectory = synthetic_task_trajectory([ ...
        0.000, 0.000, 0.000; ...
        0.004, 0.000, 0.000; ...
        0.008, 0.000, 0.000; ...
        0.012, 0.000, 0.000; ...
        0.016, 0.000, 0.000; ...
        0.020, 0.000, 0.000], ...
        [true, true, false, true, true, true], ...
        [true, true, false, true, false, true]);
    config = default_task_resampling_config();
    config.target_spacing_m = 0.002;
    resampled = resample_task_trajectory_arclength(taskTrajectory, config);

    verifyEqual(testCase, numel(resampled.runs), 3);
    verifyEqual(testCase, {resampled.runs.source_indices}, {[1, 2], 4, 6});
    for runIndex = 1:numel(resampled.runs)
        pointBrackets = vertcat(resampled.runs(runIndex).points.source_bracket_indices);
        sourceIndices = resampled.runs(runIndex).source_indices;
        verifyTrue(testCase, all(ismember(pointBrackets(:), sourceIndices)));
    end
end


function testTaskArcLengthResamplingIsDerivedAndRetainsProvenance(testCase)

    taskTrajectory = synthetic_task_trajectory([ ...
        0.000, 0.000, 0.000; ...
        0.003, 0.000, 0.000], [true, true], [true, true]);
    inputBefore = taskTrajectory;
    config = default_task_resampling_config();
    config.target_spacing_m = 0.002;
    resampled = resample_task_trajectory_arclength(taskTrajectory, config);
    point = resampled.runs(1).points(2);

    verifyEqual(testCase, taskTrajectory, inputBefore);
    verifyEqual(testCase, resampled.artifact_type, ...
        'task_trajectory_arclength_resampling');
    verifyEqual(testCase, point.source_bracket_indices, [1, 2]);
    verifyEqual(testCase, point.interpolation_ratio, 2/3, 'AbsTol', 1e-12);
    verifyEqual(testCase, point.original_run_index, 1);
    verifyEqual(testCase, point.source_arclength_m, 0.002, 'AbsTol', 1e-12);
    verifyEqual(testCase, point.interpolated_t_ms, 200/3, 'AbsTol', 1e-12);
end


function testResampledAdapterRetainsProvenanceAndBarrierRuns(testCase)

    taskTrajectory = synthetic_task_trajectory([ ...
        0.000, 0.000, 0.000; ...
        0.004, 0.000, 0.000; ...
        0.008, 0.000, 0.000; ...
        0.012, 0.000, 0.000], [true, true, false, true], ...
        [true, true, false, true]);
    config = default_task_resampling_config();
    config.target_spacing_m = 0.002;
    resampled = resample_task_trajectory_arclength(taskTrajectory, config);
    adapter = resampled_task_to_preik_segments(resampled);

    verifyEqual(testCase, numel(adapter.segments), 2);
    verifyEqual(testCase, adapter.summary.preik_segment_count, 2);
    first = adapter.segments(1).samples(2);
    verifyEqual(testCase, first.resampled_index, 2);
    verifyEqual(testCase, first.source_bracket_indices, [1, 2]);
    verifyEqual(testCase, first.interpolation_ratio, 0.5, 'AbsTol', 1e-12);
    verifyEqual(testCase, first.original_run_index, 1);
    verifyEqual(testCase, first.source_arclength_m, 0.002, 'AbsTol', 1e-12);
    verifyTrue(testCase, all(adapter.segments(1).source_indices < ...
        adapter.segments(2).source_indices));
end


function testResampledPositionOnlyIKUsesResampledXYZAndDecoratesResult(testCase)

    candidate = default_writing_candidate_config();
    taskPlane = build_writing_candidate_task_plane_config( ...
        testCase.TestData.taskPlaneConfig, candidate);
    taskTrajectory = synthetic_task_trajectory(candidate.center_m, true, true);
    resampled = resample_task_trajectory_arclength(taskTrajectory, ...
        default_task_resampling_config());
    adapter = resampled_task_to_preik_segments(resampled);
    anchor = solve_anchor_ik( ...
        testCase.TestData.robot, taskPlane, testCase.TestData.ikConfig);
    result = solve_ik_segments( ...
        testCase.TestData.robot, adapter, anchor, testCase.TestData.ikConfig);
    result = attach_resampled_provenance_to_ik_result(result, adapter);
    point = result.segments.results;

    verifyEqual(testCase, point.source_index, ...
        adapter.segments.samples.resampled_index);
    verifyEqual(testCase, point.target_xyz_m, ...
        adapter.segments.samples(1).x_m * [1, 0, 0] + ...
        adapter.segments.samples(1).y_m * [0, 1, 0] + ...
        adapter.segments.samples(1).z_m * [0, 0, 1], 'AbsTol', 1e-12);
    verifyEqual(testCase, point.resampled_provenance.xyz_m, point.target_xyz_m, ...
        'AbsTol', 1e-12);
end


function testWritingArclengthCoverageReportsFailuresWithBrackets(testCase)

    samples = [ ...
        adapter_test_sample(1, 0.000, [10, 11]), ...
        adapter_test_sample(2, 0.002, [11, 12]), ...
        adapter_test_sample(3, 0.004, [12, 13])];
    segmentSet = struct('segments', struct( ...
        'source_indices', [1, 2, 3], 'samples', samples));
    accepted = struct('source_index', 1, 'q', zeros(1,5), 'delta_q', [], ...
        'position_error_m', 0, 'joint_limit_margin', ones(1,5));
    failed = struct('source_index', 2, 'reason', 'position_error_exceeds_tolerance');
    writing = struct('segments', struct('results', accepted), 'failures', failed);
    coverage = summarize_writing_arclength_coverage(segmentSet, writing);

    verifyEqual(testCase, coverage.total_arclength_m, 0.004, 'AbsTol', 1e-12);
    verifyEqual(testCase, coverage.accepted_sampled_arclength_m, 0.0, 'AbsTol', 1e-12);
    verifyEqual(testCase, coverage.failed_points.source_bracket_indices, [11, 12]);
    verifyEqual(testCase, coverage.failed_points.source_arclength_m, 0.002, ...
        'AbsTol', 1e-12);
end


function testTaskPathIKABSummaryKeepsEachCaseStatistics(testCase)

    rawSummary = synthetic_writing_summary(8, 2, 3, 0.8);
    resampledSummary = synthetic_writing_summary(5, 1, 2, 5/6);
    rawCoverage = struct('accepted_sampled_arclength_m', 0.006, ...
        'total_arclength_m', 0.010, ...
        'accepted_sampled_coverage_fraction', 0.6, ...
        'failed_points', struct('source_index', 7));
    resampledCoverage = struct('accepted_sampled_arclength_m', 0.008, ...
        'total_arclength_m', 0.010, ...
        'accepted_sampled_coverage_fraction', 0.8, ...
        'failed_points', struct('source_index', 4));
    comparison = summarize_task_path_ik_ab( ...
        10, rawSummary, rawCoverage, 6, resampledSummary, resampledCoverage);

    verifyEqual(testCase, comparison.frame_driven.sample_count, 10);
    verifyEqual(testCase, comparison.frame_driven.writing_success_rate, 0.8);
    verifyEqual(testCase, comparison.frame_driven.accepted_sampled_arclength_m, ...
        0.006, 'AbsTol', 1e-12);
    verifyEqual(testCase, comparison.uniform_arclength.sample_count, 6);
    verifyEqual(testCase, comparison.uniform_arclength.writing_success_rate, 5/6, ...
        'AbsTol', 1e-12);
    verifyEqual(testCase, ...
        comparison.uniform_arclength.failed_points.source_index, 4);
end


function testTimedJointTrajectoryIsVelocityLimitedAndPreservesIKInput(testCase)

    ikResultSet = synthetic_timed_ik_result_set();
    original = ikResultSet;
    config = default_timed_joint_trajectory_config();
    config.max_velocity_rad_s = [1.0, 2.0, 3.0, 4.0, 5.0];
    config.minimum_segment_dt_s = 0.05;
    timed = time_parameterize_ik_success_segments(ikResultSet, config);

    verifyEqual(testCase, ikResultSet, original);
    verifyEqual(testCase, timed.artifact_type, 'TimedJointTrajectory');
    verifyEqual(testCase, timed.summary.timed_segment_count, 2);
    verifyTrue(testCase, timed.summary.all_velocity_limits_satisfied);
    verifyEqual(testCase, timed.segments(1).duration_s, 0.25, 'AbsTol', 1e-12);
    verifyEqual(testCase, [timed.segments(1).waypoints.t_s], [0.0, 0.20, 0.25], ...
        'AbsTol', 1e-12);
    verifyEqual(testCase, timed.segments(1).waypoints(3).dt_s, 0.05, ...
        'AbsTol', 1e-12);
    verifyEqual(testCase, timed.segments(1).waypoints(3).step_velocity_rad_s, ...
        zeros(1, 5), 'AbsTol', 1e-12);
    verifyTrue(testCase, all(diff([timed.segments(1).waypoints.t_s]) > 0));
    verifyTrue(testCase, all(diff([timed.segments(2).waypoints.t_s]) > 0));
    allWaypoints = [timed.segments(1).waypoints, timed.segments(2).waypoints];
    velocity = abs(vertcat(allWaypoints.step_velocity_rad_s));
    verifyLessThanOrEqual(testCase, velocity, ...
        config.max_velocity_rad_s + 1.0e-12);
    verifyEqual(testCase, timed.segments(2).waypoints(1).t_s, 0.0, ...
        'AbsTol', 1e-12);
    verifyEqual(testCase, timed.segments(2).waypoints(1).dt_s, 0.0, ...
        'AbsTol', 1e-12);
    verifyEqual(testCase, timed.segments(2).waypoints(1).q_rad, ...
        ikResultSet.segments(2).results(1).q, 'AbsTol', 1e-12);
    verifyEqual(testCase, timed.segments(1).waypoints(2).provenance.source_index, 102);
end


function testMinimumJerkContinuousTrajectoryPreservesWaypointsAndLimits(testCase)

    ikResultSet = synthetic_monotonic_timed_ik_result_set();
    config = default_timed_joint_trajectory_config();
    timed = time_parameterize_ik_success_segments(ikResultSet, config);
    timedBefore = timed;
    continuous = generate_minimum_jerk_continuous_joint_trajectory(timed, config);

    verifyEqual(testCase, timed, timedBefore);
    verifyEqual(testCase, continuous.artifact_type, 'ContinuousJointTrajectory');
    verifyFalse(testCase, continuous.time_allocation_optimized);
    verifyEqual(testCase, numel(continuous.segments), 1);
    verifyTrue(testCase, continuous.summary.all_limits_satisfied);
    for segmentIndex = 1:numel(continuous.segments)
        segment = continuous.segments(segmentIndex);
        inputSegment = timed.segments(segmentIndex);
        verifyEqual(testCase, segment.segment_index, inputSegment.segment_index);
        verifyEqual(testCase, segment.source_indices, inputSegment.source_indices);
        verifyEqual(testCase, segment.waypoint_q_rad, inputSegment.q_rad, ...
            'AbsTol', 1e-10);
        verifyTrue(testCase, all(diff(segment.t_s) > 0));
        verifyTrue(testCase, all(isfinite(segment.q_rad), 'all'));
        verifyTrue(testCase, all(isfinite(segment.qd_rad_s), 'all'));
        verifyTrue(testCase, all(isfinite(segment.qdd_rad_s2), 'all'));
        verifyTrue(testCase, all(isfinite(segment.qddd_rad_s3), 'all'));
        verifyLessThanOrEqual(testCase, ...
            segment.max_observed_abs_velocity_rad_s, ...
            config.max_velocity_rad_s + 1e-10);
        verifyLessThanOrEqual(testCase, ...
            segment.max_observed_abs_acceleration_rad_s2, ...
            config.max_acceleration_rad_s2 + 1e-10);
        for waypointIndex = 1:numel(segment.waypoint_t_s)
            sampleIndex = find(abs(segment.t_s - segment.waypoint_t_s(waypointIndex)) < 1e-12, ...
                1, 'first');
            verifyNotEmpty(testCase, sampleIndex);
            verifyEqual(testCase, segment.q_rad(sampleIndex, :), ...
                segment.waypoint_q_rad(waypointIndex, :), 'AbsTol', 1e-8);
        end
    end
    first = continuous.segments(1);
    verifyTrue(testCase, all(isnan( ...
        first.velocity_boundary_condition_rad_s(2, :))));
    verifyTrue(testCase, all(isnan( ...
        first.acceleration_boundary_condition_rad_s2(2, :))));
    verifyGreaterThan(testCase, norm(first.waypoint_qd_rad_s(2, :)), 1e-8);
    verifyEqual(testCase, ...
        continuous.segments(1).waypoint_provenance{2}.source_index, 102);
end


function testQuinticV1WaypointsLimitsAndProvenance(testCase)

    context = load_robot_context("legacy5");
    config = default_timed_joint_trajectory_config(context);
    config.max_velocity_rad_s = ones(1, 5);
    config.max_acceleration_rad_s2 = 0.05 * ones(1, 5);
    timed = time_parameterize_ik_success_segments( ...
        synthetic_timed_ik_result_set(), config, context);
    timedBefore = timed;
    continuous = generate_quintic_continuous_joint_trajectory(timed, config, context);

    verifyEqual(testCase, timed, timedBefore);
    verifyEqual(testCase, continuous.artifact_type, 'ContinuousJointTrajectory');
    verifyEqual(testCase, continuous.generation_method, 'quintic_hermite_v1');
    verifyEqual(testCase, continuous.robot_id, context.id);
    verifyEqual(testCase, continuous.robot_backend, context.backend);
    verifyFalse(testCase, continuous.time_allocation_optimized);
    verifyEqual(testCase, numel(continuous.segments), numel(timed.segments));
    verifyTrue(testCase, continuous.summary.all_safety_checks_satisfied);
    verifyTrue(testCase, any([continuous.segments.was_time_stretched]));
    for segmentIndex = 1:numel(continuous.segments)
        segment = continuous.segments(segmentIndex);
        inputSegment = timed.segments(segmentIndex);
        verifyEqual(testCase, segment.segment_index, inputSegment.segment_index);
        verifyEqual(testCase, segment.ik_success_segment_index, ...
            inputSegment.ik_success_segment_index);
        verifyEqual(testCase, segment.source_indices, inputSegment.source_indices);
        verifyEqual(testCase, segment.waypoint_q_rad, inputSegment.q_rad, ...
            'AbsTol', 1e-12);
        verifyTrue(testCase, all(isfinite(segment.q_rad), 'all'));
        verifyTrue(testCase, all(isfinite(segment.qd_rad_s), 'all'));
        verifyTrue(testCase, all(isfinite(segment.qdd_rad_s2), 'all'));
        verifyTrue(testCase, all(isfinite(segment.qddd_rad_s3), 'all'));
        verifyTrue(testCase, all(diff(segment.t_s) > 0));
        verifyEqual(testCase, segment.velocity_boundary_condition_rad_s(1, :), ...
            zeros(1, 5), 'AbsTol', 1e-12);
        verifyEqual(testCase, segment.velocity_boundary_condition_rad_s(end, :), ...
            zeros(1, 5), 'AbsTol', 1e-12);
        verifyEqual(testCase, segment.acceleration_boundary_condition_rad_s2(1, :), ...
            zeros(1, 5), 'AbsTol', 1e-12);
        verifyEqual(testCase, segment.acceleration_boundary_condition_rad_s2(end, :), ...
            zeros(1, 5), 'AbsTol', 1e-12);
        for waypointIndex = 1:numel(segment.waypoint_t_s)
            sampleIndex = find(abs(segment.t_s - ...
                segment.waypoint_t_s(waypointIndex)) < 1e-12, 1, 'first');
            verifyNotEmpty(testCase, sampleIndex);
            verifyEqual(testCase, segment.q_rad(sampleIndex, :), ...
                segment.waypoint_q_rad(waypointIndex, :), 'AbsTol', 1e-9);
        end
        if size(segment.waypoint_q_rad, 1) >= 3
            times = segment.waypoint_t_s;
            q = segment.waypoint_q_rad;
            expectedVelocity = (q(3, :) - q(1, :)) / (times(3) - times(1));
            expectedAcceleration = 2.0 * ((q(3, :) - q(2, :)) / ...
                (times(3) - times(2)) - (q(2, :) - q(1, :)) / ...
                (times(2) - times(1))) / (times(3) - times(1));
            verifyEqual(testCase, segment.velocity_boundary_condition_rad_s(2, :), ...
                expectedVelocity, 'AbsTol', 1e-10);
            verifyEqual(testCase, segment.acceleration_boundary_condition_rad_s2(2, :), ...
                expectedAcceleration, 'AbsTol', 1e-10);
        end
        verifyLessThanOrEqual(testCase, segment.max_observed_abs_velocity_rad_s, ...
            config.max_velocity_rad_s + 1e-10);
        verifyLessThanOrEqual(testCase, segment.max_observed_abs_acceleration_rad_s2, ...
            config.max_acceleration_rad_s2 + 1e-10);
        verifyTrue(testCase, segment.velocity_limits_satisfied);
        verifyTrue(testCase, segment.acceleration_limits_satisfied);
        verifyTrue(testCase, segment.joint_limits_satisfied);
        verifyTrue(testCase, segment.all_safety_checks_satisfied);
        verifyTrue(testCase, all(segment.within_joint_limits));
        verifyGreaterThanOrEqual(testCase, segment.minimum_joint_limit_margin, 0.0);
        verifyTrue(testCase, isstruct(segment.overshoot_evidence));
        verifyEqual(testCase, segment.waypoint_provenance{1}.source_index, ...
            inputSegment.waypoints(1).provenance.source_index);
    end
    verifyEqual(testCase, continuous.segments(2).waypoint_t_s(1), 0.0, ...
        'AbsTol', 1e-12);
end


function testQuinticAllSegmentsSummaryIsOrderInvariant(testCase)

    context = load_robot_context("legacy5");
    config = default_timed_joint_trajectory_config(context);
    timed = time_parameterize_ik_success_segments( ...
        synthetic_timed_ik_result_set(), config, context);
    timedBefore = timed;
    continuous = generate_quintic_continuous_joint_trajectory(timed, config, context);
    writing = synthetic_writing_results_for_continuous( ...
        testCase.TestData.robot, continuous);
    candidate = default_writing_candidate_config();
    taskPlane = build_writing_candidate_task_plane_config( ...
        testCase.TestData.taskPlaneConfig, candidate);
    validation = validate_continuous_writing_task_geometry( ...
        testCase.TestData.robot, continuous, writing, taskPlane, candidate, ...
        testCase.TestData.writingPostureConfig, context);
    summary = summarize_quintic_continuous_trajectory(continuous, validation);

    verifyEqual(testCase, timed, timedBefore);
    verifyFalse(testCase, summary.execution_timeline_exists);
    verifyEqual(testCase, summary.ik_success_segment_count, ...
        numel(timed.segments));
    verifyEqual(testCase, summary.total_accepted_waypoint_count, ...
        sum(arrayfun(@(segment) size(segment.q_rad, 1), timed.segments)));
    verifyTrue(testCase, summary.all_velocity_limits_satisfied);
    verifyTrue(testCase, summary.all_acceleration_limits_satisfied);
    verifyTrue(testCase, summary.all_joint_limits_satisfied);
    for index = 1:numel(summary.segment_records)
        record = summary.segment_records(index);
        segment = continuous.segments(index);
        verifyEqual(testCase, record.segment_index, segment.segment_index);
        verifyEqual(testCase, record.waypoint_count, size(segment.waypoint_q_rad, 1));
        verifyEqual(testCase, record.continuous_sample_count, numel(segment.t_s));
        verifyEqual(testCase, record.peak_velocity_rad_s, ...
            segment.max_observed_abs_velocity_rad_s, 'AbsTol', 1e-12);
        verifyEqual(testCase, record.peak_acceleration_rad_s2, ...
            segment.max_observed_abs_acceleration_rad_s2, 'AbsTol', 1e-12);
    end
    reversedContinuous = continuous;
    reversedContinuous.segments = fliplr(continuous.segments);
    reversedValidation = validation;
    reversedValidation.segments = fliplr(validation.segments);
    reversedSummary = summarize_quintic_continuous_trajectory( ...
        reversedContinuous, reversedValidation);
    for index = 1:numel(summary.segment_records)
        source = summary.segment_records(index);
        match = find([reversedSummary.segment_records.segment_index] == ...
            source.segment_index, 1, 'first');
        verifyNotEmpty(testCase, match);
        reordered = reversedSummary.segment_records(match);
        verifyEqual(testCase, reordered.final_duration_s, source.final_duration_s, ...
            'AbsTol', 1e-12);
        verifyEqual(testCase, reordered.cartesian_max_deviation_m, ...
            source.cartesian_max_deviation_m, 'AbsTol', 1e-12);
        verifyEqual(testCase, reordered.minimum_joint_limit_margin_rad, ...
            source.minimum_joint_limit_margin_rad, 'AbsTol', 1e-12);
    end
end


function testRealWritingSegmentsGenerateQuinticV1(testCase)

    run = run_real_resampled_task_path_ik_ab();
    config = default_timed_joint_trajectory_config();
    timed = time_parameterize_ik_success_segments( ...
        run.resampled_writing_result_set, config);
    timedBefore = timed;
    continuous = generate_quintic_continuous_joint_trajectory(timed, config);

    verifyEqual(testCase, timed, timedBefore);
    verifyEqual(testCase, continuous.generation_method, 'quintic_hermite_v1');
    verifyEqual(testCase, numel(continuous.segments), numel(timed.segments));
    verifyTrue(testCase, continuous.summary.all_safety_checks_satisfied);
    for index = 1:numel(continuous.segments)
        segment = continuous.segments(index);
        inputSegment = timed.segments(index);
        verifyEqual(testCase, segment.source_indices, inputSegment.source_indices);
        verifyEqual(testCase, segment.waypoint_q_rad, inputSegment.q_rad, ...
            'AbsTol', 1e-12);
        verifyTrue(testCase, all(diff(segment.t_s) > 0));
        verifyTrue(testCase, segment.velocity_limits_satisfied);
        verifyTrue(testCase, segment.acceleration_limits_satisfied);
        verifyTrue(testCase, segment.joint_limits_satisfied);
        verifyEqual(testCase, segment.waypoint_provenance{1}.source_index, ...
            inputSegment.waypoints(1).provenance.source_index);
        for waypointIndex = 1:numel(segment.waypoint_t_s)
            sampleIndex = find(abs(segment.t_s - ...
                segment.waypoint_t_s(waypointIndex)) < 1e-12, 1, 'first');
            verifyNotEmpty(testCase, sampleIndex);
            verifyEqual(testCase, segment.q_rad(sampleIndex, :), ...
                segment.waypoint_q_rad(waypointIndex, :), 'AbsTol', 1e-9);
        end
    end
end


function testMinimumJerkOvershootGuardAndPolynomialDiagnosticContracts(testCase)

    detector = detect_joint_interval_overshoot( ...
        [0; 0.5; 1.0], [0, 0, 0, 0, 0; 1.2, 0, 0, 0, 0; 1, 0, 0, 0, 0], ...
        [0; 1], [0, 0, 0, 0, 0; 1, 0, 0, 0, 0], 1e-8);
    verifyTrue(testCase, detector.has_overshoot);
    verifyEqual(testCase, detector.records(1).interval_index, 1);
    verifyEqual(testCase, detector.records(1).joint_index, 1);
    verifyEqual(testCase, detector.max_overshoot_magnitude_rad, 0.2, 'AbsTol', 1e-12);

    config = default_timed_joint_trajectory_config();
    timed = time_parameterize_ik_success_segments( ...
        synthetic_timed_ik_result_set(), config);
    timedBefore = timed;
    patched = generate_minimum_jerk_continuous_joint_trajectory(timed, config);
    verifyEqual(testCase, timed, timedBefore);
    for index = 1:numel(patched.segments)
        segment = patched.segments(index);
        verifyEqual(testCase, segment.waypoint_q_rad, timed.segments(index).q_rad, ...
            'AbsTol', 1e-12);
        verifyLessThanOrEqual(testCase, ...
            segment.overshoot_after_patch.max_overshoot_magnitude_rad, ...
            segment.overshoot_before_patch.max_overshoot_magnitude_rad + 1e-12);
        affectedJoints = unique([segment.overshoot_before_patch.records.joint_index]);
        for joint = 1:5
            if ~ismember(joint, affectedJoints)
                verifyFalse(testCase, any(segment.velocity_boundary_modified_mask(:, joint)));
                verifyFalse(testCase, any(segment.acceleration_boundary_modified_mask(:, joint)));
            end
        end
        verifyLessThanOrEqual(testCase, ...
            segment.max_observed_abs_velocity_rad_s, config.max_velocity_rad_s + 1e-10);
        verifyLessThanOrEqual(testCase, ...
            segment.max_observed_abs_acceleration_rad_s2, ...
            config.max_acceleration_rad_s2 + 1e-10);
    end

    writing = synthetic_writing_results_for_continuous( ...
        testCase.TestData.robot, patched);
    candidate = default_writing_candidate_config();
    taskPlane = build_writing_candidate_task_plane_config( ...
        testCase.TestData.taskPlaneConfig, candidate);
    patchedBefore = patched;
    diagnostic = diagnose_minimum_jerk_overshoot_methods( ...
        testCase.TestData.robot, patched, writing, taskPlane, candidate, ...
        testCase.TestData.writingPostureConfig);
    verifyEqual(testCase, patched, patchedBefore);
    verifyEqual(testCase, {diagnostic.comparison_records.method}, { ...
        'patched_minimum_jerk', 'plain_cubic_spline', 'plain_quintic_hermite'});
    referenceTimes = patched.segments(1).waypoint_t_s;
    for method = {diagnostic.patched_minimum_jerk.trajectory, ...
            diagnostic.cubic.trajectory, diagnostic.quintic.trajectory}
        trajectory = method{1};
        verifyEqual(testCase, trajectory.segments(1).waypoint_t_s, referenceTimes, ...
            'AbsTol', 1e-12);
        verifyEqual(testCase, trajectory.segments(1).waypoint_q_rad, ...
            patched.segments(1).waypoint_q_rad, 'AbsTol', 1e-12);
        verifyTrue(testCase, all(isfinite(trajectory.segments(1).q_rad), 'all'));
        verifyTrue(testCase, all(isfinite(trajectory.segments(1).qd_rad_s), 'all'));
        verifyTrue(testCase, all(isfinite(trajectory.segments(1).qdd_rad_s2), 'all'));
    end
end


function testContinuousWritingGeometryFKReferenceAndJointLimits(testCase)

    [continuous, writing, taskPlane, candidate] = ...
        synthetic_continuous_writing_geometry_input(testCase.TestData.robot, ...
        testCase.TestData.taskPlaneConfig);
    original = continuous;
    validation = validate_continuous_writing_task_geometry( ...
        testCase.TestData.robot, continuous, writing, taskPlane, candidate, ...
        testCase.TestData.writingPostureConfig);

    verifyEqual(testCase, continuous, original);
    verifyEqual(testCase, validation.artifact_type, ...
        'ContinuousJointTrajectoryTaskGeometryValidation');
    verifyEqual(testCase, numel(validation.segments), 2);
    verifyFalse(testCase, validation.summary.has_continuous_joint_limit_violation);
    for segmentIndex = 1:numel(validation.segments)
        segment = validation.segments(segmentIndex);
        verifyTrue(testCase, all(isfinite(segment.fk_xyz_m), 'all'));
        verifyTrue(testCase, all(isfinite(segment.fk_tool_z_direction), 'all'));
        verifyTrue(testCase, all(isfinite(segment.position_deviation_m)));
        verifyTrue(testCase, all(segment.within_joint_limits));
        verifyGreaterThan(testCase, segment.minimum_joint_limit_margin, 0.0);
        for waypointIndex = 1:numel(segment.waypoint_t_s)
            sampleIndex = find(abs(segment.t_s - segment.waypoint_t_s(waypointIndex)) < 1e-12, ...
                1, 'first');
            verifyNotEmpty(testCase, sampleIndex);
            verifyEqual(testCase, segment.reference_xyz_m(sampleIndex, :), ...
                segment.waypoint_target_xyz_m(waypointIndex, :), 'AbsTol', 1e-12);
            verifyEqual(testCase, segment.fk_xyz_m(sampleIndex, :), ...
                segment.waypoint_target_xyz_m(waypointIndex, :), 'AbsTol', 1e-12);
        end
    end
    verifyEqual(testCase, validation.segments(2).t_s(1), 0.0, 'AbsTol', 1e-12);
    verifyEqual(testCase, validation.segments(1).waypoint_provenance{2}.source_index, 102);

    outOfLimit = continuous;
    upper = testCase.TestData.robot.Bodies{1}.Joint.PositionLimits(2);
    outOfLimit.segments(1).q_rad(2, 1) = upper + 1e-3;
    outOfLimitValidation = validate_continuous_writing_task_geometry( ...
        testCase.TestData.robot, outOfLimit, writing, taskPlane, candidate, ...
        testCase.TestData.writingPostureConfig);
    verifyTrue(testCase, ...
        outOfLimitValidation.summary.has_continuous_joint_limit_violation);
    verifyFalse(testCase, outOfLimitValidation.segments(1).within_joint_limits(2));
end


function testGeneralizationFixturesShareFrozenWorkspaceContract(testCase)

    fixtures = make_writing_generalization_fixtures();
    config = default_writing_generalization_benchmark_config();
    verifyEqual(testCase, sort({fixtures.name}), sort({ ...
        'straight_line', 'rectangle_polyline', 'arc_circle_like', 's_curve', ...
        'zig_zag', 'recorded_triangle'}));
    for index = 1:numel(fixtures)
        metadata = fixtures(index).workspace_trajectory.metadata;
        verifyEqual(testCase, metadata.width_mm, config.workspace_width_mm);
        verifyEqual(testCase, metadata.height_mm, config.workspace_height_mm);
        validate_workspace_trajectory(fixtures(index).workspace_trajectory);
    end
    verifyEqual(testCase, config.resampling_config.target_spacing_m, 0.002);
    verifyFalse(testCase, config.writing_posture_config.allow_random_restart);
    verifyFalse(testCase, config.use_backward_rescue);
end


function testGeneralizationBenchmarkMetricsAreFrozenAndOrderIndependent(testCase)

    fixtures = make_writing_generalization_fixtures();
    base = fixtures(strcmp({fixtures.name}, 'straight_line'));
    first = base;
    first.name = 'mini_line_a';
    first.workspace_trajectory.samples = first.workspace_trajectory.samples(1:2);
    second = base;
    second.name = 'mini_line_b';
    second.workspace_trajectory.samples = second.workspace_trajectory.samples(4:5);
    config = default_writing_generalization_benchmark_config();
    configBefore = config;

    forwardOrder = run_writing_generalization_benchmark([first, second], config);
    reverseOrder = run_writing_generalization_benchmark([second, first], config);
    required = { ...
        'trajectory_name', 'path_length_m', 'resampled_point_count', ...
        'position_only_success_rate', 'writing_success_rate', ...
        'accepted_sampled_coverage_fraction', 'ik_success_segment_count', ...
        'max_joint_step_rad', 'minimum_joint_limit_margin', ...
        'mean_position_error_m', 'max_position_error_m', ...
        'mean_direction_error_deg', 'max_direction_error_deg', ...
        'failure_arc_length_locations', 'frozen_config'};

    verifyEqual(testCase, config, configBefore);
    verifyEqual(testCase, {forwardOrder.records.trajectory_name}, ...
        {'mini_line_a', 'mini_line_b'});
    verifyEqual(testCase, forwardOrder.records, reverseOrder.records, ...
        'AbsTol', 1e-12);
    for index = 1:numel(forwardOrder.records)
        record = forwardOrder.records(index);
        verifyTrue(testCase, all(isfield(record, required)));
        verifyEqual(testCase, record.frozen_config, config);
        verifyGreaterThanOrEqual(testCase, record.position_only_success_rate, 0.0);
        verifyLessThanOrEqual(testCase, record.position_only_success_rate, 1.0);
    end
end


function segmentSet = synthetic_writing_failure_segment_set(centerM)

    samples = [ ...
        synthetic_writing_sample(0.0, centerM), ...
        synthetic_writing_sample(100.0, centerM), ...
        synthetic_writing_sample(200.0, [10.0, 10.0, 10.0]), ...
        synthetic_writing_sample(300.0, centerM)];
    segment = struct('source_indices', [501, 502, 503, 504], 'samples', samples);
    segmentSet = struct( ...
        'coordinate_frame', 'robot_base', ...
        'units', 'm', ...
        'segments', segment);
end


function segmentSet = synthetic_two_center_segment_set(centerM)

    samples = [ ...
        synthetic_writing_sample(0.0, centerM), ...
        synthetic_writing_sample(100.0, centerM)];
    segment = struct('source_indices', [601, 602], 'samples', samples);
    segmentSet = struct('coordinate_frame', 'robot_base', 'units', 'm', ...
        'segments', segment);
end


function sample = synthetic_writing_sample(tMs, xyzM)

    sample = struct( ...
        't_ms', tMs, ...
        'valid', true, ...
        'inside_workspace', true, ...
        'x_m', xyzM(1), ...
        'y_m', xyzM(2), ...
        'z_m', xyzM(3));
end


function taskTrajectory = synthetic_task_trajectory(xyzM, validMask, insideMask)

    sampleCount = size(xyzM, 1);
    samples = repmat(task_sample(0.0, true, true, [0, 0, 0]), 1, sampleCount);
    for index = 1:sampleCount
        samples(index) = task_sample( ...
            100.0 * (index - 1), validMask(index), insideMask(index), xyzM(index, :));
    end
    taskTrajectory = struct( ...
        'coordinate_frame', 'robot_base', ...
        'metadata', struct('units', 'm'), ...
        'samples', samples);
end


function sample = adapter_test_sample(sourceIndex, arcM, bracket)

    sample = struct('t_ms', 100.0 * sourceIndex, 'valid', true, ...
        'inside_workspace', true, 'invalid_reason', '', ...
        'x_m', arcM, 'y_m', 0.0, 'z_m', 0.0, ...
        'resampled_index', sourceIndex, 'source_bracket_indices', bracket, ...
        'interpolation_ratio', 0.5, 'original_run_index', 1, ...
        'source_arclength_m', arcM);
end


function summary = synthetic_writing_summary(successCount, failureCount, segmentCount, rate)

    summary = struct( ...
        'success_point_count', successCount, ...
        'failure_count', failureCount, ...
        'ik_success_segment_count', segmentCount, ...
        'ik_success_rate', rate, ...
        'overall_max_joint_step', 0.1, ...
        'minimum_joint_limit_margin', 0.2, ...
        'mean_fk_position_error_m', 1e-5, ...
        'max_fk_position_error_m', 2e-5, ...
        'mean_tool_direction_error_deg', 1.0, ...
        'max_tool_direction_error_deg', 2.0);
end


function resultSet = synthetic_timed_ik_result_set()

    first = [ ...
        synthetic_timed_ik_point(101, 0.0, zeros(1, 5)), ...
        synthetic_timed_ik_point(102, 100.0, [0.20, 0, 0, 0, 0]), ...
        synthetic_timed_ik_point(103, 200.0, [0.20, 0, 0, 0, 0])];
    second = [ ...
        synthetic_timed_ik_point(201, 400.0, [1.00, 0, 0, 0, 0]), ...
        synthetic_timed_ik_point(202, 500.0, [1.10, 0, 0, 0, 0])];
    segmentOne = struct('preik_segment_index', 1, ...
        'source_indices', [first.source_index], 'results', first);
    segmentTwo = struct('preik_segment_index', 1, ...
        'source_indices', [second.source_index], 'results', second);
    resultSet = struct('coordinate_space', 'joint', 'units', 'rad', ...
        'segments', [segmentOne, segmentTwo], 'failures', struct([]));
end


function resultSet = synthetic_monotonic_timed_ik_result_set()

    points = [ ...
        synthetic_timed_ik_point(101, 0.0, zeros(1, 5)), ...
        synthetic_timed_ik_point(102, 100.0, [0.20, 0, 0, 0, 0]), ...
        synthetic_timed_ik_point(103, 200.0, [0.40, 0, 0, 0, 0])];
    segment = struct('preik_segment_index', 1, ...
        'source_indices', [points.source_index], 'results', points);
    resultSet = struct('coordinate_space', 'joint', 'units', 'rad', ...
        'segments', segment, 'failures', struct([]));
end


function point = synthetic_timed_ik_point(sourceIndex, tMs, q)

    point = struct('source_index', sourceIndex, 't_ms', tMs, 'q', q);
end


function writing = synthetic_writing_results_for_continuous(robot, continuous)

    writingSegments = repmat(struct('results', struct([])), 1, ...
        numel(continuous.segments));
    for segmentIndex = 1:numel(continuous.segments)
        segment = continuous.segments(segmentIndex);
        results = repmat(struct('source_index', NaN, 'target_xyz_m', NaN(1,3)), ...
            1, size(segment.waypoint_q_rad, 1));
        for pointIndex = 1:numel(results)
            pose = getTransform(robot, segment.waypoint_q_rad(pointIndex, :), 'body5');
            results(pointIndex).source_index = segment.source_indices(pointIndex);
            results(pointIndex).target_xyz_m = pose(1:3, 4)';
        end
        writingSegments(segmentIndex).results = results;
    end
    writing = struct('segments', writingSegments);
end


function [continuous, writing, taskPlane, candidate] = ...
        synthetic_continuous_writing_geometry_input(robot, baselineTaskPlane)

    q0 = homeConfiguration(robot);
    q1 = q0;
    q1(1) = q1(1) + 0.1;
    qMid = (q0 + q1) / 2;
    pose0 = getTransform(robot, q0, 'body5');
    pose1 = getTransform(robot, q1, 'body5');
    xyz0 = pose0(1:3, 4)';
    xyz1 = pose1(1:3, 4)';
    provenanceOne = {struct('source_index', 101); struct('source_index', 102)};
    provenanceTwo = {struct('source_index', 201); struct('source_index', 202)};
    segmentOne = synthetic_continuous_geometry_segment( ...
        1, [101, 102], [q0; qMid; q1], [0; 0.05; 0.1], ...
        [0; 0.1], provenanceOne);
    segmentTwo = synthetic_continuous_geometry_segment( ...
        2, [201, 202], [q1; qMid; q0], [0; 0.05; 0.1], ...
        [0; 0.1], provenanceTwo);
    continuous = struct('artifact_type', 'ContinuousJointTrajectory', ...
        'segments', [segmentOne, segmentTwo]);
    writingOne = struct('results', [ ...
        synthetic_writing_target_result(101, xyz0), ...
        synthetic_writing_target_result(102, xyz1)]);
    writingTwo = struct('results', [ ...
        synthetic_writing_target_result(201, xyz1), ...
        synthetic_writing_target_result(202, xyz0)]);
    writing = struct('segments', [writingOne, writingTwo]);
    candidate = default_writing_candidate_config();
    taskPlane = build_writing_candidate_task_plane_config( ...
        baselineTaskPlane, candidate);
end


function segment = synthetic_continuous_geometry_segment(segmentIndex, sourceIndices, ...
        q, sampleTimes, waypointTimes, provenance)

    segment = struct('segment_index', segmentIndex, ...
        'ik_success_segment_index', segmentIndex, ...
        'preik_segment_index', 1, 'source_indices', sourceIndices, ...
        'waypoint_t_s', waypointTimes, 'waypoint_provenance', {provenance}, ...
        't_s', sampleTimes, 'q_rad', q);
end


function result = synthetic_writing_target_result(sourceIndex, targetXYZ)

    result = struct('source_index', sourceIndex, 'target_xyz_m', targetXYZ);
end


function sample = task_sample(tMs, valid, inside, xyzM)

    sample = struct('t_ms', tMs, 'valid', logical(valid), ...
        'inside_workspace', logical(inside), 'invalid_reason', '', ...
        'x_m', xyzM(1), 'y_m', xyzM(2), 'z_m', xyzM(3));
    if ~valid
        sample.x_m = [];
        sample.y_m = [];
        sample.z_m = [];
        sample.invalid_reason = 'synthetic_invalid';
    end
end
