function report = test_stage3_4_replay_execution(tracePath)
%TEST_STAGE3_4_REPLAY_EXECUTION MATLAB acceptance for the Task 3--7 chain.
%
% Run this after Python writes the real-triangle trace.  It validates the
% externally meaningful replay conditions, not Stage 3.3's frozen batch E2E.

    if nargin < 1 || isempty(tracePath)
        root = fileparts(fileparts(mfilename('fullpath')));
        tracePath = fullfile(root, 'outputs', 'stage3_4', 'real_triangle_replay_trace.json');
    end
    report = verify_replay_trace_execution(tracePath);
    run = report.run;
    assert(report.drained_after_final_endpoint, 'q(t) FIFO did not drain.');
    assert(run.summary.robot_started_before_source_finished, ...
        'Robot must begin executing while ReplaySource is still publishing.');
    assert(run.summary.source_event_count >= 4, 'Trace is too short to prove lookahead.');
    assert(run.summary.planned_segment_count == run.summary.source_event_count - 1, ...
        'One contiguous real replay should retain every adjacent Cartesian segment.');
    assert(all(isfinite(run.execution.q_rad), 'all'), 'q(t) must remain finite.');
    assert(all(isfinite(run.execution.qd_rad_s), 'all'), 'qd(t) must remain finite.');
    assert(all(isfinite(run.execution.qdd_rad_s2), 'all'), 'qdd(t) must remain finite.');
    assert(size(run.execution.q_rad, 2) == run.robot_context.dof, ...
        'Every controllable joint needs one q(t) column.');
    assert(numel(run.chunk_start_events) == run.summary.planned_segment_count, ...
        'Every Cartesian segment must become exactly one started q(t) chunk.');
    if run.startup.enabled
        assert(norm(run.execution.q_rad(1,:) - run.robot_context.home_q) <= 1e-12, ...
            'Home-to-Start must begin at home without a joint-position step.');
        assert(run.startup.approach_chunk.execution_duration_s > 0, ...
            'Startup-enabled trace requires one positive-duration Home-to-Start chunk.');
        assert(any(run.execution.phase == "HOME_TO_START"), ...
            'Execution evidence must expose the Home-to-Start phase.');
    end
    visualization = verify_replay_robot_visualization(tracePath);
    assert(visualization.axes_contain_all_trace_origins, ...
        'Visualization axis limits must include the full Legacy5 chain.');
    assert(run.summary.max_ready_handoff_gap_s <= 1e-9, ...
        'A ready q(t) successor must start at the exact previous endpoint.');
    assert(isfinite(run.summary.max_execution_backlog_s) && ...
        run.summary.max_execution_backlog_s >= 0, ...
        'Backlog must be reported as a nonnegative duration in seconds.');
    fprintf(['test_stage3_4_replay_execution PASS | events=%d segments=%d ' ...
        'maxBacklog=%.3f s readyHandoffGap=%.3g s maxFK=%.3g m\n'], ...
        run.summary.source_event_count, run.summary.planned_segment_count, ...
        run.summary.max_execution_backlog_s, run.summary.max_ready_handoff_gap_s, ...
        run.summary.max_fk_to_cartesian_reference_m);
end
