function tests = test_stage3_2
%TEST_STAGE3_2 Position-Only continuous IK result-contract tests for Stage 3.2.
%
% Run from the repository root:
%   results = runtests('tests/test_stage3_2.m');

    tests = functiontests(localfunctions);
end


function setupOnce(testCase)

    testFile = mfilename('fullpath');
    testsDir = fileparts(testFile);
    repoRoot = fileparts(testsDir);
    stage3Dir = fullfile(repoRoot, 'stage3');
    stage1Dir = fullfile(repoRoot, 'stage1');

    stage3Path = genpath(stage3Dir);
    addpath(stage3Path);
    addpath(stage1Dir);

    testCase.TestData.stage3Dir = stage3Dir;
    testCase.TestData.stage3Path = stage3Path;
    testCase.TestData.stage1Dir = stage1Dir;
    testCase.TestData.robot = build_legacy_robot();
    testCase.TestData.taskPlaneConfig = default_task_plane_config();
    testCase.TestData.ikConfig = default_ik_config();
end


function teardownOnce(testCase)

    rmpath(testCase.TestData.stage1Dir);
    rmpath(testCase.TestData.stage3Path);
end


function testDefaultConfigIsDeterministicPositionOnly(testCase)

    ikConfig = testCase.TestData.ikConfig;

    verifyEqual(testCase, ikConfig.weights, [0, 0, 0, 1, 1, 1]);
    verifyFalse(testCase, ikConfig.allow_random_restart);
end


function testAnchorIkReturnsCanonicalSuccessfulResult(testCase)

    robot = testCase.TestData.robot;
    ikConfig = testCase.TestData.ikConfig;
    result = solve_anchor_ik( ...
        robot, ...
        testCase.TestData.taskPlaneConfig, ...
        ikConfig);

    requiredFields = { ...
        'target_xyz_m', ...
        'seed_q', ...
        'q', ...
        'solver_status', ...
        'pose_error_norm', ...
        'fk_xyz_m', ...
        'position_error_m', ...
        'within_joint_limits', ...
        'joint_limit_margin', ...
        'source_index', ...
        't_ms', ...
        'delta_q'};
    verifyTrue(testCase, all(isfield(result, requiredFields)));

    qAnchor = result.q;
    verifySize(testCase, result.seed_q, [1, 5]);
    verifySize(testCase, qAnchor, [1, 5]);
    verifyTrue(testCase, all(isfinite(qAnchor)));
    verifyNotEmpty(testCase, result.solver_status);
    verifyTrue(testCase, isfinite(result.pose_error_norm));
    verifyTrue(testCase, all(isfinite(result.fk_xyz_m)));
    verifyLessThanOrEqual( ...
        testCase, ...
        result.position_error_m, ...
        ikConfig.position_error_tolerance_m);
    verifyTrue(testCase, result.within_joint_limits);
    verifyTrue(testCase, all(isfinite(result.joint_limit_margin)));
    verifyGreaterThanOrEqual(testCase, min(result.joint_limit_margin), 0.0);

    % The anchor is a stand-alone point, so trajectory provenance and
    % neighbour-to-neighbour delta evidence must not be invented yet.
    verifyEmpty(testCase, result.source_index);
    verifyEmpty(testCase, result.t_ms);
    verifyEmpty(testCase, result.delta_q);

    % Test recovered Cartesian position through FK, rather than trusting the
    % solver status or its internal pose norm as the external geometry check.
    fkPose = getTransform(robot, qAnchor, ikConfig.end_effector);
    verifyLessThanOrEqual( ...
        testCase, ...
        norm(fkPose(1:3, 4)' - result.target_xyz_m), ...
        ikConfig.position_error_tolerance_m);
end


function testKnownReachableTargetRecoversPositionNotJointVector(testCase)

    robot = testCase.TestData.robot;
    ikConfig = testCase.TestData.ikConfig;

    % This configuration is strictly inside all five Stage 1 joint ranges.
    qKnown = deg2rad([30, 60, -30, 120, 45]);
    knownPose = getTransform(robot, qKnown, ikConfig.end_effector);
    targetXYZM = knownPose(1:3, 4)';

    % Deliberately discard qKnown. Position-only IK can have multiple valid
    % joint solutions, so qRecovered == qKnown is neither required nor a
    % correct regression assertion. The required observable is recovered FK
    % XYZ at this known reachable target.
    seedQ = homeConfiguration(robot);
    homePose = getTransform(robot, seedQ, ikConfig.end_effector);
    targetPose = homePose;
    targetPose(1:3, 4) = targetXYZM';

    ik = inverseKinematics( ...
        'RigidBodyTree', robot, ...
        'SolverAlgorithm', ikConfig.solver_algorithm);
    solverParameters = ik.SolverParameters;
    solverParameters.AllowRandomRestart = ikConfig.allow_random_restart;
    ik.SolverParameters = solverParameters;

    [qRecovered, solutionInfo] = ik( ...
        ikConfig.end_effector, ...
        targetPose, ...
        ikConfig.weights, ...
        seedQ);
    qRecovered = reshape(qRecovered, 1, []);
    fkRecoveredPose = getTransform( ...
        robot, ...
        qRecovered, ...
        ikConfig.end_effector);
    fkXYZM = fkRecoveredPose(1:3, 4)';

    result = ik_result_contract( ...
        targetXYZM, ...
        seedQ, ...
        qRecovered, ...
        solutionInfo.Status, ...
        solutionInfo.PoseErrorNorm, ...
        fkXYZM, ...
        five_joint_limits(robot));

    verifySize(testCase, result.q, [1, 5]);
    verifyTrue(testCase, all(isfinite(result.q)));
    verifyTrue(testCase, isfinite(result.pose_error_norm));
    verifyLessThanOrEqual( ...
        testCase, ...
        result.position_error_m, ...
        ikConfig.position_error_tolerance_m);
    verifyTrue(testCase, result.within_joint_limits);
    verifyGreaterThanOrEqual(testCase, min(result.joint_limit_margin), 0.0);
end


function testContinuousIkSplitsFailuresAndResetsSeed(testCase)

    robot = testCase.TestData.robot;
    ikConfig = testCase.TestData.ikConfig;
    anchorResult = solve_anchor_ik( ...
        robot, ...
        testCase.TestData.taskPlaneConfig, ...
        ikConfig);
    segmentSet = synthetic_failure_segment_set(robot, ikConfig);
    segmentSetBefore = segmentSet;

    ikResultSet = solve_ik_segments( ...
        robot, ...
        segmentSet, ...
        anchorResult, ...
        ikConfig);

    verifyEqual(testCase, segmentSet, segmentSetBefore);
    verifyEqual(testCase, string(ikResultSet.coordinate_space), "joint");
    verifyEqual(testCase, string(ikResultSet.units), "rad");
    verifyEqual(testCase, ikResultSet.summary.preik_segment_count, 1);
    verifyEqual(testCase, ikResultSet.summary.ik_success_segment_count, 2);
    verifyEqual(testCase, ikResultSet.summary.success_point_count, 3);
    verifyEqual(testCase, ikResultSet.summary.failure_count, 1);

    firstSuccessSegment = ikResultSet.segments(1);
    secondSuccessSegment = ikResultSet.segments(2);
    failure = ikResultSet.failures(1);

    verifyEqual(testCase, firstSuccessSegment.source_indices, [11, 12]);
    verifyEqual(testCase, firstSuccessSegment.t_ms, [0.0, 100.0]);
    verifySize(testCase, firstSuccessSegment.q_rad, [2, 5]);
    verifyEqual( ...
        testCase, ...
        firstSuccessSegment.results(2).seed_q, ...
        firstSuccessSegment.results(1).q, ...
        'AbsTol', 1e-12);
    verifyEqual( ...
        testCase, ...
        firstSuccessSegment.results(2).delta_q, ...
        firstSuccessSegment.results(2).q - firstSuccessSegment.results(1).q, ...
        'AbsTol', 1e-12);
    verifyEmpty(testCase, firstSuccessSegment.results(1).delta_q);

    % The unreachable source 13 is evidence, not a successful q point. Its
    % failure barrier forces source 14 to restart with q_anchor.
    verifyEqual(testCase, failure.source_index, 13);
    verifyEqual(testCase, failure.t_ms, 200.0);
    verifyEqual(testCase, failure.reason, 'position_error_exceeds_tolerance');
    verifyEmpty(testCase, failure.q);
    verifyFalse(testCase, ismember(13, [ikResultSet.segments.source_indices]));

    verifyEqual(testCase, secondSuccessSegment.source_indices, 14);
    verifyEqual(testCase, secondSuccessSegment.t_ms, 300.0);
    verifySize(testCase, secondSuccessSegment.q_rad, [1, 5]);
    verifyEqual( ...
        testCase, ...
        secondSuccessSegment.results(1).seed_q, ...
        anchorResult.q, ...
        'AbsTol', 1e-12);
    verifyEmpty(testCase, secondSuccessSegment.results(1).delta_q);
end


function testIndependentPreIkSegmentRestartsFromAnchorSeed(testCase)

    robot = testCase.TestData.robot;
    ikConfig = testCase.TestData.ikConfig;
    anchorResult = solve_anchor_ik( ...
        robot, ...
        testCase.TestData.taskPlaneConfig, ...
        ikConfig);
    segmentSet = independent_reachable_segment_set(robot, ikConfig);

    ikResultSet = solve_ik_segments( ...
        robot, ...
        segmentSet, ...
        anchorResult.q, ...
        ikConfig);

    verifyEqual(testCase, ikResultSet.summary.failure_count, 0);
    verifyEqual(testCase, ikResultSet.summary.ik_success_segment_count, 2);
    verifyEqual( ...
        testCase, ...
        ikResultSet.segments(2).results(1).seed_q, ...
        anchorResult.q, ...
        'AbsTol', 1e-12);
    verifyEmpty(testCase, ikResultSet.segments(2).results(1).delta_q);
end


function testContinuitySummaryMatchesCanonicalDiagnostics(testCase)

    robot = testCase.TestData.robot;
    ikConfig = testCase.TestData.ikConfig;
    anchorResult = solve_anchor_ik( ...
        robot, ...
        testCase.TestData.taskPlaneConfig, ...
        ikConfig);
    ikResultSet = solve_ik_segments( ...
        robot, ...
        synthetic_failure_segment_set(robot, ikConfig), ...
        anchorResult, ...
        ikConfig);
    resultSetBefore = ikResultSet;

    continuity = summarize_ik_continuity(ikResultSet);
    firstSuccessSegment = ikResultSet.segments(1);
    secondSuccessSegment = ikResultSet.segments(2);
    pointResults = [ ...
        firstSuccessSegment.results, ...
        secondSuccessSegment.results];
    expectedErrors = [pointResults.position_error_m];
    expectedMargins = vertcat(pointResults.joint_limit_margin);
    expectedDelta = firstSuccessSegment.results(2).delta_q;
    [expectedMaxStep, expectedJointIndex] = max(abs(expectedDelta));
    [expectedMinimumMargin, marginFlatIndex] = min(expectedMargins, [], 'all');
    [marginPointIndex, expectedClosestJointIndex] = ind2sub( ...
        size(expectedMargins), ...
        marginFlatIndex);

    verifyEqual(testCase, ikResultSet, resultSetBefore);
    verifyEqual(testCase, continuity.success_point_count, 3);
    verifyEqual(testCase, continuity.failure_count, 1);
    verifyEqual(testCase, continuity.ik_success_rate, 0.75, 'AbsTol', 1e-12);
    verifyEqual( ...
        testCase, ...
        continuity.mean_fk_position_error_m, ...
        mean(expectedErrors), ...
        'AbsTol', 1e-12);
    verifyEqual( ...
        testCase, ...
        continuity.max_fk_position_error_m, ...
        max(expectedErrors), ...
        'AbsTol', 1e-12);
    verifyEqual( ...
        testCase, ...
        continuity.per_joint_max_abs_delta_q, ...
        abs(expectedDelta), ...
        'AbsTol', 1e-12);
    verifyEqual( ...
        testCase, ...
        continuity.mean_abs_delta_q, ...
        mean(abs(expectedDelta), 'all'), ...
        'AbsTol', 1e-12);
    verifyEqual( ...
        testCase, ...
        continuity.overall_max_joint_step, ...
        expectedMaxStep, ...
        'AbsTol', 1e-12);
    verifyEqual(testCase, continuity.largest_jump_source_index, 12);
    verifyEqual(testCase, continuity.largest_jump_joint_index, expectedJointIndex);
    verifyEqual( ...
        testCase, ...
        continuity.minimum_joint_limit_margin, ...
        expectedMinimumMargin, ...
        'AbsTol', 1e-12);
    verifyEqual( ...
        testCase, ...
        continuity.closest_limit_joint_index, ...
        expectedClosestJointIndex);
    verifyEqual( ...
        testCase, ...
        continuity.closest_limit_source_index, ...
        pointResults(marginPointIndex).source_index);
end


function testSeedStrategyComparisonReportsBothPolicies(testCase)

    robot = testCase.TestData.robot;
    ikConfig = testCase.TestData.ikConfig;
    anchorResult = solve_anchor_ik( ...
        robot, ...
        testCase.TestData.taskPlaneConfig, ...
        ikConfig);
    segmentSet = synthetic_failure_segment_set(robot, ikConfig);

    comparison = compare_ik_seed_strategies( ...
        robot, ...
        segmentSet, ...
        anchorResult, ...
        ikConfig);

    verifyEqual( ...
        testCase, ...
        comparison.previous_success_seed.success_point_count, ...
        3);
    verifyEqual( ...
        testCase, ...
        comparison.previous_success_seed.failure_count, ...
        1);
    verifyEqual( ...
        testCase, ...
        comparison.anchor_seed.success_point_count + ...
        comparison.anchor_seed.failure_count, ...
        4);
    verifyTrue(testCase, isfinite( ...
        comparison.previous_success_seed.max_abs_joint_step_rad));
    verifyTrue(testCase, isfinite( ...
        comparison.anchor_seed.max_abs_joint_step_rad));
end


function limits = five_joint_limits(robot)

    limits = zeros(5, 2);

    for i = 1:5
        limits(i, :) = robot.Bodies{i}.Joint.PositionLimits;
    end
end


function segmentSet = synthetic_failure_segment_set(robot, ikConfig)

    qOne = homeConfiguration(robot);
    qTwo = deg2rad([10, 100, -10, 100, 10]);
    qThree = deg2rad([-10, 80, 10, 110, -10]);
    targetOne = getTransform(robot, qOne, ikConfig.end_effector);
    targetTwo = getTransform(robot, qTwo, ikConfig.end_effector);
    targetThree = getTransform(robot, qThree, ikConfig.end_effector);

    samples = [ ...
        synthetic_sample(0.0, targetOne(1:3, 4)'), ...
        synthetic_sample(100.0, targetTwo(1:3, 4)'), ...
        synthetic_sample(200.0, [10.0, 10.0, 10.0]), ...
        synthetic_sample(300.0, targetThree(1:3, 4)')];

    segment = struct( ...
        'source_indices', [11, 12, 13, 14], ...
        'samples', samples);
    segmentSet = struct( ...
        'coordinate_frame', 'robot_base', ...
        'units', 'm', ...
        'segments', segment);
end


function segmentSet = independent_reachable_segment_set(robot, ikConfig)

    qOne = homeConfiguration(robot);
    qTwo = deg2rad([15, 95, -15, 105, 15]);
    targetOne = getTransform(robot, qOne, ikConfig.end_effector);
    targetTwo = getTransform(robot, qTwo, ikConfig.end_effector);

    firstSegment = struct( ...
        'source_indices', 21, ...
        'samples', synthetic_sample(0.0, targetOne(1:3, 4)'));
    secondSegment = struct( ...
        'source_indices', 22, ...
        'samples', synthetic_sample(100.0, targetTwo(1:3, 4)'));
    segmentSet = struct( ...
        'coordinate_frame', 'robot_base', ...
        'units', 'm', ...
        'segments', [firstSegment, secondSegment]);
end


function sample = synthetic_sample(tMs, xyzM)

    sample = struct( ...
        't_ms', tMs, ...
        'valid', true, ...
        'inside_workspace', true, ...
        'x_m', xyzM(1), ...
        'y_m', xyzM(2), ...
        'z_m', xyzM(3));
end
