%% MonoTeach Stage 3.1A
% Visualize the default task-plane configuration beside the Legacy 5DOF robot.
% This demo only draws geometry. It does not load trajectories or solve IK.

clear;
clc;
close all;

stage3Dir = fileparts(mfilename('fullpath'));
repoRoot = fileparts(stage3Dir);
stage1Dir = fullfile(repoRoot, 'stage1');

addpath(stage3Dir);
addpath(stage1Dir);

% Robot geometry and qHome are expressed in the Legacy base frame [m, rad].
robot = build_legacy_robot();
qHome = homeConfiguration(robot);

% The config describes centred task-plane coordinates and their base transform.
config = default_task_plane_config();
TBaseTaskplane = config.T_base_taskplane;
RBaseTaskplane = TBaseTaskplane(1:3, 1:3);
taskPlaneCenterBaseM = TBaseTaskplane(1:3, 4)';

figure;
ax = axes;
plot_legacy_robot(robot, qHome, ax);
hold(ax, 'on');

% Task-plane origin is the workspace centre, represented in base metres.
plot3( ...
    ax, ...
    taskPlaneCenterBaseM(1), ...
    taskPlaneCenterBaseM(2), ...
    taskPlaneCenterBaseM(3), ...
    'kp', ...
    'MarkerSize', 12, ...
    'LineWidth', 2, ...
    'DisplayName', 'Task plane centre');

% Draw task +X and +Y. Both vectors are already expressed in base metres.
axisLengthM = 0.050;
taskXAxisBase = RBaseTaskplane(:, 1)' * axisLengthM;
taskYAxisBase = RBaseTaskplane(:, 2)' * axisLengthM;

quiver3( ...
    ax, ...
    taskPlaneCenterBaseM(1), ...
    taskPlaneCenterBaseM(2), ...
    taskPlaneCenterBaseM(3), ...
    taskXAxisBase(1), ...
    taskXAxisBase(2), ...
    taskXAxisBase(3), ...
    0, ...
    'r', ...
    'LineWidth', 2, ...
    'MaxHeadSize', 0.5, ...
    'DisplayName', 'Task +X');

quiver3( ...
    ax, ...
    taskPlaneCenterBaseM(1), ...
    taskPlaneCenterBaseM(2), ...
    taskPlaneCenterBaseM(3), ...
    taskYAxisBase(1), ...
    taskYAxisBase(2), ...
    taskYAxisBase(3), ...
    0, ...
    'g', ...
    'LineWidth', 2, ...
    'MaxHeadSize', 0.5, ...
    'DisplayName', 'Task +Y');

% Rectangle corners are centred task-plane coordinates [m, m, 0].
halfWidthM = config.workspace_width_mm * config.scale / 2;
halfHeightM = config.workspace_height_mm * config.scale / 2;
taskCornersM = [ ...
    -halfWidthM, -halfHeightM, 0; ...
     halfWidthM, -halfHeightM, 0; ...
     halfWidthM,  halfHeightM, 0; ...
    -halfWidthM,  halfHeightM, 0; ...
    -halfWidthM, -halfHeightM, 0];

% T_base_taskplane maps every rectangle corner into the robot base frame [m].
taskCornersBaseM = ...
    (RBaseTaskplane * taskCornersM' + taskPlaneCenterBaseM')';

plot3( ...
    ax, ...
    taskCornersBaseM(:, 1), ...
    taskCornersBaseM(:, 2), ...
    taskCornersBaseM(:, 3), ...
    'm-', ...
    'LineWidth', 2, ...
    'DisplayName', 'Scaled 190 x 290 mm workspace');

title(ax, 'MonoTeach Stage 3.1A - Default Task Plane');
legend(ax, 'Location', 'best');

% Fixed base-frame limits make the arm and task-plane placement easy to inspect.
xlim(ax, [-0.15, 0.25]);
ylim(ax, [-0.15, 0.15]);
zlim(ax, [0.00, 0.42]);
drawnow;
