function ikResultSet = solve_ik_segments( ...
        robot, ...
        segmentSet, ...
        qAnchorOrResult, ...
        ikConfig)
%SOLVE_IK_SEGMENTS Solve Stage 3.1 pre-IK segments as Position-Only IK runs.
%
% Inputs:
%   robot           - Stage 1 Legacy 5DOF rigidBodyTree with DataFormat row
%   segmentSet      - immutable-by-convention Stage 3.1B pre-IK candidates
%   qAnchorOrResult - finite 1-by-5 q_anchor, or an anchor result with .q
%   ikConfig        - config from default_ik_config
%
% Output:
%   ikResultSet - joint-space derived data. Successful points form one or
%                 more IK-success subsegments; failures are retained as
%                 evidence and never represented as a successful q sample.
%
% Every pre-IK segment starts from q_anchor. Within one successful subsegment,
% the next target seeds from the previous accepted q. A numerical/geometry
% failure closes that subsegment and resets the next seed to q_anchor, because
% retaining previous q would falsely bridge an unexecuted Cartesian point.

    validate_inputs(robot, segmentSet, ikConfig);

    qAnchor = resolve_anchor_q(qAnchorOrResult);
    endEffector = char(string(ikConfig.end_effector));
    homeQ = row_configuration(homeConfiguration(robot));
    homePose = getTransform(robot, homeQ, endEffector);
    targetOrientation = homePose(1:3, 1:3);
    jointLimits = five_joint_limits(robot);
    ik = configured_ik(robot, ikConfig);

    successSegments = repmat(empty_success_segment(), 1, 0);
    failures = repmat(empty_failure(), 1, 0);

    for preIkSegmentIndex = 1:numel(segmentSet.segments)
        preIkSegment = segmentSet.segments(preIkSegmentIndex);

        % Each Stage 3.1B segment is independent. No seed crosses its
        % invalid/outside barrier, even if its predecessor ended in success.
        seedQ = qAnchor;
        previousQ = [];
        currentResults = struct([]);

        for sampleIndex = 1:numel(preIkSegment.samples)
            sample = preIkSegment.samples(sampleIndex);
            targetXYZM = [sample.x_m, sample.y_m, sample.z_m];
            targetPose = eye(4);
            targetPose(1:3, 1:3) = targetOrientation;
            targetPose(1:3, 4) = targetXYZM';

            [isSuccess, pointResult, failure] = solve_one_target( ...
                robot, ...
                ik, ...
                endEffector, ...
                targetPose, ...
                targetXYZM, ...
                seedQ, ...
                jointLimits, ...
                ikConfig.weights, ...
                ikConfig.position_error_tolerance_m, ...
                preIkSegmentIndex, ...
                preIkSegment.source_indices(sampleIndex), ...
                sample.t_ms);

            if isSuccess
                pointResult.source_index = preIkSegment.source_indices(sampleIndex);
                pointResult.t_ms = sample.t_ms;

                if isempty(previousQ)
                    % A subsegment first point has no successful predecessor.
                    pointResult.delta_q = [];
                else
                    pointResult.delta_q = pointResult.q - previousQ;
                end

                currentResults = append_result(currentResults, pointResult);

                % Only an accepted successful result updates the continuity
                % seed. Solver output from a failed target is never reused.
                previousQ = pointResult.q;
                seedQ = pointResult.q;
                continue;
            end

            failures(end + 1) = failure; %#ok<AGROW>

            if ~isempty(currentResults)
                successSegments(end + 1) = build_success_segment( ...
                    preIkSegmentIndex, ...
                    currentResults); %#ok<AGROW>
            end

            % The failed point is a hard barrier. If a later sample happens
            % to solve, it begins a new subsegment from q_anchor rather than
            % pretending the old joint state traversed the failed target.
            currentResults = struct([]);
            previousQ = [];
            seedQ = qAnchor;
        end

        if ~isempty(currentResults)
            successSegments(end + 1) = build_success_segment( ...
                preIkSegmentIndex, ...
                currentResults); %#ok<AGROW>
        end
    end

    ikResultSet = struct();
    ikResultSet.coordinate_space = 'joint';
    ikResultSet.units = 'rad';
    ikResultSet.segments = successSegments;
    ikResultSet.failures = failures;
    ikResultSet.summary = struct( ...
        'preik_segment_count', numel(segmentSet.segments), ...
        'ik_success_segment_count', numel(successSegments), ...
        'success_point_count', sum(arrayfun( ...
            @(segment) numel(segment.source_indices), successSegments)), ...
        'failure_count', numel(failures));
end


function [isSuccess, pointResult, failure] = solve_one_target( ...
        robot, ...
        ik, ...
        endEffector, ...
        targetPose, ...
        targetXYZM, ...
        seedQ, ...
        jointLimits, ...
        weights, ...
        positionToleranceM, ...
        preIkSegmentIndex, ...
        sourceIndex, ...
        tMs)

    isSuccess = false;
    pointResult = struct([]);
    failure = empty_failure();

    try
        [qCandidate, solutionInfo] = ik( ...
            endEffector, ...
            targetPose, ...
            weights, ...
            seedQ);
        qCandidate = row_configuration(qCandidate);
    catch exception
        failure = failure_from_exception( ...
            preIkSegmentIndex, ...
            sourceIndex, ...
            tMs, ...
            targetXYZM, ...
            seedQ, ...
            exception);
        return;
    end

    try
        fkPose = getTransform(robot, qCandidate, endEffector);
        fkXYZM = fkPose(1:3, 4)';
        pointResult = ik_result_contract( ...
            targetXYZM, ...
            seedQ, ...
            qCandidate, ...
            solutionInfo.Status, ...
            solutionInfo.PoseErrorNorm, ...
            fkXYZM, ...
            jointLimits);
    catch exception
        failure = failure_from_exception( ...
            preIkSegmentIndex, ...
            sourceIndex, ...
            tMs, ...
            targetXYZM, ...
            seedQ, ...
            exception);
        failure.candidate_q = qCandidate;
        failure.solver_status = solutionInfo.Status;
        failure.pose_error_norm = solutionInfo.PoseErrorNorm;
        return;
    end

    if pointResult.position_error_m <= positionToleranceM && ...
            pointResult.within_joint_limits
        isSuccess = true;
        return;
    end

    failure = empty_failure();
    failure.preik_segment_index = preIkSegmentIndex;
    failure.source_index = sourceIndex;
    failure.t_ms = tMs;
    failure.target_xyz_m = targetXYZM;
    failure.seed_q = seedQ;
    failure.solver_status = solutionInfo.Status;
    failure.pose_error_norm = solutionInfo.PoseErrorNorm;
    failure.candidate_q = qCandidate;
    failure.fk_xyz_m = fkXYZM;
    failure.position_error_m = pointResult.position_error_m;
    failure.within_joint_limits = pointResult.within_joint_limits;
    failure.joint_limit_margin = pointResult.joint_limit_margin;
    failure.reason = failure_reason(pointResult, positionToleranceM);
end


function resultArray = append_result(resultArray, result)

    if isempty(resultArray)
        resultArray = result;
    else
        resultArray(end + 1) = result; %#ok<AGROW>
    end
end


function segment = build_success_segment(preIkSegmentIndex, pointResults)

    segment = empty_success_segment();
    segment.preik_segment_index = preIkSegmentIndex;
    segment.source_indices = [pointResults.source_index];
    segment.t_ms = [pointResults.t_ms];
    segment.q_rad = vertcat(pointResults.q);
    segment.results = pointResults;
end


function ik = configured_ik(robot, ikConfig)

    ik = inverseKinematics( ...
        'RigidBodyTree', robot, ...
        'SolverAlgorithm', ikConfig.solver_algorithm);
    solverParameters = ik.SolverParameters;

    if ~isfield(solverParameters, 'AllowRandomRestart')
        error( ...
            'MonoTeach:UnsupportedInverseKinematicsAPI', ...
            'R2024a SolverParameters must contain AllowRandomRestart.');
    end

    solverParameters.AllowRandomRestart = ikConfig.allow_random_restart;
    ik.SolverParameters = solverParameters;
end


function qAnchor = resolve_anchor_q(qAnchorOrResult)

    if isnumeric(qAnchorOrResult)
        qAnchor = qAnchorOrResult;
    elseif isstruct(qAnchorOrResult) && isscalar(qAnchorOrResult) && ...
            isfield(qAnchorOrResult, 'q')
        qAnchor = qAnchorOrResult.q;
    else
        error( ...
            'MonoTeach:InvalidAnchorIKSeed', ...
            'qAnchorOrResult must be a finite q row vector or result with .q.');
    end

    qAnchor = row_configuration(qAnchor);
end


function reason = failure_reason(pointResult, positionToleranceM)

    if ~pointResult.within_joint_limits
        reason = 'joint_limit_violation';
    elseif pointResult.position_error_m > positionToleranceM
        reason = 'position_error_exceeds_tolerance';
    else
        reason = 'unknown_acceptance_failure';
    end
end


function failure = failure_from_exception( ...
        preIkSegmentIndex, ...
        sourceIndex, ...
        tMs, ...
        targetXYZM, ...
        seedQ, ...
        exception)

    failure = empty_failure();
    failure.preik_segment_index = preIkSegmentIndex;
    failure.source_index = sourceIndex;
    failure.t_ms = tMs;
    failure.target_xyz_m = targetXYZM;
    failure.seed_q = seedQ;
    failure.solver_status = 'exception';
    failure.reason = 'solver_or_fk_exception';
    failure.exception_identifier = exception.identifier;
    failure.exception_message = exception.message;
end


function segment = empty_success_segment()

    segment = struct( ...
        'preik_segment_index', [], ...
        'source_indices', [], ...
        't_ms', [], ...
        'q_rad', [], ...
        'results', struct([]));
end


function failure = empty_failure()

    % q is intentionally empty for every failure: no configuration is emitted
    % as a successful trajectory point. candidate_q, when present, is solver
    % diagnostic evidence only and is never used as a continuity seed.
    failure = struct( ...
        'preik_segment_index', [], ...
        'source_index', [], ...
        't_ms', [], ...
        'target_xyz_m', [], ...
        'seed_q', [], ...
        'solver_status', [], ...
        'pose_error_norm', [], ...
        'q', [], ...
        'candidate_q', [], ...
        'fk_xyz_m', [], ...
        'position_error_m', [], ...
        'within_joint_limits', false, ...
        'joint_limit_margin', [], ...
        'reason', [], ...
        'exception_identifier', [], ...
        'exception_message', []);
end


function validate_inputs(robot, segmentSet, ikConfig)

    if ~isa(robot, 'rigidBodyTree') || ~strcmp(robot.DataFormat, 'row') || ...
            robot.NumBodies ~= 5
        error( ...
            'MonoTeach:InvalidContinuousIKRobot', ...
            'robot must be the five-body Legacy rigidBodyTree with row format.');
    end

    validate_segment_set(segmentSet);

    if ~isstruct(ikConfig) || ~isscalar(ikConfig)
        error( ...
            'MonoTeach:InvalidContinuousIKConfig', ...
            'ikConfig must be one scalar config struct.');
    end

    requiredFields = { ...
        'end_effector', ...
        'weights', ...
        'position_error_tolerance_m', ...
        'allow_random_restart', ...
        'solver_algorithm'};
    missingFields = requiredFields(~isfield(ikConfig, requiredFields));

    if ~isempty(missingFields) || ...
            ~strcmp(string(ikConfig.end_effector), "body5") || ...
            ~isequal(ikConfig.weights, [0, 0, 0, 1, 1, 1]) || ...
            ~islogical(ikConfig.allow_random_restart) || ...
            ~isscalar(ikConfig.allow_random_restart) || ...
            ~isnumeric(ikConfig.position_error_tolerance_m) || ...
            ~isscalar(ikConfig.position_error_tolerance_m) || ...
            ~isfinite(ikConfig.position_error_tolerance_m) || ...
            ikConfig.position_error_tolerance_m <= 0 || ...
            ~strcmp(string(ikConfig.solver_algorithm), "BFGSGradientProjection")
        error( ...
            'MonoTeach:InvalidContinuousIKConfig', ...
            'ikConfig must be the deterministic Position-Only baseline config.');
    end
end


function validate_segment_set(segmentSet)

    if ~isstruct(segmentSet) || ~isscalar(segmentSet) || ...
            ~isfield(segmentSet, 'coordinate_frame') || ...
            ~isfield(segmentSet, 'units') || ...
            ~isfield(segmentSet, 'segments') || ...
            ~strcmp(string(segmentSet.coordinate_frame), "robot_base") || ...
            ~strcmp(string(segmentSet.units), "m") || ...
            ~isstruct(segmentSet.segments)
        error( ...
            'MonoTeach:InvalidContinuousIKSegmentSet', ...
            'segmentSet must be a robot_base metre SegmentSet with segments.');
    end

    for i = 1:numel(segmentSet.segments)
        segment = segmentSet.segments(i);

        if ~isfield(segment, 'source_indices') || ~isfield(segment, 'samples') || ...
                ~isnumeric(segment.source_indices) || ...
                ~isrow(segment.source_indices) || ...
                ~isstruct(segment.samples) || ...
                numel(segment.source_indices) ~= numel(segment.samples)
            error( ...
                'MonoTeach:InvalidContinuousIKSegment', ...
                'Each segment must align source_indices with samples.');
        end

        for j = 1:numel(segment.samples)
            sample = segment.samples(j);
            requiredSampleFields = { ...
                't_ms', 'valid', 'inside_workspace', 'x_m', 'y_m', 'z_m'};

            if ~all(isfield(sample, requiredSampleFields)) || ...
                    ~sample.valid || ~sample.inside_workspace || ...
                    ~isnumeric(sample.t_ms) || ~isscalar(sample.t_ms) || ...
                    ~isfinite(sample.t_ms) || sample.t_ms < 0 || ...
                    ~all(isfinite([sample.x_m, sample.y_m, sample.z_m]))
                error( ...
                    'MonoTeach:InvalidContinuousIKSample', ...
                    'Each pre-IK sample must be valid, inside, and finite.');
            end
        end
    end
end


function q = row_configuration(configuration)

    if ~isnumeric(configuration) || ~isreal(configuration) || ...
            any(~isfinite(configuration), 'all')
        error( ...
            'MonoTeach:InvalidContinuousIKConfiguration', ...
            'A continuous IK configuration must be finite real numeric data.');
    end

    q = reshape(configuration, 1, []);

    if numel(q) ~= 5
        error( ...
            'MonoTeach:UnexpectedContinuousIKDof', ...
            'The Legacy continuous IK baseline requires five joint values.');
    end
end


function limits = five_joint_limits(robot)

    limits = zeros(5, 2);

    for i = 1:5
        joint = robot.Bodies{i}.Joint;

        if ~strcmp(joint.Type, 'revolute')
            error( ...
                'MonoTeach:UnexpectedContinuousIKJoint', ...
                'Legacy body %d must have a revolute joint.', ...
                i);
        end

        limits(i, :) = joint.PositionLimits;
    end
end
