%% MonoTeach Stage 3.2
% Final verification for the deterministic Position-Only continuous IK
% baseline. This verifies accepted IK/FK geometry and failure-barrier data;
% it does not perform timing, qdot/qddot, animation, or robot execution.

clear;
clc;
format long g;

stage3Dir = fileparts(mfilename('fullpath'));
repoRoot = fileparts(stage3Dir);
addpath(stage3Dir);
addpath(fullfile(repoRoot, 'stage1'));

fprintf('============================================\n');
fprintf('MonoTeach Stage 3.2 Final Verification\n');
fprintf('============================================\n');

allPassed = true;
robot = build_legacy_robot();
taskPlaneConfig = default_task_plane_config();
ikConfig = default_ik_config();


%% 1. Deterministic Position-Only anchor baseline

fprintf('\n[1] Default config and anchor IK/FK\n');
configPassed = ...
    strcmp(string(ikConfig.end_effector), "body5") && ...
    isequal(ikConfig.weights, [0, 0, 0, 1, 1, 1]) && ...
    ~ikConfig.allow_random_restart && ...
    ikConfig.position_error_tolerance_m > 0;
allPassed = report_result( ...
    allPassed, ...
    'Default config is deterministic Position-Only baseline', ...
    configPassed);

anchorResult = solve_anchor_ik(robot, taskPlaneConfig, ikConfig);
anchorFkPose = getTransform(robot, anchorResult.q, ikConfig.end_effector);
anchorFkError = norm( ...
    anchorFkPose(1:3, 4)' - taskPlaneConfig.robot_anchor_m);
anchorPassed = ...
    isequal(size(anchorResult.q), [1, 5]) && ...
    all(isfinite(anchorResult.q)) && ...
    anchorResult.within_joint_limits && ...
    all(anchorResult.joint_limit_margin >= 0) && ...
    anchorResult.position_error_m <= ikConfig.position_error_tolerance_m && ...
    anchorFkError <= ikConfig.position_error_tolerance_m;
fprintf('Anchor FK error [m]: %.9e\n', anchorFkError);
allPassed = report_result( ...
    allPassed, ...
    'Anchor IK and independent FK back-check', ...
    anchorPassed);


%% 2. Known reachable target: assert recovered XYZ, never q equality

fprintf('\n[2] Known-reachable Position-Only IK\n');
qKnown = deg2rad([30, 60, -30, 120, 45]);
knownPose = getTransform(robot, qKnown, ikConfig.end_effector);
knownTargetXYZ = knownPose(1:3, 4)';
knownSet = one_sample_segment_set(101, 10.0, knownTargetXYZ);
knownResultSet = solve_ik_segments(robot, knownSet, anchorResult, ikConfig);
knownPassed = knownResultSet.summary.success_point_count == 1 && ...
    knownResultSet.summary.failure_count == 0 && ...
    knownResultSet.segments(1).results(1).position_error_m <= ...
        ikConfig.position_error_tolerance_m && ...
    knownResultSet.segments(1).results(1).within_joint_limits;
allPassed = report_result( ...
    allPassed, ...
    'Known reachable target recovers FK XYZ (not necessarily q_known)', ...
    knownPassed);


%% 3. Previous-q provenance, failure barrier, and reset behaviour

fprintf('\n[3] Continuous seeds, failure barrier, and provenance\n');
segmentSet = synthetic_failure_segment_set(robot, ikConfig);
segmentSetBefore = segmentSet;
ikResultSet = solve_ik_segments(robot, segmentSet, anchorResult, ikConfig);
continuity = summarize_ik_continuity(ikResultSet);

if numel(ikResultSet.segments) >= 2 && numel(ikResultSet.failures) == 1
    firstSegment = ikResultSet.segments(1);
    secondSegment = ikResultSet.segments(2);
    failure = ikResultSet.failures(1);

    previousSeedPassed = numel(firstSegment.results) == 2 && ...
        isequal(firstSegment.results(2).seed_q, firstSegment.results(1).q);
    barrierPassed = failure.source_index == 13 && ...
        isempty(failure.q) && ...
        ~ismember(13, [ikResultSet.segments.source_indices]);
    resetPassed = numel(secondSegment.results) == 1 && ...
        isequal(secondSegment.results(1).seed_q, anchorResult.q) && ...
        isempty(secondSegment.results(1).delta_q);
    provenancePassed = ...
        isequal(firstSegment.source_indices, [11, 12]) && ...
        isequal(firstSegment.t_ms, [0.0, 100.0]) && ...
        isequal(secondSegment.source_indices, 14) && ...
        isequal(secondSegment.t_ms, 300.0) && ...
        firstSegment.results(2).source_index == 12 && ...
        firstSegment.results(2).t_ms == 100.0;
else
    previousSeedPassed = false;
    barrierPassed = false;
    resetPassed = false;
    provenancePassed = false;
end

allPassed = report_result( ...
    allPassed, ...
    'Previous successful q is the next seed', ...
    previousSeedPassed);
allPassed = report_result( ...
    allPassed, ...
    'Synthetic unreachable point is a failure barrier without q', ...
    barrierPassed);
allPassed = report_result( ...
    allPassed, ...
    'Post-failure success restarts from q_anchor', ...
    resetPassed);
allPassed = report_result( ...
    allPassed, ...
    'source_index and t_ms provenance are retained', ...
    provenancePassed);
allPassed = report_result( ...
    allPassed, ...
    'Stage 3.1 SegmentSet input remains unchanged', ...
    isequaln(segmentSet, segmentSetBefore));


%% 4. Derived continuity and explicit joint-limit evidence

fprintf('\n[4] Continuity and joint-limit diagnostics\n');
expectedDelta = ikResultSet.segments(1).results(2).delta_q;
expectedErrors = [ ...
    ikResultSet.segments(1).results.position_error_m, ...
    ikResultSet.segments(2).results.position_error_m];
allResults = [ ...
    ikResultSet.segments(1).results, ...
    ikResultSet.segments(2).results];
expectedMinimumMargin = min(vertcat(allResults.joint_limit_margin), [], 'all');
[expectedMaxStep, expectedJoint] = max(abs(expectedDelta));

continuityPassed = ...
    continuity.success_point_count == 3 && ...
    continuity.failure_count == 1 && ...
    abs(continuity.ik_success_rate - 0.75) <= 1e-12 && ...
    abs(continuity.mean_fk_position_error_m - mean(expectedErrors)) <= 1e-12 && ...
    abs(continuity.max_fk_position_error_m - max(expectedErrors)) <= 1e-12 && ...
    isequal(continuity.per_joint_max_abs_delta_q, abs(expectedDelta)) && ...
    abs(continuity.overall_max_joint_step - expectedMaxStep) <= 1e-12 && ...
    continuity.largest_jump_source_index == 12 && ...
    continuity.largest_jump_joint_index == expectedJoint && ...
    abs(continuity.minimum_joint_limit_margin - expectedMinimumMargin) <= 1e-12;
allPassed = report_result( ...
    allPassed, ...
    'Continuity summary agrees with canonical delta_q and FK data', ...
    continuityPassed);

jointLimitPassed = all([allResults.within_joint_limits]) && ...
    all(isfinite(vertcat(allResults.joint_limit_margin)), 'all') && ...
    all(vertcat(allResults.joint_limit_margin) >= 0, 'all');
allPassed = report_result( ...
    allPassed, ...
    'All accepted synthetic points satisfy explicit joint limits', ...
    jointLimitPassed);


%% 5. Final result

fprintf('\n============================================\n');
if allPassed
    fprintf('FINAL RESULT: PASS\n');
else
    fprintf('FINAL RESULT: FAIL\n');
end
fprintf('============================================\n');

if ~allPassed
    error( ...
        'MonoTeach:Stage3_2VerificationFailed', ...
        'Stage 3.2 verification failed.');
end


%% Local helpers

function allPassed = report_result(allPassed, label, condition)

    if condition
        result = 'PASS';
    else
        result = 'FAIL';
    end

    fprintf('%s -> %s\n', label, result);
    allPassed = allPassed && condition;
end


function segmentSet = one_sample_segment_set(sourceIndex, tMs, xyzM)

    segmentSet = struct( ...
        'coordinate_frame', 'robot_base', ...
        'units', 'm', ...
        'segments', struct( ...
            'source_indices', sourceIndex, ...
            'samples', synthetic_sample(tMs, xyzM)));
end


function segmentSet = synthetic_failure_segment_set(robot, ikConfig)

    qOne = homeConfiguration(robot);
    qTwo = deg2rad([10, 100, -10, 100, 10]);
    qThree = deg2rad([-10, 80, 10, 110, -10]);
    poseOne = getTransform(robot, qOne, ikConfig.end_effector);
    poseTwo = getTransform(robot, qTwo, ikConfig.end_effector);
    poseThree = getTransform(robot, qThree, ikConfig.end_effector);

    samples = [ ...
        synthetic_sample(0.0, poseOne(1:3, 4)'), ...
        synthetic_sample(100.0, poseTwo(1:3, 4)'), ...
        synthetic_sample(200.0, [10.0, 10.0, 10.0]), ...
        synthetic_sample(300.0, poseThree(1:3, 4)')];
    segmentSet = struct( ...
        'coordinate_frame', 'robot_base', ...
        'units', 'm', ...
        'segments', struct('source_indices', [11, 12, 13, 14], 'samples', samples));
end


function sample = synthetic_sample(tMs, xyzM)

    sample = struct( ...
        't_ms', tMs, ...
        'valid', true, ...
        'inside_workspace', true, ...
        'x_m', xyzM(1), ...
        'y_m', xyzM(2), ...
        'z_m', xyzM(3));
end
