function diagnostic = diagnose_writing_anchor_multistart( ...
        robot, taskPlaneConfig, ikConfig, writingPostureConfig, diagnosticConfig)
%DIAGNOSE_WRITING_ANCHOR_MULTISTART Diagnose writing posture at one anchor.
%
% This is an anchor-only, deterministic feasibility diagnostic. It compares
% body5 local +Z aiming at +/- task-plane normals across a fixed seed set and
% does not alter the frozen Stage 3.2 Position-Only solver or any tolerance.

    if nargin < 5 || isempty(diagnosticConfig)
        diagnosticConfig = default_writing_anchor_diagnostic_config();
    end
    validate_inputs(robot, taskPlaneConfig, ikConfig, ...
        writingPostureConfig, diagnosticConfig);

    endEffector = char(string(writingPostureConfig.end_effector));
    targetXYZ = reshape(taskPlaneConfig.robot_anchor_m, 1, 3);
    nPlane = derive_task_plane_normal(taskPlaneConfig)';
    positionOnlyAnchor = solve_anchor_ik(robot, taskPlaneConfig, ikConfig);
    seedSet = deterministic_seed_set( ...
        robot, positionOnlyAnchor.q, diagnosticConfig);
    jointLimits = five_joint_limits(robot);

    runCount = numel(writingPostureConfig.candidate_plane_normal_signs) * ...
        numel(diagnosticConfig.solver_algorithms);
    runs = repmat(empty_run(), 1, runCount);
    runIndex = 0;

    for signValue = writingPostureConfig.candidate_plane_normal_signs
        signedNormal = signValue * nPlane;
        aimTarget = targetXYZ + ...
            writingPostureConfig.aim_distance_m * signedNormal;
        positionConstraint = constraintPositionTarget(endEffector);
        positionConstraint.TargetPosition = targetXYZ;
        positionConstraint.PositionTolerance = ...
            writingPostureConfig.position_tolerance_m;
        aimingConstraint = constraintAiming(endEffector);
        aimingConstraint.TargetPoint = aimTarget;
        aimingConstraint.AngularTolerance = ...
            writingPostureConfig.aiming_angular_tolerance_rad;

        for algorithmIndex = 1:numel(diagnosticConfig.solver_algorithms)
            solverAlgorithm = diagnosticConfig.solver_algorithms{algorithmIndex};
            gik = configured_gik( ...
                robot, solverAlgorithm, diagnosticConfig.allow_random_restart);

            trials = repmat(empty_trial(), 1, numel(seedSet));
            for seedIndex = 1:numel(seedSet)
                trials(seedIndex) = solve_one_trial( ...
                    robot, ...
                    gik, ...
                    positionConstraint, ...
                    aimingConstraint, ...
                    seedSet(seedIndex), ...
                    targetXYZ, ...
                    signedNormal, ...
                    endEffector, ...
                    jointLimits, ...
                    writingPostureConfig);
            end

            runIndex = runIndex + 1;
            runs(runIndex) = summarize_run( ...
                signValue, ...
                signedNormal, ...
                aimTarget, ...
                solverAlgorithm, ...
                trials, ...
                writingPostureConfig);
        end
    end

    diagnostic = struct();
    diagnostic.target_xyz_m = targetXYZ;
    diagnostic.plane_normal_base = nPlane;
    diagnostic.position_only_anchor = positionOnlyAnchor;
    diagnostic.seed_set = seedSet;
    diagnostic.runs = runs;
end


function gik = configured_gik(robot, solverAlgorithm, allowRandomRestart)

    gik = generalizedInverseKinematics( ...
        'RigidBodyTree', robot, ...
        'ConstraintInputs', {'position', 'aiming'}, ...
        'SolverAlgorithm', solverAlgorithm);
    solverParameters = gik.SolverParameters;
    if ~isfield(solverParameters, 'AllowRandomRestart')
        error( ...
            'MonoTeach:UnsupportedGeneralizedInverseKinematicsAPI', ...
            'R2024a GIK SolverParameters must contain AllowRandomRestart.');
    end
    solverParameters.AllowRandomRestart = allowRandomRestart;
    gik.SolverParameters = solverParameters;
end


function seedSet = deterministic_seed_set(robot, qAnchor, diagnosticConfig)

    limits = five_joint_limits(robot);
    qHome = reshape(homeConfiguration(robot), 1, []);
    seedSet = struct('name', {}, 'initial_q', {});
    if is_limit_valid_configuration(qAnchor, limits)
        seedSet(end + 1) = struct( ... %#ok<AGROW>
            'name', 'position_only_q_anchor', ...
            'initial_q', qAnchor);
    end
    if is_limit_valid_configuration(qHome, limits)
        seedSet(end + 1) = struct( ... %#ok<AGROW>
            'name', 'home_configuration', ...
            'initial_q', qHome);
    end

    priorRngState = rng;
    restoreRng = onCleanup(@() rng(priorRngState)); %#ok<NASGU>
    rng(diagnosticConfig.random_seed, 'twister');
    for randomIndex = 1:diagnosticConfig.random_seed_count
        initialQ = limits(:, 1)' + rand(1, robot.NumBodies) .* ...
            (limits(:, 2)' - limits(:, 1)');
        seedSet(end + 1) = struct( ... %#ok<AGROW>
            'name', sprintf('fixed_random_%02d', randomIndex), ...
            'initial_q', initialQ);
    end

    if isfield(diagnosticConfig, 'additional_seed_set')
        additionalSeeds = diagnosticConfig.additional_seed_set;
        jointLimits = five_joint_limits(robot);
        for additionalIndex = 1:numel(additionalSeeds)
            seedSet(end + 1) = additionalSeeds(additionalIndex); %#ok<AGROW>
        end
    end
end


function trial = solve_one_trial( ...
        robot, gik, positionConstraint, aimingConstraint, seed, ...
        targetXYZ, signedNormal, endEffector, jointLimits, writingPostureConfig)

    trial = empty_trial();
    trial.seed_name = seed.name;
    trial.initial_q = seed.initial_q;
    trial.solver_algorithm = gik.SolverAlgorithm;

    try
        [q, solutionInfo] = gik( ...
            seed.initial_q, positionConstraint, aimingConstraint);
        q = reshape(q, 1, []);
        trial.candidate_q = q;
        trial.solver_status = char(string(solutionInfo.Status));

        fkPose = getTransform(robot, q, endEffector);
        trial.fk_xyz_m = fkPose(1:3, 4)';
        trial.position_error_m = norm(trial.fk_xyz_m - targetXYZ);
        trial.fk_tool_z_direction = unit_vector(fkPose(1:3, 3)');
        trial.tool_direction_error_rad = angle_between_unit_vectors( ...
            trial.fk_tool_z_direction, signedNormal);
        trial.tool_direction_error_deg = rad2deg( ...
            trial.tool_direction_error_rad);
        [trial.within_joint_limits, trial.joint_limit_margin] = ...
            joint_limit_evidence(q, jointLimits);
        trial.within_position_tolerance = ...
            trial.position_error_m <= writingPostureConfig.position_tolerance_m;
        trial.within_aiming_tolerance = ...
            trial.tool_direction_error_rad <= ...
            writingPostureConfig.aiming_angular_tolerance_rad;
        trial.solver_status_is_success = ...
            strcmpi(trial.solver_status, 'success');
        trial.accepted = trial.solver_status_is_success && ...
            trial.within_position_tolerance && ...
            trial.within_aiming_tolerance && ...
            trial.within_joint_limits;

        if ~trial.accepted
            trial.failure_reason = 'solver_or_backcheck_not_accepted';
        end
    catch exception
        trial.solver_status = ['exception:' exception.identifier];
        trial.failure_reason = exception.message;
    end
end


function run = summarize_run( ...
        signValue, signedNormal, aimTarget, solverAlgorithm, trials, config)

    run = empty_run();
    run.sign = signValue;
    run.signed_normal = signedNormal;
    run.aim_target_m = aimTarget;
    run.solver_algorithm = solverAlgorithm;
    run.trials = trials;
    run.trials_count = numel(trials);
    run.accepted_count = sum([trials.accepted]);
    run.has_formally_accepted_solution = run.accepted_count > 0;

    successfulTrials = find(arrayfun(@(trial) isfinite( ...
        trial.position_error_m) && isfinite(trial.tool_direction_error_rad), trials));
    if isempty(successfulTrials)
        return;
    end

    positionErrors = [trials(successfulTrials).position_error_m];
    directionErrors = [trials(successfulTrials).tool_direction_error_rad];
    [run.best_position_error_m, relativePositionIndex] = min(positionErrors);
    run.best_position_trial_index = successfulTrials(relativePositionIndex);
    [run.best_direction_error_rad, relativeDirectionIndex] = min(directionErrors);
    run.best_direction_error_deg = rad2deg(run.best_direction_error_rad);
    run.best_direction_trial_index = successfulTrials(relativeDirectionIndex);

    % The combined candidate is selected only among limit-feasible trials,
    % using formal normalized tolerances. It is therefore not a relaxed
    % success criterion and can differ from either individual best result.
    jointFeasibleTrials = successfulTrials([trials(successfulTrials).within_joint_limits]);
    if isempty(jointFeasibleTrials)
        jointFeasibleTrials = successfulTrials;
    end
    combinedScores = arrayfun(@(trial) max( ...
        trial.position_error_m / config.position_tolerance_m, ...
        trial.tool_direction_error_rad / config.aiming_angular_tolerance_rad), ...
        trials(jointFeasibleTrials));
    [run.best_combined_score, relativeCombinedIndex] = min(combinedScores);
    run.best_combined_trial_index = jointFeasibleTrials(relativeCombinedIndex);
    combinedTrial = trials(run.best_combined_trial_index);
    run.best_combined_position_error_m = combinedTrial.position_error_m;
    run.best_combined_direction_error_rad = ...
        combinedTrial.tool_direction_error_rad;
    run.best_combined_direction_error_deg = ...
        combinedTrial.tool_direction_error_deg;
    run.best_combined_within_joint_limits = combinedTrial.within_joint_limits;
    run.best_combined_min_joint_limit_margin = ...
        min(combinedTrial.joint_limit_margin);
    run.has_simultaneous_position_and_direction_solution = any(arrayfun( ...
        @(trial) trial.within_position_tolerance && ...
            trial.within_aiming_tolerance, ...
        trials(successfulTrials)));
end


function run = empty_run()

    run = struct( ...
        'sign', NaN, ...
        'signed_normal', NaN(1, 3), ...
        'aim_target_m', NaN(1, 3), ...
        'solver_algorithm', '', ...
        'trials', repmat(empty_trial(), 1, 0), ...
        'trials_count', 0, ...
        'accepted_count', 0, ...
        'has_formally_accepted_solution', false, ...
        'best_position_error_m', NaN, ...
        'best_position_trial_index', NaN, ...
        'best_direction_error_rad', NaN, ...
        'best_direction_error_deg', NaN, ...
        'best_direction_trial_index', NaN, ...
        'best_combined_score', NaN, ...
        'best_combined_trial_index', NaN, ...
        'best_combined_position_error_m', NaN, ...
        'best_combined_direction_error_rad', NaN, ...
        'best_combined_direction_error_deg', NaN, ...
        'best_combined_within_joint_limits', false, ...
        'best_combined_min_joint_limit_margin', NaN, ...
        'has_simultaneous_position_and_direction_solution', false);
end


function trial = empty_trial()

    trial = struct( ...
        'seed_name', '', ...
        'initial_q', NaN(1, 5), ...
        'solver_algorithm', '', ...
        'candidate_q', [], ...
        'solver_status', '', ...
        'fk_xyz_m', NaN(1, 3), ...
        'position_error_m', NaN, ...
        'fk_tool_z_direction', NaN(1, 3), ...
        'tool_direction_error_rad', NaN, ...
        'tool_direction_error_deg', NaN, ...
        'within_joint_limits', false, ...
        'joint_limit_margin', NaN(1, 5), ...
        'within_position_tolerance', false, ...
        'within_aiming_tolerance', false, ...
        'solver_status_is_success', false, ...
        'accepted', false, ...
        'failure_reason', '');
end


function validate_inputs( ...
        robot, taskPlaneConfig, ikConfig, writingPostureConfig, diagnosticConfig)

    if ~isa(robot, 'rigidBodyTree') || ~strcmp(robot.DataFormat, 'row') || ...
            robot.NumBodies ~= 5
        error( ...
            'MonoTeach:InvalidWritingDiagnosticRobot', ...
            'robot must be the row-format Legacy 5DOF rigidBodyTree.');
    end

    if ~isstruct(taskPlaneConfig) || ~isscalar(taskPlaneConfig) || ...
            ~isfield(taskPlaneConfig, 'robot_anchor_m') || ...
            ~isequal(size(taskPlaneConfig.robot_anchor_m), [1, 3])
        error( ...
            'MonoTeach:InvalidWritingDiagnosticTaskPlane', ...
            'taskPlaneConfig must contain a 1-by-3 robot_anchor_m.');
    end

    if ~isstruct(ikConfig) || ~isscalar(ikConfig)
        error( ...
            'MonoTeach:InvalidWritingDiagnosticIKConfig', ...
            'ikConfig must be one scalar config struct.');
    end

    if ~isstruct(writingPostureConfig) || ~isscalar(writingPostureConfig) || ...
            ~strcmp(string(writingPostureConfig.end_effector), "body5") || ...
            ~strcmp(string(writingPostureConfig.tool_axis), "z") || ...
            ~is_valid_candidate_signs( ...
                writingPostureConfig.candidate_plane_normal_signs)
        error( ...
            'MonoTeach:InvalidWritingDiagnosticPostureConfig', ...
            ['writingPostureConfig must retain body5 local +Z and one or ' ...
             'both of the +/- normal candidates.']);
    end

    require_positive_scalar( ...
        writingPostureConfig.aim_distance_m, 'aim_distance_m');
    require_positive_scalar( ...
        writingPostureConfig.position_tolerance_m, 'position_tolerance_m');
    require_positive_scalar( ...
        writingPostureConfig.aiming_angular_tolerance_rad, ...
        'aiming_angular_tolerance_rad');

    if ~isstruct(diagnosticConfig) || ~isscalar(diagnosticConfig) || ...
            ~isfield(diagnosticConfig, 'random_seed') || ...
            ~isfield(diagnosticConfig, 'random_seed_count') || ...
            ~isfield(diagnosticConfig, 'solver_algorithms') || ...
            ~isfield(diagnosticConfig, 'allow_random_restart')
        error( ...
            'MonoTeach:InvalidWritingDiagnosticConfig', ...
            'diagnosticConfig is missing required deterministic fields.');
    end

    if ~isnumeric(diagnosticConfig.random_seed) || ...
            ~isscalar(diagnosticConfig.random_seed) || ...
            diagnosticConfig.random_seed < 0 || ...
            diagnosticConfig.random_seed ~= floor(diagnosticConfig.random_seed) || ...
            ~isnumeric(diagnosticConfig.random_seed_count) || ...
            ~isscalar(diagnosticConfig.random_seed_count) || ...
            diagnosticConfig.random_seed_count < 0 || ...
            diagnosticConfig.random_seed_count ~= ...
                floor(diagnosticConfig.random_seed_count)
        error( ...
            'MonoTeach:InvalidWritingDiagnosticSeedConfig', ...
            'random_seed and random_seed_count must be nonnegative integers.');
    end

    if ~iscellstr(diagnosticConfig.solver_algorithms) || ...
            isempty(diagnosticConfig.solver_algorithms) || ...
            ~all(ismember(diagnosticConfig.solver_algorithms, ...
                {'BFGSGradientProjection', 'LevenbergMarquardt'}))
        error( ...
            'MonoTeach:InvalidWritingDiagnosticAlgorithms', ...
            ['solver_algorithms must contain R2024a BFGSGradientProjection ' ...
             'and/or LevenbergMarquardt names.']);
    end

    if ~islogical(diagnosticConfig.allow_random_restart) || ...
            ~isscalar(diagnosticConfig.allow_random_restart) || ...
            diagnosticConfig.allow_random_restart
        error( ...
            'MonoTeach:InvalidWritingDiagnosticRestartPolicy', ...
            'Deterministic multi-start requires AllowRandomRestart=false.');
    end

    if isfield(diagnosticConfig, 'additional_seed_set')
        additionalSeeds = diagnosticConfig.additional_seed_set;
        jointLimits = five_joint_limits(robot);
        if ~isstruct(additionalSeeds) || ...
                ~all(isfield(additionalSeeds, {'name', 'initial_q'}))
            error( ...
                'MonoTeach:InvalidWritingDiagnosticAdditionalSeeds', ...
                'additional_seed_set must contain name and initial_q fields.');
        end
        for additionalIndex = 1:numel(additionalSeeds)
            initialQ = additionalSeeds(additionalIndex).initial_q;
            if ~isnumeric(initialQ) || ~isreal(initialQ) || ...
                    ~isequal(size(initialQ), [1, robot.NumBodies]) || ...
                    any(~isfinite(initialQ)) || ...
                    any(initialQ < jointLimits(:, 1)') || ...
                    any(initialQ > jointLimits(:, 2)')
                error( ...
                    'MonoTeach:InvalidWritingDiagnosticAdditionalSeed', ...
                    ['Each additional seed must be a finite, limit-valid ' ...
                     '1-by-5 vector.']);
            end
        end
    end
end


function isValid = is_valid_candidate_signs(signs)

    isValid = isnumeric(signs) && isreal(signs) && isrow(signs) && ...
        ~isempty(signs) && all(ismember(signs, [+1, -1])) && ...
        numel(unique(signs)) == numel(signs);
end


function isValid = is_limit_valid_configuration(q, limits)

    isValid = isnumeric(q) && isreal(q) && ...
        isequal(size(q), [1, size(limits, 1)]) && all(isfinite(q)) && ...
        all(q >= limits(:, 1)' & q <= limits(:, 2)');
end


function limits = five_joint_limits(robot)

    limits = zeros(robot.NumBodies, 2);
    for bodyIndex = 1:robot.NumBodies
        limits(bodyIndex, :) = robot.Bodies{bodyIndex}.Joint.PositionLimits;
    end
end


function [withinLimits, margin] = joint_limit_evidence(q, limits)

    margin = min(q - limits(:, 1)', limits(:, 2)' - q);
    withinLimits = all(q >= limits(:, 1)' & q <= limits(:, 2)');
end


function unitVector = unit_vector(vector)

    magnitude = norm(vector);
    if ~isfinite(magnitude) || magnitude <= eps
        error( ...
            'MonoTeach:DegenerateWritingDiagnosticToolDirection', ...
            'FK tool-Z direction must be finite and nonzero.');
    end
    unitVector = vector / magnitude;
end


function angleRad = angle_between_unit_vectors(first, second)

    angleRad = acos(max(-1.0, min(1.0, dot(first, second))));
end


function require_positive_scalar(value, context)

    if ~isnumeric(value) || ~isscalar(value) || ~isreal(value) || ...
            ~isfinite(value) || value <= 0
        error( ...
            'MonoTeach:InvalidWritingDiagnosticInput', ...
            '%s must be one positive finite scalar.', context);
    end
end
