function visualization = visualize_writing_anchor_diagnostic( ...
        robot, taskPlaneConfig, ikConfig, writingPostureConfig)
%VISUALIZE_WRITING_ANCHOR_DIAGNOSTIC Show body5 axes and aiming geometry.
%
% The robot is drawn at the frozen Stage 3.2 Position-Only q_anchor. The
% blue/red rays are the +normal/-normal aiming targets. The labelled body5
% local Z axis is the exact axis constrained by constraintAiming in R2024a.

    qAnchorResult = solve_anchor_ik(robot, taskPlaneConfig, ikConfig);
    targetXYZ = reshape(taskPlaneConfig.robot_anchor_m, 1, 3);
    nPlane = derive_task_plane_normal(taskPlaneConfig)';
    endEffector = char(string(writingPostureConfig.end_effector));
    body5Pose = getTransform(robot, qAnchorResult.q, endEffector);

    figureHandle = figure( ...
        'Name', 'MonoTeach Stage 3.3 Writing Anchor Diagnostic', ...
        'Position', [100, 100, 1100, 800]);
    axesHandle = axes(figureHandle);
    plot_legacy_robot(robot, qAnchorResult.q, axesHandle);
    hold(axesHandle, 'on');

    corners = task_plane_corners_base_m(taskPlaneConfig);
    patch( ...
        axesHandle, ...
        corners(:, 1), corners(:, 2), corners(:, 3), ...
        [0.85, 0.40, 0.85], ...
        'FaceAlpha', 0.12, ...
        'EdgeColor', [0.55, 0.10, 0.55], ...
        'LineWidth', 1.5, ...
        'DisplayName', 'Task Plane');

    hAnchor = plot3( ...
        axesHandle, targetXYZ(1), targetXYZ(2), targetXYZ(3), ...
        'kp', 'MarkerSize', 12, 'LineWidth', 2, ...
        'DisplayName', 'robot anchor');
    hPlus = draw_ray(axesHandle, targetXYZ, nPlane, ...
        writingPostureConfig.aim_distance_m, [0.10, 0.40, 0.90], '+normal ray');
    hMinus = draw_ray(axesHandle, targetXYZ, -nPlane, ...
        writingPostureConfig.aim_distance_m, [0.85, 0.15, 0.15], '-normal ray');

    axisLength = 0.040;
    axisOrigin = body5Pose(1:3, 4)';
    hX = draw_ray(axesHandle, axisOrigin, body5Pose(1:3, 1)', ...
        axisLength, [0.90, 0.10, 0.10], 'body5 local X');
    hY = draw_ray(axesHandle, axisOrigin, body5Pose(1:3, 2)', ...
        axisLength, [0.10, 0.65, 0.10], 'body5 local Y');
    hZ = draw_ray(axesHandle, axisOrigin, body5Pose(1:3, 3)', ...
        axisLength, [0.10, 0.10, 0.10], ...
        'body5 local +Z (constraintAiming axis)');
    text( ...
        axesHandle, axisOrigin(1), axisOrigin(2), axisOrigin(3), ...
        '  body5 local +Z -> constraintAiming', ...
        'FontWeight', 'bold');

    axis(axesHandle, 'equal');
    grid(axesHandle, 'on');
    xlabel(axesHandle, 'Base X (m)');
    ylabel(axesHandle, 'Base Y (m)');
    zlabel(axesHandle, 'Base Z (m)');
    title(axesHandle, 'Stage 3.3 Anchor: body5 local axes vs Task Plane normals');
    legend(axesHandle, [hAnchor, hPlus, hMinus, hX, hY, hZ], ...
        'Location', 'best');
    view(axesHandle, 3);

    visualization = struct();
    visualization.figure = figureHandle;
    visualization.axes = axesHandle;
    visualization.q_anchor = qAnchorResult.q;
    visualization.anchor_xyz_m = targetXYZ;
    visualization.plane_normal_base = nPlane;
    visualization.body5_pose = body5Pose;
    visualization.body5_local_axes_base = body5Pose(1:3, 1:3);
end


function handle = draw_ray(axesHandle, origin, direction, lengthM, color, label)

    handle = quiver3( ...
        axesHandle, ...
        origin(1), origin(2), origin(3), ...
        lengthM * direction(1), ...
        lengthM * direction(2), ...
        lengthM * direction(3), ...
        0, ...
        'Color', color, ...
        'LineWidth', 2, ...
        'MaxHeadSize', 0.5, ...
        'DisplayName', label);
end


function cornersBaseM = task_plane_corners_base_m(config)

    halfWidthM = config.workspace_width_mm * config.scale / 2;
    halfHeightM = config.workspace_height_mm * config.scale / 2;
    cornersTaskPlaneM = [ ...
        -halfWidthM, -halfHeightM, 0; ...
         halfWidthM, -halfHeightM, 0; ...
         halfWidthM,  halfHeightM, 0; ...
        -halfWidthM,  halfHeightM, 0];
    R = config.T_base_taskplane(1:3, 1:3);
    origin = config.T_base_taskplane(1:3, 4)';
    cornersBaseM = (R * cornersTaskPlaneM' + origin')';
end
