function taskPlaneConfig = build_writing_candidate_task_plane_config( ...
        baselineTaskPlaneConfig, candidateConfig)
%BUILD_WRITING_CANDIDATE_TASK_PLANE_CONFIG Apply the Stage 3.3 candidate.
%
% The source Workspace contract stays 190-by-290 mm.  This only derives a
% temporary Task Plane config with the selected centre, vertical yaw, and
% uniform scale; default_task_plane_config.m is never modified.

    validate_inputs(baselineTaskPlaneConfig, candidateConfig);

    taskPlaneConfig = baselineTaskPlaneConfig;
    yawRad = deg2rad(candidateConfig.yaw_deg);
    RzBase = [ ...
        cos(yawRad), -sin(yawRad), 0; ...
        sin(yawRad),  cos(yawRad), 0; ...
        0,            0,           1];
    taskPlaneConfig.scale = candidateConfig.scale_m_per_mm;
    taskPlaneConfig.robot_anchor_m = candidateConfig.center_m;
    taskPlaneConfig.T_base_taskplane(1:3, 1:3) = ...
        RzBase * baselineTaskPlaneConfig.T_base_taskplane(1:3, 1:3);
    taskPlaneConfig.T_base_taskplane(1:3, 4) = candidateConfig.center_m';
end


function validate_inputs(baselineConfig, candidateConfig)

    requiredBaselineFields = { ...
        'workspace_width_mm', 'workspace_height_mm', 'scale', ...
        'robot_anchor_m', 'T_base_taskplane'};
    if ~isstruct(baselineConfig) || ~isscalar(baselineConfig) || ...
            ~all(isfield(baselineConfig, requiredBaselineFields)) || ...
            baselineConfig.workspace_width_mm ~= 190.0 || ...
            baselineConfig.workspace_height_mm ~= 290.0
        error( ...
            'MonoTeach:InvalidWritingCandidateBaseline', ...
            'Baseline must retain the 190-by-290 mm Stage 3.1 Workspace.');
    end

    requiredCandidateFields = { ...
        'center_m', 'yaw_deg', 'normal_sign', 'scale_m_per_mm', ...
        'source_workspace_width_mm', 'source_workspace_height_mm'};
    if ~isstruct(candidateConfig) || ~isscalar(candidateConfig) || ...
            ~all(isfield(candidateConfig, requiredCandidateFields)) || ...
            ~isequal(candidateConfig.center_m, [0.105, 0.060, 0.195]) || ...
            candidateConfig.yaw_deg ~= -60.0 || ...
            candidateConfig.normal_sign ~= +1 || ...
            candidateConfig.scale_m_per_mm ~= 0.00020 || ...
            candidateConfig.source_workspace_width_mm ~= 190.0 || ...
            candidateConfig.source_workspace_height_mm ~= 290.0
        error( ...
            'MonoTeach:InvalidWritingCandidate', ...
            ['Stage 3.3 Task 2 fixes the approved working candidate and ' ...
             'the unchanged 190-by-290 mm source Workspace.']);
    end
end
