function feasibility = evaluate_writing_anchor_feasibility( ...
        robot, taskPlaneConfig, ikConfig, writingPostureConfig)
%EVALUATE_WRITING_ANCHOR_FEASIBILITY Compare writing normals at one anchor.
%
% This Stage 3.3 Task 1 Step 2 helper evaluates only taskPlaneConfig's
% robot_anchor_m.  It deliberately does not accept a trajectory, create
% timing data, or choose writingPostureConfig.plane_normal_sign.
%
% Each candidate constrains body5 local +Z to aim from the anchor toward:
%   aimTarget = targetXYZ + aim_distance_m * signedNormal
% and independently back-checks position, tool direction, and joint limits.

    validate_inputs(robot, taskPlaneConfig, ikConfig, writingPostureConfig);

    endEffector = char(string(writingPostureConfig.end_effector));
    targetXYZ = reshape(taskPlaneConfig.robot_anchor_m, 1, 3);
    [nPlane, ~] = derive_task_plane_normal(taskPlaneConfig);
    nPlane = nPlane';
    candidateSigns = writingPostureConfig.candidate_plane_normal_signs;

    % Retain the frozen Stage 3.2 solver unchanged.  Its q_anchor is only a
    % deterministic reference/seed for this isolated posture experiment.
    positionOnlyAnchor = solve_anchor_ik(robot, taskPlaneConfig, ikConfig);
    jointLimits = five_joint_limits(robot);

    gik = generalizedInverseKinematics( ...
        'RigidBodyTree', robot, ...
        'ConstraintInputs', {'position', 'aiming'}, ...
        'SolverAlgorithm', writingPostureConfig.solver_algorithm);
    solverParameters = gik.SolverParameters;
    if ~isfield(solverParameters, 'AllowRandomRestart')
        error( ...
            'MonoTeach:UnsupportedGeneralizedInverseKinematicsAPI', ...
            'R2024a GIK SolverParameters must contain AllowRandomRestart.');
    end
    solverParameters.AllowRandomRestart = writingPostureConfig.allow_random_restart;
    gik.SolverParameters = solverParameters;

    candidates = repmat(empty_candidate(), 1, numel(candidateSigns));
    for candidateIndex = 1:numel(candidateSigns)
        signValue = candidateSigns(candidateIndex);
        signedNormal = signValue * nPlane;
        aimTarget = targetXYZ + ...
            writingPostureConfig.aim_distance_m * signedNormal;

        candidate = empty_candidate();
        candidate.sign = signValue;
        candidate.target_xyz_m = targetXYZ;
        candidate.signed_normal = signedNormal;
        candidate.aim_target_m = aimTarget;

        positionConstraint = constraintPositionTarget(endEffector);
        positionConstraint.TargetPosition = targetXYZ;
        positionConstraint.PositionTolerance = ...
            writingPostureConfig.position_tolerance_m;

        aimingConstraint = constraintAiming(endEffector);
        aimingConstraint.TargetPoint = aimTarget;
        aimingConstraint.AngularTolerance = ...
            writingPostureConfig.aiming_angular_tolerance_rad;

        try
            [q, solutionInfo] = gik( ...
                positionOnlyAnchor.q, ...
                positionConstraint, ...
                aimingConstraint);
            q = reshape(q, 1, []);
            candidate.q = q;
            candidate.solver_status = char(string(solutionInfo.Status));
            candidate.solution_info = solutionInfo;

            fkPose = getTransform(robot, q, endEffector);
            candidate.fk_xyz_m = fkPose(1:3, 4)';
            candidate.position_error_m = ...
                norm(candidate.fk_xyz_m - targetXYZ);
            candidate.fk_tool_z_direction = unit_vector(fkPose(1:3, 3)');
            candidate.tool_direction_error_rad = angle_between_unit_vectors( ...
                candidate.fk_tool_z_direction, ...
                signedNormal);
            candidate.tool_direction_error_deg = rad2deg( ...
                candidate.tool_direction_error_rad);
            [candidate.within_joint_limits, candidate.joint_limit_margin] = ...
                joint_limit_evidence(q, jointLimits);
            candidate.distance_to_position_only_q_anchor = ...
                norm(q - positionOnlyAnchor.q);
            candidate.within_position_tolerance = ...
                candidate.position_error_m <= ...
                writingPostureConfig.position_tolerance_m;
            candidate.within_aiming_tolerance = ...
                candidate.tool_direction_error_rad <= ...
                writingPostureConfig.aiming_angular_tolerance_rad;
            candidate.solver_status_is_success = ...
                strcmpi(candidate.solver_status, 'success');
            candidate.accepted = candidate.solver_status_is_success && ...
                candidate.within_position_tolerance && ...
                candidate.within_aiming_tolerance && ...
                candidate.within_joint_limits;

            if ~candidate.accepted
                candidate.failure_reason = 'solver_or_backcheck_not_accepted';
            end
        catch exception
            % Keep the candidate's geometry and an explicit failure record;
            % a failed sign must not disappear from the comparison.
            candidate.solver_status = ['exception:' exception.identifier];
            candidate.failure_reason = exception.message;
        end

        candidates(candidateIndex) = candidate;
    end

    feasibility = struct();
    feasibility.target_xyz_m = targetXYZ;
    feasibility.plane_normal_base = nPlane;
    feasibility.position_only_anchor = positionOnlyAnchor;
    feasibility.candidates = candidates;
end


function candidate = empty_candidate()

    candidate = struct( ...
        'sign', NaN, ...
        'target_xyz_m', NaN(1, 3), ...
        'signed_normal', NaN(1, 3), ...
        'aim_target_m', NaN(1, 3), ...
        'q', [], ...
        'solver_status', '', ...
        'solution_info', struct(), ...
        'fk_xyz_m', NaN(1, 3), ...
        'position_error_m', NaN, ...
        'fk_tool_z_direction', NaN(1, 3), ...
        'tool_direction_error_rad', NaN, ...
        'tool_direction_error_deg', NaN, ...
        'within_joint_limits', false, ...
        'joint_limit_margin', NaN(1, 5), ...
        'distance_to_position_only_q_anchor', NaN, ...
        'within_position_tolerance', false, ...
        'within_aiming_tolerance', false, ...
        'solver_status_is_success', false, ...
        'accepted', false, ...
        'failure_reason', '');
end


function validate_inputs(robot, taskPlaneConfig, ikConfig, writingPostureConfig)

    if ~isa(robot, 'rigidBodyTree') || ~strcmp(robot.DataFormat, 'row')
        error( ...
            'MonoTeach:InvalidWritingFeasibilityRobot', ...
            'robot must be a rigidBodyTree with DataFormat set to row.');
    end

    if ~isstruct(taskPlaneConfig) || ~isscalar(taskPlaneConfig) || ...
            ~isfield(taskPlaneConfig, 'robot_anchor_m')
        error( ...
            'MonoTeach:InvalidWritingFeasibilityTaskPlane', ...
            'taskPlaneConfig must contain robot_anchor_m.');
    end
    require_finite_row_vector( ...
        taskPlaneConfig.robot_anchor_m, 3, 'taskPlaneConfig.robot_anchor_m');

    if ~isstruct(ikConfig) || ~isscalar(ikConfig)
        error( ...
            'MonoTeach:InvalidWritingFeasibilityIKConfig', ...
            'ikConfig must be one scalar config struct.');
    end

    if ~isstruct(writingPostureConfig) || ~isscalar(writingPostureConfig)
        error( ...
            'MonoTeach:InvalidWritingPostureConfig', ...
            'writingPostureConfig must be one scalar config struct.');
    end

    requiredFields = { ...
        'end_effector', ...
        'tool_axis', ...
        'candidate_plane_normal_signs', ...
        'aim_distance_m', ...
        'position_tolerance_m', ...
        'aiming_angular_tolerance_rad', ...
        'solver_algorithm', ...
        'allow_random_restart'};
    missingFields = requiredFields(~isfield( ...
        writingPostureConfig, requiredFields));
    if ~isempty(missingFields)
        error( ...
            'MonoTeach:MissingWritingPostureConfigField', ...
            'writingPostureConfig is missing required fields: %s.', ...
            strjoin(missingFields, ', '));
    end

    if ~strcmp(string(writingPostureConfig.end_effector), "body5") || ...
            ~strcmp(string(writingPostureConfig.tool_axis), "z")
        error( ...
            'MonoTeach:UnsupportedWritingToolGeometry', ...
            'This experiment requires body5 local +Z as the tool axis.');
    end

    candidateSigns = writingPostureConfig.candidate_plane_normal_signs;
    if ~isnumeric(candidateSigns) || ~isreal(candidateSigns) || ...
            ~isequal(candidateSigns, [+1, -1])
        error( ...
            'MonoTeach:InvalidWritingNormalCandidates', ...
            'candidate_plane_normal_signs must be [+1, -1].');
    end

    require_positive_scalar( ...
        writingPostureConfig.aim_distance_m, 'aim_distance_m');
    require_positive_scalar( ...
        writingPostureConfig.position_tolerance_m, 'position_tolerance_m');
    require_positive_scalar( ...
        writingPostureConfig.aiming_angular_tolerance_rad, ...
        'aiming_angular_tolerance_rad');

    if ~strcmp(string(writingPostureConfig.solver_algorithm), ...
            "BFGSGradientProjection")
        error( ...
            'MonoTeach:InvalidWritingFeasibilitySolver', ...
            'This R2024a experiment requires BFGSGradientProjection.');
    end

    if ~islogical(writingPostureConfig.allow_random_restart) || ...
            ~isscalar(writingPostureConfig.allow_random_restart)
        error( ...
            'MonoTeach:InvalidWritingFeasibilityRestartPolicy', ...
            'allow_random_restart must be one logical scalar.');
    end
end


function limits = five_joint_limits(robot)

    limits = zeros(robot.NumBodies, 2);
    for bodyIndex = 1:robot.NumBodies
        limits(bodyIndex, :) = robot.Bodies{bodyIndex}.Joint.PositionLimits;
    end
end


function [withinLimits, margin] = joint_limit_evidence(q, limits)

    margin = min(q - limits(:, 1)', limits(:, 2)' - q);
    comparisonTolerance = 1.0e-12;
    withinLimits = all( ...
        q >= limits(:, 1)' - comparisonTolerance & ...
        q <= limits(:, 2)' + comparisonTolerance);
end


function unitVector = unit_vector(vector)

    magnitude = norm(vector);
    if ~isfinite(magnitude) || magnitude <= eps
        error( ...
            'MonoTeach:DegenerateToolDirection', ...
            'FK tool-Z direction must have nonzero finite length.');
    end

    unitVector = vector / magnitude;
end


function angleRad = angle_between_unit_vectors(first, second)

    boundedDotProduct = max(-1.0, min(1.0, dot(first, second)));
    angleRad = acos(boundedDotProduct);
end


function require_finite_row_vector(value, expectedLength, context)

    if ~isnumeric(value) || ~isreal(value) || ...
            ~isequal(size(value), [1, expectedLength]) || ...
            any(~isfinite(value), 'all')
        error( ...
            'MonoTeach:InvalidWritingFeasibilityInput', ...
            '%s must be one finite 1-by-%d numeric vector.', ...
            context, ...
            expectedLength);
    end
end


function require_positive_scalar(value, context)

    if ~isnumeric(value) || ~isscalar(value) || ~isreal(value) || ...
            ~isfinite(value) || value <= 0
        error( ...
            'MonoTeach:InvalidWritingFeasibilityInput', ...
            '%s must be one positive finite scalar.', context);
    end
end
