function scan = scan_writing_full_task_plane( ...
        robot, taskPlaneConfig, ikConfig, writingPostureConfig, scanConfig)
%SCAN_WRITING_FULL_TASK_PLANE Independently test writing feasibility on a grid.
%
% The temporary candidate is [0.105, 0.060, 0.195] m, yaw=-60 deg, +normal.
% Workspace samples are mapped by workspace_to_task_trajectory, preserving the
% established Stage 3.1 workspace-mm -> centred-task-plane -> base-m contract.
% Each grid point has an independent deterministic seed set; no previous-grid
% configuration is used as a seed.

    if nargin < 5 || isempty(scanConfig)
        scanConfig = default_writing_full_plane_scan_config();
    end
    validate_inputs(robot, taskPlaneConfig, writingPostureConfig, scanConfig);

    baselineTaskPlaneConfig = taskPlaneConfig;
    candidateTaskPlaneConfig = candidate_task_plane_config( ...
        baselineTaskPlaneConfig, scanConfig);
    workspaceTrajectory = make_workspace_grid_trajectory( ...
        scanConfig, candidateTaskPlaneConfig);
    taskTrajectory = workspace_to_task_trajectory( ...
        workspaceTrajectory, candidateTaskPlaneConfig);
    validate_mapping_geometry( ...
        candidateTaskPlaneConfig, taskTrajectory, scanConfig);

    diagnosticConfig = default_writing_anchor_diagnostic_config();
    diagnosticConfig.random_seed = scanConfig.random_seed;
    diagnosticConfig.random_seed_count = scanConfig.random_seed_count;
    diagnosticConfig.solver_algorithms = {scanConfig.solver_algorithm};
    diagnosticConfig.allow_random_restart = scanConfig.allow_random_restart;

    writingConfig = writingPostureConfig;
    writingConfig.candidate_plane_normal_signs = scanConfig.normal_sign;
    centerDiagnostic = diagnose_writing_anchor_multistart( ...
        robot, candidateTaskPlaneConfig, ikConfig, ...
        writingConfig, diagnosticConfig);
    centerRun = centerDiagnostic.runs(1);
    [centerQ, centerSeedProvenance] = accepted_center_writing_q( ...
        robot, centerRun);

    pointIndices = traversal_indices( ...
        scanConfig.workspace_x_values_mm, ...
        scanConfig.workspace_y_values_mm, ...
        scanConfig.traversal_order);
    records = repmat(empty_record(), 1, numel(pointIndices));
    for recordIndex = 1:numel(pointIndices)
        sourceIndex = pointIndices(recordIndex);
        workspaceSample = workspaceTrajectory.samples(sourceIndex);
        taskSample = taskTrajectory.samples(sourceIndex);
        targetXYZ = [taskSample.x_m, taskSample.y_m, taskSample.z_m];
        perPointTaskPlaneConfig = candidateTaskPlaneConfig;
        perPointTaskPlaneConfig.robot_anchor_m = targetXYZ;

        % The centre writing q, each point's position-only q, home, and the
        % fixed random sample are all present independently at every point.
        % No prior grid-point state enters this configuration.
        perPointDiagnosticConfig = diagnosticConfig;
        perPointDiagnosticConfig.additional_seed_set = struct( ...
            'name', 'accepted_center_writing_q', ...
            'initial_q', centerQ);
        diagnostic = diagnose_writing_anchor_multistart( ...
            robot, perPointTaskPlaneConfig, ikConfig, ...
            writingConfig, perPointDiagnosticConfig);
        run = diagnostic.runs(1);

        records(recordIndex) = make_record( ...
            workspaceSample, taskSample, candidateTaskPlaneConfig, ...
            perPointTaskPlaneConfig, run);
    end

    scan = struct();
    scan.input_task_plane_config = baselineTaskPlaneConfig;
    scan.candidate_task_plane_config = candidateTaskPlaneConfig;
    scan.scan_config = scanConfig;
    scan.plane_normal_base = derive_task_plane_normal(candidateTaskPlaneConfig)';
    scan.center_writing_q = centerQ;
    scan.center_writing_seed_provenance = centerSeedProvenance;
    scan.workspace_trajectory = workspaceTrajectory;
    scan.task_trajectory = taskTrajectory;
    scan.records = records;
    scan.summary = summarize_scan(records, candidateTaskPlaneConfig, scanConfig);
end


function config = candidate_task_plane_config(baselineConfig, scanConfig)

    yawRad = deg2rad(scanConfig.candidate_yaw_deg);
    RzBase = [ ...
        cos(yawRad), -sin(yawRad), 0; ...
        sin(yawRad),  cos(yawRad), 0; ...
        0,            0,           1];
    config = baselineConfig;
    config.robot_anchor_m = scanConfig.candidate_center_m;
    config.T_base_taskplane(1:3, 1:3) = ...
        RzBase * baselineConfig.T_base_taskplane(1:3, 1:3);
    config.T_base_taskplane(1:3, 4) = scanConfig.candidate_center_m';
end


function trajectory = make_workspace_grid_trajectory(scanConfig, taskPlaneConfig)

    [workspaceX, workspaceY] = meshgrid( ...
        scanConfig.workspace_x_values_mm, ...
        scanConfig.workspace_y_values_mm);
    pointCount = numel(workspaceX);
    samples = repmat(empty_workspace_sample(), 1, pointCount);
    for pointIndex = 1:pointCount
        samples(pointIndex).t_ms = pointIndex - 1;
        samples(pointIndex).valid = true;
        samples(pointIndex).x_mm = workspaceX(pointIndex);
        samples(pointIndex).y_mm = workspaceY(pointIndex);
        samples(pointIndex).inside_workspace = true;
        samples(pointIndex).invalid_reason = '';
    end

    trajectory = struct();
    trajectory.schema_version = '1.0';
    trajectory.metadata = struct( ...
        'source_trajectory_id', 'stage3_3_full_plane_grid', ...
        'workspace_calibration_id', 'stage3_3_temporary_scan_candidate', ...
        'coordinate_frame', 'workspace_2d', ...
        'width_mm', taskPlaneConfig.workspace_width_mm, ...
        'height_mm', taskPlaneConfig.workspace_height_mm);
    trajectory.samples = samples;
end


function sample = empty_workspace_sample()

    sample = struct( ...
        't_ms', [], ...
        'valid', [], ...
        'x_mm', [], ...
        'y_mm', [], ...
        'inside_workspace', [], ...
        'invalid_reason', []);
end


function validate_mapping_geometry(candidateConfig, taskTrajectory, scanConfig)

    if ~strcmp(string(taskTrajectory.coordinate_frame), "robot_base") || ...
            numel(taskTrajectory.samples) ~= ...
                numel(scanConfig.workspace_x_values_mm) * ...
                numel(scanConfig.workspace_y_values_mm)
        error( ...
            'MonoTeach:InvalidFullPlaneTaskMapping', ...
            'The full-plane grid must use a complete robot-base TaskTrajectory.');
    end

    R = candidateConfig.T_base_taskplane(1:3, 1:3);
    nPlane = derive_task_plane_normal(candidateConfig);
    tolerance = 1.0e-12;
    if norm(R' * R - eye(3), 'fro') > tolerance || ...
            abs(det(R) - 1.0) > tolerance || ...
            norm(R(:, 2) - [0; 0; -1]) > tolerance || ...
            abs(nPlane(3)) > tolerance
        error( ...
            'MonoTeach:InvalidFullPlaneCandidateGeometry', ...
            'Temporary candidate must retain a proper vertical Task Plane.');
    end
end


function [q, seedProvenance] = accepted_center_writing_q(robot, run)

    acceptedTrialIndex = find([run.trials.accepted], 1, 'first');
    if isempty(acceptedTrialIndex)
        error( ...
            'MonoTeach:FullPlaneCenterWritingNotAccepted', ...
            ['The Step 8 candidate centre must retain a formally accepted ' ...
             'writing solution before it can seed independent grid points.']);
    end
    q = run.trials(acceptedTrialIndex).candidate_q;
    if ~is_limit_valid_configuration(robot, q)
        error( ...
            'MonoTeach:InvalidFullPlaneCenterWritingSeed', ...
            'The accepted centre writing configuration must be limit-valid.');
    end
    seedProvenance = run.trials(acceptedTrialIndex).seed_name;
end


function pointIndices = traversal_indices(xValues, yValues, traversalOrder)

    % meshgrid(xValues, yValues) has y as the row dimension and x as the
    % column dimension.  This index grid therefore refers directly to the
    % Stage 3.1-mapped TaskTrajectory samples.
    pointIndices = reshape(1:(numel(xValues) * numel(yValues)), ...
        numel(yValues), numel(xValues));
    switch char(string(traversalOrder))
        case 'workspace_x_then_y'
            pointIndices = pointIndices(:)';
        case 'workspace_y_then_x'
            pointIndices = pointIndices';
            pointIndices = pointIndices(:)';
        otherwise
            error( ...
                'MonoTeach:InvalidFullPlaneTraversalOrder', ...
                'traversal_order must be workspace_x_then_y or workspace_y_then_x.');
    end
end


function record = make_record( ...
        workspaceSample, taskSample, candidateTaskPlaneConfig, ...
        pointTaskPlaneConfig, run)

    if run.accepted_count > 0
        selectedTrialIndex = find([run.trials.accepted], 1, 'first');
        selectionReason = 'first_formally_accepted_trial';
    else
        selectedTrialIndex = run.best_combined_trial_index;
        selectionReason = 'closest_combined_nonaccepted_trial';
    end
    selectedTrial = run.trials(selectedTrialIndex);
    baseXYZ = [taskSample.x_m, taskSample.y_m, taskSample.z_m];
    taskPointH = candidateTaskPlaneConfig.T_base_taskplane \ [baseXYZ, 1.0]';

    record = empty_record();
    record.workspace_x_mm = workspaceSample.x_mm;
    record.workspace_y_mm = workspaceSample.y_mm;
    record.task_plane_xyz_m = taskPointH(1:3)';
    record.base_xyz_m = baseXYZ;
    record.accepted = run.has_formally_accepted_solution;
    record.accepted_count = run.accepted_count;
    record.normal_sign = run.sign;
    record.candidate_q = selectedTrial.candidate_q;
    record.position_error_m = selectedTrial.position_error_m;
    record.direction_error_rad = selectedTrial.tool_direction_error_rad;
    record.direction_error_deg = selectedTrial.tool_direction_error_deg;
    record.within_joint_limits = selectedTrial.within_joint_limits;
    record.minimum_joint_limit_margin = min(selectedTrial.joint_limit_margin);
    record.solver_status = selectedTrial.solver_status;
    record.seed_provenance = selectedTrial.seed_name;
    record.solver_algorithm = run.solver_algorithm;
    record.selection_reason = selectionReason;
    record.task_plane_config = pointTaskPlaneConfig;
    record.trials = run.trials;
end


function record = empty_record()

    record = struct( ...
        'workspace_x_mm', NaN, ...
        'workspace_y_mm', NaN, ...
        'task_plane_xyz_m', NaN(1, 3), ...
        'base_xyz_m', NaN(1, 3), ...
        'accepted', false, ...
        'accepted_count', 0, ...
        'normal_sign', NaN, ...
        'candidate_q', [], ...
        'position_error_m', NaN, ...
        'direction_error_rad', NaN, ...
        'direction_error_deg', NaN, ...
        'within_joint_limits', false, ...
        'minimum_joint_limit_margin', NaN, ...
        'solver_status', '', ...
        'seed_provenance', '', ...
        'solver_algorithm', '', ...
        'selection_reason', '', ...
        'task_plane_config', struct(), ...
        'trials', struct([]));
end


function summary = summarize_scan(records, candidateConfig, scanConfig)

    acceptedMask = [records.accepted];
    acceptedRecords = records(acceptedMask);
    edgeMask = [records.workspace_x_mm] == 0.0 | ...
        [records.workspace_x_mm] == candidateConfig.workspace_width_mm | ...
        [records.workspace_y_mm] == 0.0 | ...
        [records.workspace_y_mm] == candidateConfig.workspace_height_mm;
    edgeRecords = records(edgeMask);
    cornerMask = ( ...
        [records.workspace_x_mm] == 0.0 | ...
        [records.workspace_x_mm] == candidateConfig.workspace_width_mm) & ...
        ( ...
        [records.workspace_y_mm] == 0.0 | ...
        [records.workspace_y_mm] == candidateConfig.workspace_height_mm);

    summary = struct();
    summary.total_count = numel(records);
    summary.accepted_count = sum(acceptedMask);
    summary.coverage_percent = 100.0 * summary.accepted_count / summary.total_count;
    summary.corner_records = records(cornerMask);
    summary.edge_total_count = numel(edgeRecords);
    summary.edge_accepted_count = sum([edgeRecords.accepted]);
    summary.edge_coverage_percent = ...
        100.0 * summary.edge_accepted_count / summary.edge_total_count;
    summary.failed_records = records(~acceptedMask);
    summary.candidate_center_m = scanConfig.candidate_center_m;
    if isempty(acceptedRecords)
        summary.minimum_accepted_joint_margin = NaN;
        summary.worst_accepted_direction_error_deg = NaN;
    else
        summary.minimum_accepted_joint_margin = ...
            min([acceptedRecords.minimum_joint_limit_margin]);
        summary.worst_accepted_direction_error_deg = ...
            max([acceptedRecords.direction_error_deg]);
    end
end


function isValid = is_limit_valid_configuration(robot, q)

    if ~isnumeric(q) || ~isreal(q) || ...
            ~isequal(size(q), [1, robot.NumBodies]) || any(~isfinite(q))
        isValid = false;
        return;
    end
    limits = zeros(robot.NumBodies, 2);
    for bodyIndex = 1:robot.NumBodies
        limits(bodyIndex, :) = robot.Bodies{bodyIndex}.Joint.PositionLimits;
    end
    isValid = all(q >= limits(:, 1)' & q <= limits(:, 2)');
end


function validate_inputs(robot, taskPlaneConfig, writingPostureConfig, scanConfig)

    if ~isa(robot, 'rigidBodyTree') || ~strcmp(robot.DataFormat, 'row') || ...
            robot.NumBodies ~= 5
        error( ...
            'MonoTeach:InvalidFullPlaneScanRobot', ...
            'robot must be the row-format Legacy 5DOF rigidBodyTree.');
    end

    requiredTaskPlaneFields = { ...
        'workspace_width_mm', 'workspace_height_mm', 'workspace_center_mm', ...
        'scale', 'robot_anchor_m', 'T_base_taskplane'};
    if ~isstruct(taskPlaneConfig) || ~isscalar(taskPlaneConfig) || ...
            ~all(isfield(taskPlaneConfig, requiredTaskPlaneFields))
        error( ...
            'MonoTeach:InvalidFullPlaneScanTaskPlane', ...
            'taskPlaneConfig is missing the Stage 3.1 mapping fields.');
    end

    if ~isstruct(writingPostureConfig) || ...
            ~isequal(writingPostureConfig.candidate_plane_normal_signs, [+1, -1])
        error( ...
            'MonoTeach:InvalidFullPlaneScanPosture', ...
            'writingPostureConfig must retain unresolved +/- candidates.');
    end

    requiredScanFields = { ...
        'workspace_x_values_mm', 'workspace_y_values_mm', ...
        'traversal_order', 'candidate_center_m', 'candidate_yaw_deg', ...
        'normal_sign', 'random_seed', 'random_seed_count', ...
        'solver_algorithm', 'allow_random_restart'};
    if ~isstruct(scanConfig) || ~isscalar(scanConfig) || ...
            ~all(isfield(scanConfig, requiredScanFields))
        error( ...
            'MonoTeach:InvalidFullPlaneScanConfig', ...
            'scanConfig is missing required fields.');
    end

    require_workspace_grid( ...
        scanConfig.workspace_x_values_mm, taskPlaneConfig.workspace_width_mm, ...
        taskPlaneConfig.workspace_center_mm(1), 'workspace_x_values_mm');
    require_workspace_grid( ...
        scanConfig.workspace_y_values_mm, taskPlaneConfig.workspace_height_mm, ...
        taskPlaneConfig.workspace_center_mm(2), 'workspace_y_values_mm');
    if ~isnumeric(scanConfig.candidate_center_m) || ...
            ~isequal(size(scanConfig.candidate_center_m), [1, 3]) || ...
            any(~isfinite(scanConfig.candidate_center_m)) || ...
            ~isequal(scanConfig.candidate_center_m, [0.105, 0.060, 0.195]) || ...
            scanConfig.candidate_yaw_deg ~= -60.0 || ...
            scanConfig.normal_sign ~= +1
        error( ...
            'MonoTeach:InvalidFullPlaneTemporaryCandidate', ...
            'Step 8 requires [0.105 0.060 0.195] m, yaw=-60 deg, +normal.');
    end

    validTraversalOrder = ismember(string(scanConfig.traversal_order), ...
        ["workspace_x_then_y", "workspace_y_then_x"]);
    if ~validTraversalOrder || ...
            ~strcmp(string(scanConfig.solver_algorithm), ...
                "BFGSGradientProjection") || ...
            ~islogical(scanConfig.allow_random_restart) || ...
            ~isscalar(scanConfig.allow_random_restart) || ...
            scanConfig.allow_random_restart
        error( ...
            'MonoTeach:InvalidFullPlaneScanPolicy', ...
            ['Full-plane scan must use a supported independent traversal, ' ...
             'BFGSGradientProjection, and AllowRandomRestart=false.']);
    end
end


function require_workspace_grid(values, extentMM, centerMM, fieldName)

    if ~isnumeric(values) || ~isreal(values) || ~isrow(values) || ...
            isempty(values) || any(~isfinite(values)) || ...
            any(diff(values) <= 0) || values(1) ~= 0.0 || ...
            values(end) ~= extentMM || ...
            ~any(abs(values - centerMM) <= 1.0e-12)
        error( ...
            'MonoTeach:InvalidFullPlaneWorkspaceGrid', ...
            '%s must include both boundaries and workspace centre.', fieldName);
    end
end
