function sweep = sweep_writing_task_plane_scale( ...
        robot, taskPlaneConfig, ikConfig, writingPostureConfig, sweepConfig)
%SWEEP_WRITING_TASK_PLANE_SCALE Find largest sampled-full-coverage scale.
%
% This scans uniform workspace-to-robot scales with the Step 8 placement
% fixed.  Each scale calls the independent-seed full-plane point scanner.
% If any coarse 5-by-7 grid has 100 percent coverage, that largest scale and
% its immediate coarse neighbours are then checked on the 9-by-13 grid.

    if nargin < 5 || isempty(sweepConfig)
        sweepConfig = default_writing_scale_sweep_config();
    end
    validate_inputs(robot, taskPlaneConfig, writingPostureConfig, sweepConfig);

    baselineTaskPlaneConfig = taskPlaneConfig;
    coarseRecords = repmat(empty_scale_record(), 1, ...
        numel(sweepConfig.scale_values_m_per_mm));
    for scaleIndex = 1:numel(sweepConfig.scale_values_m_per_mm)
        scaleMPerMM = sweepConfig.scale_values_m_per_mm(scaleIndex);
        coarseRecords(scaleIndex) = scan_one_scale( ...
            robot, baselineTaskPlaneConfig, ikConfig, writingPostureConfig, ...
            sweepConfig, scaleMPerMM, ...
            sweepConfig.coarse_workspace_x_values_mm, ...
            sweepConfig.coarse_workspace_y_values_mm, ...
            'coarse_5_by_7');
    end

    fullCoverageMask = [coarseRecords.coverage_percent] == 100.0;
    largestCoarseFullCoverageScale = NaN;
    verificationRecords = repmat(empty_scale_record(), 1, 0);
    if any(fullCoverageMask)
        largestIndex = find(fullCoverageMask, 1, 'last');
        largestCoarseFullCoverageScale = ...
            coarseRecords(largestIndex).scale_m_per_mm;
        verificationIndices = unique( ...
            max(1, largestIndex - 1):min(numel(coarseRecords), largestIndex + 1));
        verificationRecords = repmat(empty_scale_record(), 1, ...
            numel(verificationIndices));
        for verificationIndex = 1:numel(verificationIndices)
            sourceIndex = verificationIndices(verificationIndex);
            verificationRecords(verificationIndex) = scan_one_scale( ...
                robot, baselineTaskPlaneConfig, ikConfig, writingPostureConfig, ...
                sweepConfig, ...
                coarseRecords(sourceIndex).scale_m_per_mm, ...
                sweepConfig.verification_workspace_x_values_mm, ...
                sweepConfig.verification_workspace_y_values_mm, ...
                'verification_9_by_13');
        end
    end

    sweep = struct();
    sweep.input_task_plane_config = baselineTaskPlaneConfig;
    sweep.sweep_config = sweepConfig;
    sweep.coarse_records = coarseRecords;
    sweep.largest_coarse_full_coverage_scale_m_per_mm = ...
        largestCoarseFullCoverageScale;
    sweep.verification_records = verificationRecords;
    if isempty(verificationRecords)
        sweep.largest_verified_full_coverage_scale_m_per_mm = NaN;
    else
        verifiedMask = [verificationRecords.coverage_percent] == 100.0;
        verifiedScales = [verificationRecords(verifiedMask).scale_m_per_mm];
        if isempty(verifiedScales)
            sweep.largest_verified_full_coverage_scale_m_per_mm = NaN;
        else
            sweep.largest_verified_full_coverage_scale_m_per_mm = ...
                max(verifiedScales);
        end
    end
end


function record = scan_one_scale( ...
        robot, baselineConfig, ikConfig, writingPostureConfig, sweepConfig, ...
        scaleMPerMM, workspaceXValuesMM, workspaceYValuesMM, stage)

    scaledTaskPlaneConfig = baselineConfig;
    scaledTaskPlaneConfig.scale = scaleMPerMM;
    scanConfig = default_writing_full_plane_scan_config();
    scanConfig.workspace_x_values_mm = workspaceXValuesMM;
    scanConfig.workspace_y_values_mm = workspaceYValuesMM;
    scanConfig.traversal_order = sweepConfig.traversal_order;
    scanConfig.candidate_center_m = sweepConfig.candidate_center_m;
    scanConfig.candidate_yaw_deg = sweepConfig.candidate_yaw_deg;
    scanConfig.normal_sign = sweepConfig.normal_sign;
    scanConfig.random_seed = sweepConfig.random_seed;
    scanConfig.random_seed_count = sweepConfig.random_seed_count;
    scanConfig.solver_algorithm = sweepConfig.solver_algorithm;
    scanConfig.allow_random_restart = sweepConfig.allow_random_restart;
    scan = scan_writing_full_task_plane( ...
        robot, scaledTaskPlaneConfig, ikConfig, ...
        writingPostureConfig, scanConfig);

    record = empty_scale_record();
    record.stage = stage;
    record.scale_m_per_mm = scaleMPerMM;
    record.robot_physical_width_m = ...
        scaledTaskPlaneConfig.workspace_width_mm * scaleMPerMM;
    record.robot_physical_height_m = ...
        scaledTaskPlaneConfig.workspace_height_mm * scaleMPerMM;
    record.accepted_count = scan.summary.accepted_count;
    record.total_count = scan.summary.total_count;
    record.coverage_percent = scan.summary.coverage_percent;
    record.corner_pass_count = sum([scan.summary.corner_records.accepted]);
    record.corner_total_count = numel(scan.summary.corner_records);
    record.edge_accepted_count = scan.summary.edge_accepted_count;
    record.edge_total_count = scan.summary.edge_total_count;
    record.edge_coverage_percent = scan.summary.edge_coverage_percent;
    record.minimum_accepted_joint_margin = ...
        scan.summary.minimum_accepted_joint_margin;
    record.worst_accepted_direction_error_deg = ...
        scan.summary.worst_accepted_direction_error_deg;
    acceptedRecords = scan.records([scan.records.accepted]);
    if isempty(acceptedRecords)
        record.worst_accepted_position_error_m = NaN;
    else
        record.worst_accepted_position_error_m = ...
            max([acceptedRecords.position_error_m]);
    end
    record.failed_workspace_points_mm = [[scan.summary.failed_records.workspace_x_mm]', ...
        [scan.summary.failed_records.workspace_y_mm]'];
    record.scan = scan;
end


function record = empty_scale_record()

    record = struct( ...
        'stage', '', ...
        'scale_m_per_mm', NaN, ...
        'robot_physical_width_m', NaN, ...
        'robot_physical_height_m', NaN, ...
        'accepted_count', 0, ...
        'total_count', 0, ...
        'coverage_percent', NaN, ...
        'corner_pass_count', 0, ...
        'corner_total_count', 0, ...
        'edge_accepted_count', 0, ...
        'edge_total_count', 0, ...
        'edge_coverage_percent', NaN, ...
        'minimum_accepted_joint_margin', NaN, ...
        'worst_accepted_direction_error_deg', NaN, ...
        'worst_accepted_position_error_m', NaN, ...
        'failed_workspace_points_mm', NaN(0, 2), ...
        'scan', struct());
end


function validate_inputs(robot, taskPlaneConfig, writingPostureConfig, sweepConfig)

    if ~isa(robot, 'rigidBodyTree') || ~strcmp(robot.DataFormat, 'row') || ...
            robot.NumBodies ~= 5
        error( ...
            'MonoTeach:InvalidWritingScaleSweepRobot', ...
            'robot must be the row-format Legacy 5DOF rigidBodyTree.');
    end

    if ~isstruct(taskPlaneConfig) || ~isscalar(taskPlaneConfig) || ...
            taskPlaneConfig.workspace_width_mm ~= 190.0 || ...
            taskPlaneConfig.workspace_height_mm ~= 290.0
        error( ...
            'MonoTeach:InvalidWritingScaleSweepWorkspace', ...
            'Step 9 keeps the 190-by-290 mm source Workspace unchanged.');
    end

    if ~isstruct(writingPostureConfig) || ...
            ~isequal(writingPostureConfig.candidate_plane_normal_signs, [+1, -1])
        error( ...
            'MonoTeach:InvalidWritingScaleSweepPosture', ...
            'writingPostureConfig must retain unresolved +/- candidates.');
    end

    requiredFields = { ...
        'scale_values_m_per_mm', ...
        'coarse_workspace_x_values_mm', ...
        'coarse_workspace_y_values_mm', ...
        'verification_workspace_x_values_mm', ...
        'verification_workspace_y_values_mm', ...
        'candidate_center_m', ...
        'candidate_yaw_deg', ...
        'normal_sign', ...
        'traversal_order', ...
        'random_seed', ...
        'random_seed_count', ...
        'solver_algorithm', ...
        'allow_random_restart'};
    if ~isstruct(sweepConfig) || ~isscalar(sweepConfig) || ...
            ~all(isfield(sweepConfig, requiredFields))
        error( ...
            'MonoTeach:InvalidWritingScaleSweepConfig', ...
            'sweepConfig is missing required fields.');
    end

    expectedScales = [ ...
        0.00010, 0.00015, 0.00020, 0.00025, 0.00030, ...
        0.00035, 0.00040, 0.00045, 0.00050];
    require_increasing_positive_row( ...
        sweepConfig.scale_values_m_per_mm, 'scale_values_m_per_mm');
    if any(~ismember(sweepConfig.scale_values_m_per_mm, expectedScales))
        error( ...
            'MonoTeach:InvalidWritingScaleSweepCandidates', ...
            'Scale sweep values must be selected from the Step 9 coarse list.');
    end
    require_workspace_grid( ...
        sweepConfig.coarse_workspace_x_values_mm, 190.0, 95.0, ...
        'coarse_workspace_x_values_mm');
    require_workspace_grid( ...
        sweepConfig.coarse_workspace_y_values_mm, 290.0, 145.0, ...
        'coarse_workspace_y_values_mm');
    require_workspace_grid( ...
        sweepConfig.verification_workspace_x_values_mm, 190.0, 95.0, ...
        'verification_workspace_x_values_mm');
    require_workspace_grid( ...
        sweepConfig.verification_workspace_y_values_mm, 290.0, 145.0, ...
        'verification_workspace_y_values_mm');

    if ~isequal(sweepConfig.candidate_center_m, [0.105, 0.060, 0.195]) || ...
            sweepConfig.candidate_yaw_deg ~= -60.0 || ...
            sweepConfig.normal_sign ~= +1 || ...
            ~ismember(string(sweepConfig.traversal_order), ...
                ["workspace_x_then_y", "workspace_y_then_x"]) || ...
            ~strcmp(string(sweepConfig.solver_algorithm), ...
                "BFGSGradientProjection") || ...
            ~islogical(sweepConfig.allow_random_restart) || ...
            ~isscalar(sweepConfig.allow_random_restart) || ...
            sweepConfig.allow_random_restart
        error( ...
            'MonoTeach:InvalidWritingScaleSweepCandidate', ...
            ['Scale sweep fixes the Step 8 placement, +normal, and ' ...
             'deterministic BFGS baseline.']);
    end
end


function require_increasing_positive_row(values, fieldName)

    if ~isnumeric(values) || ~isreal(values) || ~isrow(values) || ...
            isempty(values) || any(~isfinite(values)) || any(values <= 0) || ...
            any(diff(values) <= 0)
        error( ...
            'MonoTeach:InvalidWritingScaleSweepValues', ...
            '%s must be an increasing positive finite numeric row.', fieldName);
    end
end


function require_workspace_grid(values, extentMM, centerMM, fieldName)

    if ~isnumeric(values) || ~isreal(values) || ~isrow(values) || ...
            numel(values) < 3 || any(~isfinite(values)) || ...
            any(diff(values) <= 0) || values(1) ~= 0.0 || ...
            values(end) ~= extentMM || ...
            ~any(abs(values - centerMM) <= 1.0e-12)
        error( ...
            'MonoTeach:InvalidWritingScaleSweepGrid', ...
            '%s must include boundaries, centre, and interior samples.', fieldName);
    end
end
