function sweep = sweep_writing_task_plane_yaw( ...
        robot, taskPlaneConfig, ikConfig, writingPostureConfig, sweepConfig)
%SWEEP_WRITING_TASK_PLANE_YAW Scan vertical Task Plane yaw and centre height.
%
% For every (center Z, yaw) cell, Rnew = Rz_base(yaw) * R0 and both
% robot_anchor_m(3) and T_base_taskplane(3,4) receive the centre Z. The
% Task Plane stays vertical; its X/Y translation, workspace scale, and
% dimensions remain unchanged.

    if nargin < 5 || isempty(sweepConfig)
        sweepConfig = default_writing_yaw_sweep_config();
    end
    validate_inputs(robot, taskPlaneConfig, writingPostureConfig, sweepConfig);

    baselineTaskPlaneConfig = taskPlaneConfig;
    R0 = taskPlaneConfig.T_base_taskplane(1:3, 1:3);
    diagnosticConfig = default_writing_anchor_diagnostic_config();
    diagnosticConfig.random_seed = sweepConfig.random_seed;
    diagnosticConfig.random_seed_count = sweepConfig.random_seed_count;
    diagnosticConfig.solver_algorithms = {sweepConfig.solver_algorithm};
    diagnosticConfig.allow_random_restart = sweepConfig.allow_random_restart;

    records = repmat(empty_record(), 1, ...
        numel(sweepConfig.center_z_values_m) * ...
        numel(sweepConfig.yaw_deg_values) * 2);
    recordIndex = 0;
    for heightIndex = 1:numel(sweepConfig.center_z_values_m)
        centerZM = sweepConfig.center_z_values_m(heightIndex);
        previousSelectedQ = struct('plus_normal', [], 'minus_normal', []);
        for yawIndex = 1:numel(sweepConfig.yaw_deg_values)
            yawDeg = sweepConfig.yaw_deg_values(yawIndex);
            taskPlaneAtCell = yaw_height_task_plane_config( ...
                baselineTaskPlaneConfig, R0, centerZM, yawDeg);
            geometry = validate_vertical_task_plane( ...
                taskPlaneAtCell, baselineTaskPlaneConfig);

            for signValue = writingPostureConfig.candidate_plane_normal_signs
                signKey = normal_sign_key(signValue);
                perSignPostureConfig = writingPostureConfig;
                perSignPostureConfig.candidate_plane_normal_signs = signValue;
                perSignDiagnosticConfig = diagnosticConfig;
                if ~isempty(previousSelectedQ.(signKey))
                    perSignDiagnosticConfig.additional_seed_set = struct( ...
                        'name', 'previous_yaw_selected_q', ...
                        'initial_q', previousSelectedQ.(signKey));
                end
                diagnostic = diagnose_writing_anchor_multistart( ...
                    robot, taskPlaneAtCell, ikConfig, ...
                    perSignPostureConfig, perSignDiagnosticConfig);

                recordIndex = recordIndex + 1;
                records(recordIndex) = make_record( ...
                    centerZM, yawDeg, taskPlaneAtCell, ...
                    geometry, diagnostic.runs(1));
                selectedQ = records(recordIndex).candidate_q;
                if isnumeric(selectedQ) && ...
                        isequal(size(selectedQ), [1, 5]) && ...
                        all(isfinite(selectedQ)) && ...
                        is_limit_valid_configuration(robot, selectedQ)
                    previousSelectedQ.(signKey) = selectedQ;
                end
            end
        end
    end

    sweep = struct();
    sweep.input_task_plane_config = baselineTaskPlaneConfig;
    sweep.baseline_rotation = R0;
    sweep.sweep_config = sweepConfig;
    sweep.records = records;
    sweep.accepted_plus_normal_pairs_m_deg = record_pairs(records, +1);
    sweep.accepted_minus_normal_pairs_m_deg = record_pairs(records, -1);
end


function config = yaw_height_task_plane_config(config, R0, centerZM, yawDeg)

    yawRad = deg2rad(yawDeg);
    RzBase = [ ...
        cos(yawRad), -sin(yawRad), 0; ...
        sin(yawRad),  cos(yawRad), 0; ...
        0,            0,           1];
    config.robot_anchor_m(3) = centerZM;
    config.T_base_taskplane(3, 4) = centerZM;
    config.T_base_taskplane(1:3, 1:3) = RzBase * R0;
end


function geometry = validate_vertical_task_plane(config, baselineConfig)

    R = config.T_base_taskplane(1:3, 1:3);
    nPlane = derive_task_plane_normal(config);
    tolerance = 1.0e-12;
    taskYAxis = R(:, 2);

    geometry = struct();
    geometry.task_y_axis_base = taskYAxis;
    geometry.plane_normal_base = nPlane;
    geometry.rotation_orthonormal = ...
        norm(R' * R - eye(3), 'fro') <= tolerance;
    geometry.rotation_determinant = det(R);
    geometry.proper_rotation = abs(det(R) - 1.0) <= tolerance;
    geometry.task_y_is_base_negative_z = ...
        norm(taskYAxis - [0; 0; -1]) <= tolerance;
    geometry.plane_normal_base_z = nPlane(3);
    geometry.plane_normal_is_horizontal = abs(nPlane(3)) <= tolerance;
    geometry.translation_xy_unchanged = isequal( ...
        config.T_base_taskplane(1:2, 4), ...
        baselineConfig.T_base_taskplane(1:2, 4));
    geometry.translation_z_matches_anchor = ...
        config.T_base_taskplane(3, 4) == config.robot_anchor_m(3);

    if ~(geometry.rotation_orthonormal && geometry.proper_rotation && ...
            geometry.task_y_is_base_negative_z && ...
            geometry.plane_normal_is_horizontal && ...
            geometry.translation_xy_unchanged && ...
            geometry.translation_z_matches_anchor)
        error( ...
            'MonoTeach:InvalidVerticalYawTaskPlane', ...
            'Yaw-height Task Plane must remain a proper vertical rotation.');
    end
end


function record = make_record(centerZM, yawDeg, taskPlaneConfig, geometry, run)

    if run.accepted_count > 0
        selectedTrialIndex = find([run.trials.accepted], 1, 'first');
        selectionReason = 'first_formally_accepted_trial';
    else
        selectedTrialIndex = run.best_combined_trial_index;
        selectionReason = 'closest_combined_nonaccepted_trial';
    end
    selectedTrial = run.trials(selectedTrialIndex);

    record = empty_record();
    record.center_z_m = centerZM;
    record.yaw_deg = yawDeg;
    record.R_base_taskplane = taskPlaneConfig.T_base_taskplane(1:3, 1:3);
    record.task_plane_translation_m = taskPlaneConfig.T_base_taskplane(1:3, 4)';
    record.plane_normal_base = geometry.plane_normal_base';
    record.normal_sign = run.sign;
    record.task_plane_geometry = geometry;
    record.task_plane_config = taskPlaneConfig;
    record.accepted = run.has_formally_accepted_solution;
    record.accepted_count = run.accepted_count;
    record.solver_algorithm = run.solver_algorithm;
    record.trials = run.trials;
    record.selected_trial_index = selectedTrialIndex;
    record.selection_reason = selectionReason;
    record.seed_provenance = selectedTrial.seed_name;
    record.candidate_q = selectedTrial.candidate_q;
    record.position_error_m = selectedTrial.position_error_m;
    record.direction_error_rad = selectedTrial.tool_direction_error_rad;
    record.direction_error_deg = selectedTrial.tool_direction_error_deg;
    record.within_joint_limits = selectedTrial.within_joint_limits;
    record.minimum_joint_limit_margin = min(selectedTrial.joint_limit_margin);
    record.solver_status = selectedTrial.solver_status;
    record.best_position_error_m = run.best_position_error_m;
    record.best_direction_error_rad = run.best_direction_error_rad;
    record.best_direction_error_deg = run.best_direction_error_deg;
end


function record = empty_record()

    record = struct( ...
        'center_z_m', NaN, ...
        'yaw_deg', NaN, ...
        'R_base_taskplane', NaN(3, 3), ...
        'task_plane_translation_m', NaN(1, 3), ...
        'plane_normal_base', NaN(1, 3), ...
        'normal_sign', NaN, ...
        'task_plane_geometry', struct(), ...
        'task_plane_config', struct(), ...
        'accepted', false, ...
        'accepted_count', 0, ...
        'solver_algorithm', '', ...
        'trials', struct([]), ...
        'selected_trial_index', NaN, ...
        'selection_reason', '', ...
        'seed_provenance', '', ...
        'candidate_q', [], ...
        'position_error_m', NaN, ...
        'direction_error_rad', NaN, ...
        'direction_error_deg', NaN, ...
        'within_joint_limits', false, ...
        'minimum_joint_limit_margin', NaN, ...
        'solver_status', '', ...
        'best_position_error_m', NaN, ...
        'best_direction_error_rad', NaN, ...
        'best_direction_error_deg', NaN);
end


function key = normal_sign_key(signValue)

    if signValue == +1
        key = 'plus_normal';
    else
        key = 'minus_normal';
    end
end


function pairs = record_pairs(records, signValue)

    acceptedRecords = records( ...
        [records.normal_sign] == signValue & [records.accepted]);
    pairs = [[acceptedRecords.center_z_m]', [acceptedRecords.yaw_deg]'];
end


function isValid = is_limit_valid_configuration(robot, q)

    limits = zeros(robot.NumBodies, 2);
    for bodyIndex = 1:robot.NumBodies
        limits(bodyIndex, :) = robot.Bodies{bodyIndex}.Joint.PositionLimits;
    end
    isValid = all(q >= limits(:, 1)' & q <= limits(:, 2)');
end


function validate_inputs(robot, taskPlaneConfig, writingPostureConfig, sweepConfig)

    if ~isa(robot, 'rigidBodyTree') || ~strcmp(robot.DataFormat, 'row') || ...
            robot.NumBodies ~= 5
        error( ...
            'MonoTeach:InvalidWritingYawSweepRobot', ...
            'robot must be the row-format Legacy 5DOF rigidBodyTree.');
    end

    if ~isstruct(taskPlaneConfig) || ~isscalar(taskPlaneConfig) || ...
            ~isfield(taskPlaneConfig, 'robot_anchor_m') || ...
            ~isfield(taskPlaneConfig, 'T_base_taskplane')
        error( ...
            'MonoTeach:InvalidWritingYawSweepTaskPlane', ...
            'taskPlaneConfig must contain robot_anchor_m and T_base_taskplane.');
    end

    if ~isstruct(writingPostureConfig) || ...
            ~isequal(writingPostureConfig.candidate_plane_normal_signs, [+1, -1])
        error( ...
            'MonoTeach:InvalidWritingYawSweepPostureConfig', ...
            'writingPostureConfig must retain [+1, -1] candidates.');
    end

    requiredFields = { ...
        'yaw_deg_values', ...
        'center_z_values_m', ...
        'random_seed', ...
        'random_seed_count', ...
        'solver_algorithm', ...
        'allow_random_restart'};
    if ~isstruct(sweepConfig) || ~isscalar(sweepConfig) || ...
            ~all(isfield(sweepConfig, requiredFields))
        error( ...
            'MonoTeach:InvalidWritingYawSweepConfig', ...
            'sweepConfig is missing required fields.');
    end

    yawValues = sweepConfig.yaw_deg_values;
    if ~isnumeric(yawValues) || ~isreal(yawValues) || ~isrow(yawValues) || ...
            isempty(yawValues) || any(~isfinite(yawValues)) || ...
            any(diff(yawValues) <= 0) || ~any(yawValues == 0)
        error( ...
            'MonoTeach:InvalidWritingYawSweepValues', ...
            'yaw_deg_values must be increasing finite row data containing 0.');
    end

    zValues = sweepConfig.center_z_values_m;
    if ~isnumeric(zValues) || ~isreal(zValues) || ~isrow(zValues) || ...
            isempty(zValues) || any(~isfinite(zValues)) || ...
            any(diff(zValues) <= 0) || any(zValues > 0.255)
        error( ...
            'MonoTeach:InvalidWritingYawSweepHeights', ...
            ['center_z_values_m must be increasing finite values and may ' ...
             'not exceed the default 0.255 m centre height.']);
    end

    if ~strcmp(string(sweepConfig.solver_algorithm), ...
            "BFGSGradientProjection") || ...
            ~islogical(sweepConfig.allow_random_restart) || ...
            ~isscalar(sweepConfig.allow_random_restart) || ...
            sweepConfig.allow_random_restart
        error( ...
            'MonoTeach:InvalidWritingYawSweepSolver', ...
            ['The deterministic coarse sweep requires BFGSGradientProjection ' ...
             'with AllowRandomRestart=false.']);
    end
end
