function sweep = sweep_writing_anchor_height( ...
        robot, taskPlaneConfig, ikConfig, writingPostureConfig, sweepConfig)
%SWEEP_WRITING_ANCHOR_HEIGHT Coarsely scan synchronized Task Plane heights.
%
% Each height is a copied task-plane config: robot_anchor_m(3) and
% T_base_taskplane(3,4) change together while rotation, X/Y anchor, and
% workspace scale remain unchanged. The Step 3 deterministic multi-start
% diagnostic supplies current-height q_anchor, home, and fixed valid seeds.

    if nargin < 5 || isempty(sweepConfig)
        sweepConfig = default_writing_height_sweep_config();
    end
    validate_inputs(robot, taskPlaneConfig, writingPostureConfig, sweepConfig);

    baselineTaskPlaneConfig = taskPlaneConfig;
    diagnosticConfig = default_writing_anchor_diagnostic_config();
    diagnosticConfig.random_seed = sweepConfig.random_seed;
    diagnosticConfig.random_seed_count = sweepConfig.random_seed_count;
    diagnosticConfig.solver_algorithms = {sweepConfig.solver_algorithm};
    diagnosticConfig.allow_random_restart = sweepConfig.allow_random_restart;

    records = repmat(empty_record(), 1, ...
        numel(sweepConfig.anchor_z_values_m) * 2);
    recordIndex = 0;
    previousSelectedQ = struct('plus_normal', [], 'minus_normal', []);
    for heightIndex = 1:numel(sweepConfig.anchor_z_values_m)
        anchorZM = sweepConfig.anchor_z_values_m(heightIndex);
        heightTaskPlaneConfig = synchronized_height_config( ...
            baselineTaskPlaneConfig, anchorZM);
        for signValue = writingPostureConfig.candidate_plane_normal_signs
            signKey = normal_sign_key(signValue);
            perSignPostureConfig = writingPostureConfig;
            perSignPostureConfig.candidate_plane_normal_signs = signValue;
            perSignDiagnosticConfig = diagnosticConfig;
            if ~isempty(previousSelectedQ.(signKey))
                perSignDiagnosticConfig.additional_seed_set = struct( ...
                    'name', 'previous_height_selected_q', ...
                    'initial_q', previousSelectedQ.(signKey));
            end
            diagnostic = diagnose_writing_anchor_multistart( ...
                robot, ...
                heightTaskPlaneConfig, ...
                ikConfig, ...
                perSignPostureConfig, ...
                perSignDiagnosticConfig);

            recordIndex = recordIndex + 1;
            records(recordIndex) = make_record( ...
                heightTaskPlaneConfig, ...
                diagnostic.runs(1));
            selectedQ = records(recordIndex).best_candidate_q;
            if isnumeric(selectedQ) && isequal(size(selectedQ), [1, 5]) && ...
                    all(isfinite(selectedQ)) && ...
                    is_limit_valid_configuration(robot, selectedQ)
                previousSelectedQ.(signKey) = selectedQ;
            end
        end
    end

    sweep = struct();
    sweep.input_task_plane_config = baselineTaskPlaneConfig;
    sweep.sweep_config = sweepConfig;
    sweep.records = records;
    sweep.accepted_plus_normal_heights_m = [ ...
        records([records.sign] == +1 & [records.accepted]).anchor_z_m];
    sweep.accepted_minus_normal_heights_m = [ ...
        records([records.sign] == -1 & [records.accepted]).anchor_z_m];
end


function key = normal_sign_key(signValue)

    if signValue == +1
        key = 'plus_normal';
    else
        key = 'minus_normal';
    end
end


function isValid = is_limit_valid_configuration(robot, q)

    limits = zeros(robot.NumBodies, 2);
    for bodyIndex = 1:robot.NumBodies
        limits(bodyIndex, :) = robot.Bodies{bodyIndex}.Joint.PositionLimits;
    end
    isValid = all(q >= limits(:, 1)' & q <= limits(:, 2)');
end


function config = synchronized_height_config(config, anchorZM)

    config.robot_anchor_m(3) = anchorZM;
    config.T_base_taskplane(3, 4) = anchorZM;
end


function record = make_record(heightTaskPlaneConfig, run)

    if run.accepted_count > 0
        selectedTrialIndex = find([run.trials.accepted], 1, 'first');
        selectionReason = 'first_formally_accepted_trial';
    else
        selectedTrialIndex = run.best_combined_trial_index;
        selectionReason = 'closest_combined_nonaccepted_trial';
    end
    selectedTrial = run.trials(selectedTrialIndex);

    record = empty_record();
    record.anchor_z_m = heightTaskPlaneConfig.robot_anchor_m(3);
    record.sign = run.sign;
    record.task_plane_config = heightTaskPlaneConfig;
    record.task_plane_orientation = ...
        heightTaskPlaneConfig.T_base_taskplane(1:3, 1:3);
    record.target_xyz_m = [ ...
        heightTaskPlaneConfig.robot_anchor_m(1:2), ...
        heightTaskPlaneConfig.robot_anchor_m(3)];
    record.aim_target_m = run.aim_target_m;
    record.solver_algorithm = run.solver_algorithm;
    record.trials = run.trials;
    record.accepted = run.has_formally_accepted_solution;
    record.accepted_count = run.accepted_count;
    record.selected_trial_index = selectedTrialIndex;
    record.selection_reason = selectionReason;
    record.seed_provenance = selectedTrial.seed_name;
    record.best_candidate_q = selectedTrial.candidate_q;
    record.position_error_m = selectedTrial.position_error_m;
    record.direction_error_rad = selectedTrial.tool_direction_error_rad;
    record.direction_error_deg = selectedTrial.tool_direction_error_deg;
    record.within_joint_limits = selectedTrial.within_joint_limits;
    record.minimum_joint_limit_margin = min(selectedTrial.joint_limit_margin);
    record.solver_status = selectedTrial.solver_status;
    record.best_position_error_m = run.best_position_error_m;
    record.best_direction_error_rad = run.best_direction_error_rad;
    record.best_direction_error_deg = run.best_direction_error_deg;
    record.best_combined_position_error_m = run.best_combined_position_error_m;
    record.best_combined_direction_error_rad = ...
        run.best_combined_direction_error_rad;
end


function record = empty_record()

    record = struct( ...
        'anchor_z_m', NaN, ...
        'sign', NaN, ...
        'task_plane_config', struct(), ...
        'task_plane_orientation', NaN(3, 3), ...
        'target_xyz_m', NaN(1, 3), ...
        'aim_target_m', NaN(1, 3), ...
        'solver_algorithm', '', ...
        'trials', struct([]), ...
        'accepted', false, ...
        'accepted_count', 0, ...
        'selected_trial_index', NaN, ...
        'selection_reason', '', ...
        'seed_provenance', '', ...
        'best_candidate_q', [], ...
        'position_error_m', NaN, ...
        'direction_error_rad', NaN, ...
        'direction_error_deg', NaN, ...
        'within_joint_limits', false, ...
        'minimum_joint_limit_margin', NaN, ...
        'solver_status', '', ...
        'best_position_error_m', NaN, ...
        'best_direction_error_rad', NaN, ...
        'best_direction_error_deg', NaN, ...
        'best_combined_position_error_m', NaN, ...
        'best_combined_direction_error_rad', NaN);
end


function validate_inputs(robot, taskPlaneConfig, writingPostureConfig, sweepConfig)

    if ~isa(robot, 'rigidBodyTree') || ~strcmp(robot.DataFormat, 'row') || ...
            robot.NumBodies ~= 5
        error( ...
            'MonoTeach:InvalidWritingHeightSweepRobot', ...
            'robot must be the row-format Legacy 5DOF rigidBodyTree.');
    end

    if ~isstruct(taskPlaneConfig) || ~isscalar(taskPlaneConfig) || ...
            ~isfield(taskPlaneConfig, 'robot_anchor_m') || ...
            ~isfield(taskPlaneConfig, 'T_base_taskplane')
        error( ...
            'MonoTeach:InvalidWritingHeightSweepTaskPlane', ...
            'taskPlaneConfig must contain robot_anchor_m and T_base_taskplane.');
    end

    if ~isstruct(writingPostureConfig) || ...
            ~isequal(writingPostureConfig.candidate_plane_normal_signs, [+1, -1])
        error( ...
            'MonoTeach:InvalidWritingHeightSweepPostureConfig', ...
            'writingPostureConfig must retain [+1, -1] candidates.');
    end

    if ~isstruct(sweepConfig) || ~isscalar(sweepConfig) || ...
            ~isfield(sweepConfig, 'anchor_z_values_m') || ...
            ~isfield(sweepConfig, 'random_seed') || ...
            ~isfield(sweepConfig, 'random_seed_count') || ...
            ~isfield(sweepConfig, 'solver_algorithm') || ...
            ~isfield(sweepConfig, 'allow_random_restart')
        error( ...
            'MonoTeach:InvalidWritingHeightSweepConfig', ...
            'sweepConfig is missing required fields.');
    end

    zValues = sweepConfig.anchor_z_values_m;
    if ~isnumeric(zValues) || ~isreal(zValues) || ~isrow(zValues) || ...
            isempty(zValues) || any(~isfinite(zValues)) || ...
            any(diff(zValues) <= 0)
        error( ...
            'MonoTeach:InvalidWritingHeightSweepValues', ...
            'anchor_z_values_m must be strictly increasing finite row data.');
    end

    if ~strcmp(string(sweepConfig.solver_algorithm), ...
            "BFGSGradientProjection") || ...
            ~islogical(sweepConfig.allow_random_restart) || ...
            ~isscalar(sweepConfig.allow_random_restart) || ...
            sweepConfig.allow_random_restart
        error( ...
            'MonoTeach:InvalidWritingHeightSweepSolver', ...
            ['The deterministic coarse sweep requires BFGSGradientProjection ' ...
             'with AllowRandomRestart=false.']);
    end
end
