function sweep = sweep_writing_task_plane_xy( ...
        robot, taskPlaneConfig, ikConfig, writingPostureConfig, sweepConfig)
%SWEEP_WRITING_TASK_PLANE_XY Scan local XY placement at the Step 6 posture.
%
% Every cell has yaw=-60 deg, centre Z=0.195 m, and +normal aiming.  Both
% robot_anchor_m(1:2) and T_base_taskplane(1:2,4) move together, while the
% Task Plane rotation, scale, workspace dimensions, and Z stay fixed.

    if nargin < 5 || isempty(sweepConfig)
        sweepConfig = default_writing_xy_sweep_config();
    end
    validate_inputs(robot, taskPlaneConfig, writingPostureConfig, sweepConfig);

    baselineTaskPlaneConfig = taskPlaneConfig;
    fixedRotation = yawed_rotation( ...
        baselineTaskPlaneConfig.T_base_taskplane(1:3, 1:3), ...
        sweepConfig.fixed_yaw_deg);
    diagnosticConfig = default_writing_anchor_diagnostic_config();
    diagnosticConfig.random_seed = sweepConfig.random_seed;
    diagnosticConfig.random_seed_count = sweepConfig.random_seed_count;
    diagnosticConfig.solver_algorithms = {sweepConfig.solver_algorithm};
    diagnosticConfig.allow_random_restart = sweepConfig.allow_random_restart;

    records = repmat(empty_record(), 1, ...
        numel(sweepConfig.x_values_m) * numel(sweepConfig.y_values_m));
    recordIndex = 0;
    for yIndex = 1:numel(sweepConfig.y_values_m)
        yM = sweepConfig.y_values_m(yIndex);
        previousSelectedQ = [];
        for xIndex = 1:numel(sweepConfig.x_values_m)
            xM = sweepConfig.x_values_m(xIndex);
            taskPlaneAtCell = xy_task_plane_config( ...
                baselineTaskPlaneConfig, fixedRotation, ...
                sweepConfig.fixed_center_z_m, xM, yM);
            geometry = validate_fixed_xy_task_plane( ...
                taskPlaneAtCell, baselineTaskPlaneConfig, fixedRotation, ...
                sweepConfig.fixed_center_z_m);

            perCellPostureConfig = writingPostureConfig;
            perCellPostureConfig.candidate_plane_normal_signs = ...
                sweepConfig.normal_sign;
            perCellDiagnosticConfig = diagnosticConfig;
            if ~isempty(previousSelectedQ)
                perCellDiagnosticConfig.additional_seed_set = struct( ...
                    'name', 'previous_x_selected_q', ...
                    'initial_q', previousSelectedQ);
            end
            diagnostic = diagnose_writing_anchor_multistart( ...
                robot, taskPlaneAtCell, ikConfig, ...
                perCellPostureConfig, perCellDiagnosticConfig);
            run = diagnostic.runs(1);

            recordIndex = recordIndex + 1;
            records(recordIndex) = make_record( ...
                xM, yM, taskPlaneAtCell, geometry, run);
            selectedQ = records(recordIndex).candidate_q;
            if is_limit_valid_configuration(robot, selectedQ)
                previousSelectedQ = selectedQ;
            end
        end
    end

    sweep = struct();
    sweep.input_task_plane_config = baselineTaskPlaneConfig;
    sweep.fixed_rotation = fixedRotation;
    sweep.sweep_config = sweepConfig;
    sweep.records = records;
    acceptedRecords = records([records.accepted]);
    sweep.accepted_xy_m = [[acceptedRecords.x_m]', [acceptedRecords.y_m]'];
end


function config = xy_task_plane_config(config, fixedRotation, centerZM, xM, yM)

    config.robot_anchor_m = [xM, yM, centerZM];
    config.T_base_taskplane(1:3, 1:3) = fixedRotation;
    config.T_base_taskplane(1:3, 4) = [xM; yM; centerZM];
end


function rotation = yawed_rotation(R0, yawDeg)

    yawRad = deg2rad(yawDeg);
    RzBase = [ ...
        cos(yawRad), -sin(yawRad), 0; ...
        sin(yawRad),  cos(yawRad), 0; ...
        0,            0,           1];
    rotation = RzBase * R0;
end


function geometry = validate_fixed_xy_task_plane( ...
        config, baselineConfig, fixedRotation, centerZM)

    R = config.T_base_taskplane(1:3, 1:3);
    tolerance = 1.0e-12;
    taskYAxis = R(:, 2);
    nPlane = derive_task_plane_normal(config);

    geometry = struct();
    geometry.rotation_unchanged = norm(R - fixedRotation, 'fro') <= tolerance;
    geometry.rotation_orthonormal = norm(R' * R - eye(3), 'fro') <= tolerance;
    geometry.rotation_determinant = det(R);
    geometry.proper_rotation = abs(det(R) - 1.0) <= tolerance;
    geometry.task_y_is_base_negative_z = ...
        norm(taskYAxis - [0; 0; -1]) <= tolerance;
    geometry.plane_normal_base = nPlane;
    geometry.plane_normal_is_horizontal = abs(nPlane(3)) <= tolerance;
    geometry.workspace_scale_unchanged = config.scale == baselineConfig.scale;
    geometry.workspace_dimensions_unchanged = ...
        config.workspace_width_mm == baselineConfig.workspace_width_mm && ...
        config.workspace_height_mm == baselineConfig.workspace_height_mm;
    geometry.translation_matches_anchor = norm( ...
        config.T_base_taskplane(1:3, 4)' - config.robot_anchor_m) <= tolerance;
    geometry.translation_z_matches_fixed_center = ...
        abs(config.T_base_taskplane(3, 4) - centerZM) <= tolerance;

    if ~(geometry.rotation_unchanged && geometry.rotation_orthonormal && ...
            geometry.proper_rotation && ...
            geometry.task_y_is_base_negative_z && ...
            geometry.plane_normal_is_horizontal && ...
            geometry.workspace_scale_unchanged && ...
            geometry.workspace_dimensions_unchanged && ...
            geometry.translation_matches_anchor && ...
            geometry.translation_z_matches_fixed_center)
        error( ...
            'MonoTeach:InvalidWritingXYSweepTaskPlane', ...
            'XY sweep must preserve the fixed Step 6 Task Plane geometry.');
    end
end


function record = make_record(xM, yM, taskPlaneConfig, geometry, run)

    if run.accepted_count > 0
        selectedTrialIndex = find([run.trials.accepted], 1, 'first');
        selectionReason = 'first_formally_accepted_trial';
    else
        selectedTrialIndex = run.best_combined_trial_index;
        selectionReason = 'closest_combined_nonaccepted_trial';
    end
    selectedTrial = run.trials(selectedTrialIndex);

    record = empty_record();
    record.x_m = xM;
    record.y_m = yM;
    record.accepted = run.has_formally_accepted_solution;
    record.accepted_count = run.accepted_count;
    record.normal_sign = run.sign;
    record.task_plane_config = taskPlaneConfig;
    record.task_plane_geometry = geometry;
    record.candidate_q = selectedTrial.candidate_q;
    record.position_error_m = selectedTrial.position_error_m;
    record.direction_error_rad = selectedTrial.tool_direction_error_rad;
    record.direction_error_deg = selectedTrial.tool_direction_error_deg;
    record.within_joint_limits = selectedTrial.within_joint_limits;
    record.minimum_joint_limit_margin = min(selectedTrial.joint_limit_margin);
    record.solver_status = selectedTrial.solver_status;
    record.seed_provenance = selectedTrial.seed_name;
    record.solver_algorithm = run.solver_algorithm;
    record.trials = run.trials;
    record.selected_trial_index = selectedTrialIndex;
    record.selection_reason = selectionReason;
    record.best_position_error_m = run.best_position_error_m;
    record.best_direction_error_rad = run.best_direction_error_rad;
    record.best_direction_error_deg = run.best_direction_error_deg;
end


function record = empty_record()

    record = struct( ...
        'x_m', NaN, ...
        'y_m', NaN, ...
        'accepted', false, ...
        'accepted_count', 0, ...
        'normal_sign', NaN, ...
        'task_plane_config', struct(), ...
        'task_plane_geometry', struct(), ...
        'candidate_q', [], ...
        'position_error_m', NaN, ...
        'direction_error_rad', NaN, ...
        'direction_error_deg', NaN, ...
        'within_joint_limits', false, ...
        'minimum_joint_limit_margin', NaN, ...
        'solver_status', '', ...
        'seed_provenance', '', ...
        'solver_algorithm', '', ...
        'trials', struct([]), ...
        'selected_trial_index', NaN, ...
        'selection_reason', '', ...
        'best_position_error_m', NaN, ...
        'best_direction_error_rad', NaN, ...
        'best_direction_error_deg', NaN);
end


function isValid = is_limit_valid_configuration(robot, q)

    if ~isnumeric(q) || ~isreal(q) || ...
            ~isequal(size(q), [1, robot.NumBodies]) || any(~isfinite(q))
        isValid = false;
        return;
    end
    limits = zeros(robot.NumBodies, 2);
    for bodyIndex = 1:robot.NumBodies
        limits(bodyIndex, :) = robot.Bodies{bodyIndex}.Joint.PositionLimits;
    end
    isValid = all(q >= limits(:, 1)' & q <= limits(:, 2)');
end


function validate_inputs(robot, taskPlaneConfig, writingPostureConfig, sweepConfig)

    if ~isa(robot, 'rigidBodyTree') || ~strcmp(robot.DataFormat, 'row') || ...
            robot.NumBodies ~= 5
        error( ...
            'MonoTeach:InvalidWritingXYSweepRobot', ...
            'robot must be the row-format Legacy 5DOF rigidBodyTree.');
    end

    requiredTaskPlaneFields = { ...
        'robot_anchor_m', 'T_base_taskplane', 'scale', ...
        'workspace_width_mm', 'workspace_height_mm'};
    if ~isstruct(taskPlaneConfig) || ~isscalar(taskPlaneConfig) || ...
            ~all(isfield(taskPlaneConfig, requiredTaskPlaneFields))
        error( ...
            'MonoTeach:InvalidWritingXYSweepTaskPlane', ...
            'taskPlaneConfig is missing required Task Plane fields.');
    end

    if ~isstruct(writingPostureConfig) || ...
            ~isequal(writingPostureConfig.candidate_plane_normal_signs, [+1, -1])
        error( ...
            'MonoTeach:InvalidWritingXYSweepPostureConfig', ...
            'writingPostureConfig must retain the unresolved +/- candidates.');
    end

    requiredSweepFields = { ...
        'x_values_m', 'y_values_m', 'fixed_yaw_deg', ...
        'fixed_center_z_m', 'normal_sign', 'random_seed', ...
        'random_seed_count', 'solver_algorithm', 'allow_random_restart'};
    if ~isstruct(sweepConfig) || ~isscalar(sweepConfig) || ...
            ~all(isfield(sweepConfig, requiredSweepFields))
        error( ...
            'MonoTeach:InvalidWritingXYSweepConfig', ...
            'sweepConfig is missing required fields.');
    end

    require_increasing_finite_row(sweepConfig.x_values_m, 'x_values_m');
    require_increasing_finite_row(sweepConfig.y_values_m, 'y_values_m');
    if ~any(abs(sweepConfig.x_values_m - 0.100) <= 1.0e-12) || ...
            ~any(abs(sweepConfig.y_values_m - 0.040) <= 1.0e-12)
        error( ...
            'MonoTeach:MissingDefaultWritingXYAnchor', ...
            'The XY sweep grid must include the default [0.100, 0.040] m.');
    end

    if ~isscalar(sweepConfig.fixed_yaw_deg) || ...
            sweepConfig.fixed_yaw_deg ~= -60.0 || ...
            ~isscalar(sweepConfig.fixed_center_z_m) || ...
            sweepConfig.fixed_center_z_m ~= 0.195 || ...
            ~isscalar(sweepConfig.normal_sign) || ...
            sweepConfig.normal_sign ~= +1
        error( ...
            'MonoTeach:InvalidWritingXYFixedCandidate', ...
            'Step 7 fixes yaw=-60 deg, Z=0.195 m, and +normal.');
    end

    if ~strcmp(string(sweepConfig.solver_algorithm), ...
            "BFGSGradientProjection") || ...
            ~islogical(sweepConfig.allow_random_restart) || ...
            ~isscalar(sweepConfig.allow_random_restart) || ...
            sweepConfig.allow_random_restart
        error( ...
            'MonoTeach:InvalidWritingXYSweepSolver', ...
            ['The deterministic coarse sweep requires BFGSGradientProjection ' ...
             'with AllowRandomRestart=false.']);
    end
end


function require_increasing_finite_row(values, fieldName)

    if ~isnumeric(values) || ~isreal(values) || ~isrow(values) || ...
            isempty(values) || any(~isfinite(values)) || any(diff(values) <= 0)
        error( ...
            'MonoTeach:InvalidWritingXYSweepGrid', ...
            '%s must be an increasing finite numeric row.', fieldName);
    end
end
