function audit = audit_banter_fist_timing(fixturePath)
%AUDIT_BANTER_FIST_TIMING Print per-segment Task 6 FIST timing evidence.
%   This is an offline diagnostics helper for the three timing-only FIST
%   variants. It neither changes a plan nor opens a robot/camera connection.

    if nargin < 1 || isempty(fixturePath)
        error('MonoTeach:BanterFixtureRequired', ...
            ['Generate a JSON fixture first, for example: python -m ' ...
            'banter.export_task6_styled_plans outputs/banter_task6_styled_plans.json']);
    end
    payload = jsondecode(fileread(fixturePath));
    if ~isfield(payload, 'plans') || ~isstruct(payload.plans)
        error('MonoTeach:BanterFixture', 'Fixture must contain a plans array.');
    end
    context = load_robot_context('legacy5');
    timingConfig = default_timed_joint_trajectory_config(context);
    records = repmat(empty_record(), 1, 0);
    plans = payload.plans;
    for planIndex = 1:numel(plans)
        if ~strcmp(string(plans(planIndex).behavior_name), "FIST_COUNTER")
            continue;
        end
        compiled = compile_styled_banter_motion_plan( ...
            plans(planIndex), context, timingConfig);
        segments = compiled.continuous_trajectory.segments;
        for segmentIndex = 1:numel(segments)
            segment = segments(segmentIndex);
            guard = compiled.movement_run_guard_evidence(segmentIndex);
            [constraint, jointName, ratio] = dominant_initial_constraint( ...
                segment, timingConfig, context);
            records(end + 1) = struct( ...
                'variant', char(string(compiled.variant)), ...
                'group_index', segmentIndex, ...
                'source_step_indices', mat2str(compiled.segment_groups(segmentIndex).source_step_indices), ...
                'requested_duration_s', segment.initial_duration_s, ...
                'actual_duration_s', segment.duration_s, ...
                'time_stretch_factor', segment.time_stretch_factor, ...
                'initial_velocity_ratio', segment.initial_velocity_limit_ratio, ...
                'initial_acceleration_ratio', segment.initial_acceleration_limit_ratio, ...
                'dominant_constraint', constraint, ...
                'dominant_joint', jointName, ...
                'dominant_ratio', ratio, ...
                'plan_requested_duration_s', compiled.summary.requested_styled_duration_s, ...
                'plan_resolved_duration_s', compiled.summary.resolved_timing_duration_s, ...
                'plan_actual_duration_s', compiled.summary.execution_duration_s, ...
                'retiming_method', compiled.summary.style_timing_resolution.retiming_method, ...
                'baseline_duration_s', compiled.summary.style_timing_resolution.baseline_duration_s, ...
                'toppra_duration_s', compiled.summary.style_timing_resolution.toppra_duration_s, ...
                'toppra_sample_count', compiled.summary.style_timing_resolution.toppra_sample_count, ...
                'toppra_path_joint_deviation_rad', compiled.summary.style_timing_resolution.toppra_path_joint_deviation_rad, ...
                'toppra_path_fk_deviation_m', compiled.summary.style_timing_resolution.toppra_path_fk_deviation_m, ...
                'guard_status', guard.status, ...
                'guard_stage', guard.stage, ...
                'guard_overshoot_before_rad', guard_max_overshoot(guard.overshoot_before), ...
                'guard_overshoot_after_rad', guard_max_overshoot(guard.overshoot_after), ...
                'guard_affected_joint_waypoints', mat2str(guard.affected_joint_waypoint_indices), ...
                'guard_velocity_zeroed_joint_waypoints', mat2str(find_guard_indices(guard.velocity_zeroed_mask)), ...
                'guard_qd_before_rad_s', mat2str(guard.velocity_boundary_before_rad_s, 6), ...
                'guard_qd_after_rad_s', mat2str(guard.velocity_boundary_after_rad_s, 6), ...
                'guard_qdd_before_rad_s2', mat2str(guard.acceleration_boundary_before_rad_s2, 6), ...
                'guard_qdd_after_rad_s2', mat2str(guard.acceleration_boundary_after_rad_s2, 6), ...
                'fallback_reason', compiled.summary.style_timing_resolution.fallback_reason); %#ok<AGROW>
        end
    end
    audit = struct( ...
        'artifact_type', 'BanterFistTimingAudit', ...
        'limit_source', context.limit_source, ...
        'max_velocity_rad_s', timingConfig.max_velocity_rad_s, ...
        'max_acceleration_rad_s2', timingConfig.max_acceleration_rad_s2, ...
        'segments', records);
    fprintf('Limit source: %s\n', audit.limit_source);
    fprintf('max_velocity_rad_s: %s\n', mat2str(audit.max_velocity_rad_s));
    fprintf('max_acceleration_rad_s2: %s\n', mat2str(audit.max_acceleration_rad_s2));
    disp(struct2table(records));
end

function [constraint, jointName, ratio] = dominant_initial_constraint( ...
        segment, timingConfig, context)
    velocityRatio = segment.initial_peak_velocity_rad_s ./ ...
        timingConfig.max_velocity_rad_s;
    accelerationRatio = segment.initial_peak_acceleration_rad_s2 ./ ...
        timingConfig.max_acceleration_rad_s2;
    [maxVelocity, velocityJoint] = max(velocityRatio);
    [maxAcceleration, accelerationJoint] = max(accelerationRatio);
    [ratio, kind] = max([maxVelocity, maxAcceleration]);
    if ratio == 0.0
        constraint = 'NONE';
        jointName = '';
    elseif kind == 1
        constraint = 'VELOCITY';
        jointName = context.joint_names{velocityJoint};
    else
        constraint = 'ACCELERATION';
        jointName = context.joint_names{accelerationJoint};
    end
end

function record = empty_record()
    record = struct( ...
        'variant', '', 'group_index', NaN, 'source_step_indices', '', ...
        'requested_duration_s', NaN, 'actual_duration_s', NaN, ...
        'time_stretch_factor', NaN, 'initial_velocity_ratio', NaN, ...
        'initial_acceleration_ratio', NaN, 'dominant_constraint', '', ...
        'dominant_joint', '', 'dominant_ratio', NaN, ...
        'plan_requested_duration_s', NaN, ...
        'plan_resolved_duration_s', NaN, 'plan_actual_duration_s', NaN, ...
        'retiming_method', '', 'baseline_duration_s', NaN, ...
        'toppra_duration_s', NaN, 'toppra_sample_count', NaN, ...
        'toppra_path_joint_deviation_rad', NaN, ...
        'toppra_path_fk_deviation_m', NaN, 'guard_status', '', ...
        'guard_stage', '', 'guard_overshoot_before_rad', NaN, ...
        'guard_overshoot_after_rad', NaN, 'guard_affected_joint_waypoints', '', ...
        'guard_velocity_zeroed_joint_waypoints', '', ...
        'guard_qd_before_rad_s', '', 'guard_qd_after_rad_s', '', ...
        'guard_qdd_before_rad_s2', '', 'guard_qdd_after_rad_s2', '', ...
        'fallback_reason', '');
end

function value = guard_max_overshoot(evidence)
    if isstruct(evidence) && isfield(evidence, 'max_overshoot_magnitude_rad')
        value = evidence.max_overshoot_magnitude_rad;
    else
        value = NaN;
    end
end

function indices = find_guard_indices(mask)
    [waypoint, joint] = find(mask);
    indices = [joint, waypoint];
end
