function compiled = compile_banter_motion_plan(motionPlan, robotContext, timingConfig)
%COMPILE_BANTER_MOTION_PLAN Named Task 5 steps -> existing Legacy5 quintic q(t).
%   The input is a JSON-decoded MotionPlan struct. This compiler owns only the
%   pose lookup/adaptation; Stage 3's public quintic generator remains the
%   sole timing and joint-limit authority.

    if nargin < 2 || isempty(robotContext)
        robotContext = load_robot_context('legacy5');
    end
    if nargin < 3 || isempty(timingConfig)
        timingConfig = default_timed_joint_trajectory_config(robotContext);
    end
    validate_motion_plan(motionPlan);
    poses = default_legacy5_banter_pose_library(robotContext);
    inputSnapshot = motionPlan;

    steps = motionPlan.motion_steps;
    [timed, finalQ, nominalDurationS, segmentGroups] = make_timed_trajectory( ...
        motionPlan, steps, poses, robotContext);
    if norm(finalQ - robotContext.home_q, inf) > 1.0e-12
        error('MonoTeach:BanterNeutralReturn', ...
            'Task 5 MotionPlan must compile back to NEUTRAL.');
    end
    [timed, segmentGroups, guardedSegments, guardEvidence] = refine_unsafe_movement_runs( ...
        timed, segmentGroups, motionPlan, timingConfig, robotContext);
    continuous = generate_quintic_continuous_joint_trajectory( ...
        timed, timingConfig, robotContext);
    continuous = apply_guarded_banter_segments(continuous, guardedSegments, timingConfig);
    segments = continuous.segments;
    overshootEvidence = [segments.overshoot_evidence];
    if ~all([segments.all_safety_checks_satisfied]) || ...
            any([overshootEvidence.has_overshoot])
        error('MonoTeach:BanterUnsafeMotion', ...
            'Macro %s did not satisfy Legacy5 quintic safety evidence.', ...
            char(string(motionPlan.macro_name)));
    end
    if ~isequaln(motionPlan, inputSnapshot)
        error('MonoTeach:BanterMotionPlanMutation', ...
            'compile_banter_motion_plan must not modify the input MotionPlan.');
    end
    compiled = struct( ...
        'artifact_type', 'CompiledBanterMotion', ...
        'schema_version', 'banter_compiled_motion_v1', ...
        'robot_id', robotContext.id, ...
        'macro_name', char(string(motionPlan.macro_name)), ...
        'variant', char(string(motionPlan.variant)), ...
        'source_behavior', motionPlan.source_behavior, ...
        'motion_plan', motionPlan, ...
        'segmentation_method', 'HOLD_BOUNDARY_RUNS_V1', ...
        'segment_groups', segmentGroups, ...
        'movement_run_guard_evidence', guardEvidence, ...
        'continuous_trajectory', continuous, ...
        'summary', struct( ...
            'nominal_duration_s', nominalDurationS, ...
            'execution_duration_s', sum([segments.duration_s]), ...
            'minimum_joint_limit_margin_rad', min([segments.minimum_joint_limit_margin]), ...
            'max_observed_abs_velocity_rad_s', max(vertcat(segments.max_observed_abs_velocity_rad_s), [], 1), ...
            'max_observed_abs_acceleration_rad_s2', max(vertcat(segments.max_observed_abs_acceleration_rad_s2), [], 1), ...
            'all_safety_checks_satisfied', all([segments.all_safety_checks_satisfied]), ...
            'has_joint_overshoot', any([overshootEvidence.has_overshoot])));
end

function [timed, finalQ, nominalDurationS, segmentGroups] = make_timed_trajectory( ...
        motionPlan, steps, poses, robotContext)
    sourceIds = double(motionPlan.source_behavior.source_token_event_ids(:)');
    if isempty(sourceIds)
        sourceIds = double(motionPlan.source_behavior.source_phrase_ids(:)');
    end
    sourceIndex = sourceIds(1);
    currentQ = robotContext.home_q;
    segmentTemplate = struct( ...
        'segment_index', NaN, 'ik_success_segment_index', NaN, ...
        'preik_segment_index', NaN, 'source_indices', zeros(1, 0), ...
        'waypoints', struct('provenance', ''), 'q_rad', zeros(0, robotContext.dof), ...
        't_s', zeros(0, 1));
    segments = repmat(segmentTemplate, 1, 0);
    groupTemplate = struct( ...
        'group_index', NaN, 'kind', '', 'source_step_indices', zeros(1, 0), ...
        'requested_duration_s', NaN, 'segmentation_reason', '');
    segmentGroups = repmat(groupTemplate, 1, 0);
    nominalDurationS = 0.0;

    % A run of movement steps is one Stage 3 quintic trajectory, so its
    % internal named poses are true waypoints rather than stop-and-go joins.
    % HOLD is deliberately emitted as its own stationary [q; q] segment: it
    % creates the only required rest boundary and prevents hold waypoints from
    % being passed as duplicated samples to a moving quintic.
    [runQ, runT, runStepIndices, runProvenance] = start_movement_run( ...
        currentQ, motionPlan, 0);
    for index = 1:numel(steps)
        step = steps(index);
        poseName = char(string(step.target_pose_name));
        if ~isfield(poses, poseName)
            error('MonoTeach:BanterUnknownPose', ...
                'MotionPlan %d names unknown Legacy5 pose %s.', motionPlan.plan_id, poseName);
        end
        targetQ = poses.(poseName);
        durationS = double(step.duration_ms) / 1000.0;
        provenance = sprintf('behavior_%d_%s_step_%d_%s', ...
            double(motionPlan.source_behavior.behavior_id), ...
            char(string(motionPlan.macro_name)), index, poseName);
        if strcmp(string(step.kind), "HOLD")
            if norm(targetQ - currentQ, inf) > 1.0e-12
                error('MonoTeach:BanterInvalidHoldTarget', ...
                    ['HOLD step %d in MotionPlan %d must target the current ' ...
                    'named pose; it cannot conceal a move.'], ...
                    index, double(motionPlan.plan_id));
            end
            [segments, segmentGroups] = append_movement_run( ...
                segments, segmentGroups, segmentTemplate, groupTemplate, ...
                runQ, runT, runStepIndices, runProvenance, sourceIndex, motionPlan);
            [segments, segmentGroups] = append_hold_segment( ...
                segments, segmentGroups, segmentTemplate, groupTemplate, ...
                currentQ, durationS, index, provenance, sourceIndex, motionPlan);
            [runQ, runT, runStepIndices, runProvenance] = start_movement_run( ...
                currentQ, motionPlan, index);
        else
            runQ(end + 1, :) = targetQ;
            runT(end + 1, 1) = runT(end) + durationS;
            runStepIndices(end + 1) = index;
            runProvenance{end + 1} = provenance;
        end
        currentQ = targetQ;
        nominalDurationS = nominalDurationS + durationS;
    end
    [segments, segmentGroups] = append_movement_run( ...
        segments, segmentGroups, segmentTemplate, groupTemplate, ...
        runQ, runT, runStepIndices, runProvenance, sourceIndex, motionPlan);
    finalQ = currentQ;
    timed = struct( ...
        'artifact_type', 'TimedJointTrajectory', ...
        'robot_id', robotContext.id, ...
        'segments', segments);
end

function [refined, refinedGroups, guardedSegments, guardEvidence] = refine_unsafe_movement_runs( ...
        timed, groups, motionPlan, timingConfig, robotContext)
% Retain a maximal run when a local Banter quintic boundary guard removes its
% overshoot.  The frozen Stage 3 generator remains the baseline and all
% ordinary/fallback pieces still use it unchanged.
    segmentTemplate = timed.segments(1);
    groupTemplate = groups(1);
    segments = repmat(segmentTemplate, 1, 0);
    refinedGroups = repmat(groupTemplate, 1, 0);
    guardedSegments = cell(1, 0);
    guardEvidence = repmat(empty_guard_evidence(), 1, 0);
    for index = 1:numel(timed.segments)
        segment = timed.segments(index);
        group = groups(index);
        baseline = generate_single_timed_segment(segment, timingConfig, robotContext);
        unsafeMoveRun = strcmp(group.kind, 'MOVE_RUN') && ...
            ~is_continuous_segment_safe(baseline);
        if unsafeMoveRun
            guarded = generate_guarded_banter_quintic_segment( ...
                segment, baseline, timingConfig, robotContext);
            if guarded.applied
                group.segmentation_reason = 'BANTER_LOCAL_BOUNDARY_GUARD';
                segments(end + 1) = segment;
                refinedGroups(end + 1) = group;
                guardedSegments{end + 1} = guarded.segment; %#ok<AGROW>
                guardEvidence(end + 1) = guard_evidence_record( ...
                    'APPLIED', guarded.evidence); %#ok<AGROW>
                continue;
            end
            [safeSegments, safeRanges] = minimum_safe_movement_partition( ...
                segment, timingConfig, robotContext);
            for partitionIndex = 1:numel(safeSegments)
                subsegment = safeSegments(partitionIndex);
                startWaypoint = safeRanges(partitionIndex, 1);
                endWaypoint = safeRanges(partitionIndex, 2);
                subGroup = group;
                subGroup.source_step_indices = group.source_step_indices( ...
                    startWaypoint:endWaypoint - 1);
                subGroup.requested_duration_s = subsegment.t_s(end);
                subGroup.segmentation_reason = 'STAGE3_SAFETY';
                segments(end + 1) = subsegment;
                refinedGroups(end + 1) = subGroup;
                guardedSegments{end + 1} = []; %#ok<AGROW>
                guardEvidence(end + 1) = guard_evidence_record( ...
                    'FALLBACK_SPLIT', guarded.evidence); %#ok<AGROW>
            end
        else
            segments(end + 1) = segment;
            refinedGroups(end + 1) = group;
            guardedSegments{end + 1} = []; %#ok<AGROW>
            if strcmp(group.kind, 'MOVE_RUN')
                guardEvidence(end + 1) = guard_evidence_record( ...
                    'NOT_NEEDED', baseline.overshoot_evidence); %#ok<AGROW>
            else
                guardEvidence(end + 1) = guard_evidence_record( ...
                    'HOLD_NOT_APPLICABLE', baseline.overshoot_evidence); %#ok<AGROW>
            end
        end
    end
    for index = 1:numel(segments)
        segmentId = double(motionPlan.plan_id) * 1000 + index;
        segments(index).segment_index = segmentId;
        segments(index).ik_success_segment_index = segmentId;
        segments(index).preik_segment_index = segmentId;
        refinedGroups(index).group_index = index;
        if ~isempty(guardedSegments{index})
            guardedSegments{index}.segment_index = segmentId;
            guardedSegments{index}.ik_success_segment_index = segmentId;
            guardedSegments{index}.preik_segment_index = segmentId;
        end
    end
    refined = timed;
    refined.segments = segments;
end

function continuous = apply_guarded_banter_segments(continuous, guardedSegments, config)
    applied = false;
    for index = 1:numel(guardedSegments)
        if isempty(guardedSegments{index})
            continue;
        end
        continuous.segments(index) = guardedSegments{index};
        applied = true;
    end
    if applied
        continuous.summary = summarize_banter_continuous_segments( ...
            continuous.segments, config);
    end
end

function summary = summarize_banter_continuous_segments(segments, config)
    summary = struct('continuous_segment_count', numel(segments), ...
        'continuous_sample_count', sum(arrayfun(@(item) numel(item.t_s), segments)), ...
        'total_independent_duration_s', sum([segments.duration_s]), ...
        'max_velocity_rad_s', config.max_velocity_rad_s, ...
        'max_acceleration_rad_s2', config.max_acceleration_rad_s2, ...
        'time_allocation_optimized', false, ...
        'max_observed_abs_velocity_rad_s', max(vertcat( ...
            segments.max_observed_abs_velocity_rad_s), [], 1), ...
        'max_observed_abs_acceleration_rad_s2', max(vertcat( ...
            segments.max_observed_abs_acceleration_rad_s2), [], 1), ...
        'max_observed_abs_jerk_rad_s3', max(vertcat( ...
            segments.max_observed_abs_jerk_rad_s3), [], 1), ...
        'all_safety_checks_satisfied', all([segments.all_safety_checks_satisfied]), ...
        'all_joint_limits_satisfied', all([segments.joint_limits_satisfied]), ...
        'max_joint_overshoot_rad', max(arrayfun(@(item) ...
            item.overshoot_evidence.max_overshoot_magnitude_rad, segments)));
end

function continuousSegment = generate_single_timed_segment(segment, config, context)
    timed = struct('artifact_type', 'TimedJointTrajectory', ...
        'robot_id', context.id, 'segments', segment);
    continuous = generate_quintic_continuous_joint_trajectory(timed, config, context);
    continuousSegment = continuous.segments;
end

function safe = is_continuous_segment_safe(segment)
    safe = segment.all_safety_checks_satisfied && ...
        ~segment.overshoot_evidence.has_overshoot;
end

function record = empty_guard_evidence()
    record = struct('status', '', 'method', '', 'stage', '', ...
        'overshoot_before', struct(), 'overshoot_after', struct(), ...
        'affected_joint_waypoint_indices', zeros(0, 2), ...
        'reversal_joint_waypoint_indices', zeros(0, 2), ...
        'velocity_boundary_before_rad_s', zeros(0, 5), ...
        'velocity_boundary_after_rad_s', zeros(0, 5), ...
        'acceleration_boundary_before_rad_s2', zeros(0, 5), ...
        'acceleration_boundary_after_rad_s2', zeros(0, 5), ...
        'velocity_zeroed_mask', false(0, 5), ...
        'acceleration_damping_factor', zeros(0, 5));
end

function record = guard_evidence_record(status, evidence)
    record = empty_guard_evidence();
    record.status = status;
    if isstruct(evidence) && isfield(evidence, 'method')
        fields = fieldnames(record);
        for index = 1:numel(fields)
            field = fields{index};
            if isfield(evidence, field)
                record.(field) = evidence.(field);
            end
        end
    elseif isstruct(evidence)
        record.overshoot_before = evidence;
        record.overshoot_after = evidence;
    end
end

function [safeSegments, safeRanges] = minimum_safe_movement_partition( ...
        segment, timingConfig, robotContext)
    waypointCount = size(segment.q_rad, 1);
    safe = false(waypointCount, waypointCount);
    candidates = cell(waypointCount, waypointCount);
    for startWaypoint = 1:waypointCount - 1
        for endWaypoint = startWaypoint + 1:waypointCount
            candidate = slice_movement_segment(segment, startWaypoint, endWaypoint);
            candidates{startWaypoint, endWaypoint} = candidate;
            safe(startWaypoint, endWaypoint) = is_timed_segment_safe( ...
                candidate, timingConfig, robotContext);
        end
    end

    minimumSegments = inf(1, waypointCount);
    predecessor = zeros(1, waypointCount);
    minimumSegments(1) = 0;
    for endWaypoint = 2:waypointCount
        for startWaypoint = 1:endWaypoint - 1
            if safe(startWaypoint, endWaypoint) && ...
                    minimumSegments(startWaypoint) + 1 < minimumSegments(endWaypoint)
                minimumSegments(endWaypoint) = minimumSegments(startWaypoint) + 1;
                predecessor(endWaypoint) = startWaypoint;
            end
        end
    end
    if ~isfinite(minimumSegments(end))
        error('MonoTeach:BanterUnsafeMotion', ...
            'No safe Stage 3 partition exists for a Banter movement run.');
    end
    reverseSegments = cell(1, 0);
    reverseRanges = zeros(0, 2);
    endWaypoint = waypointCount;
    while endWaypoint > 1
        startWaypoint = predecessor(endWaypoint);
        reverseSegments{end + 1} = candidates{startWaypoint, endWaypoint};
        reverseRanges(end + 1, :) = [startWaypoint, endWaypoint];
        endWaypoint = startWaypoint;
    end
    safeSegments = fliplr([reverseSegments{:}]);
    safeRanges = flipud(reverseRanges);
end

function safe = is_timed_segment_safe(segment, timingConfig, robotContext)
    candidate = struct( ...
        'artifact_type', 'TimedJointTrajectory', ...
        'robot_id', robotContext.id, ...
        'segments', segment);
    continuous = generate_quintic_continuous_joint_trajectory( ...
        candidate, timingConfig, robotContext);
    evidence = continuous.segments.overshoot_evidence;
    safe = continuous.segments.all_safety_checks_satisfied && ~evidence.has_overshoot;
end

function sliced = slice_movement_segment(segment, startWaypoint, endWaypoint)
    sliced = segment;
    sliced.q_rad = segment.q_rad(startWaypoint:endWaypoint, :);
    sliced.t_s = segment.t_s(startWaypoint:endWaypoint) - segment.t_s(startWaypoint);
    sliced.waypoints = segment.waypoints(startWaypoint:endWaypoint);
end


function [runQ, runT, runStepIndices, runProvenance] = start_movement_run( ...
        currentQ, motionPlan, precedingHoldStepIndex)
    runQ = currentQ;
    runT = 0.0;
    runStepIndices = zeros(1, 0);
    if precedingHoldStepIndex == 0
        startLabel = 'home';
    else
        startLabel = sprintf('after_hold_%d', precedingHoldStepIndex);
    end
    runProvenance = {sprintf('behavior_%d_%s_run_start_%s', ...
        double(motionPlan.source_behavior.behavior_id), ...
        char(string(motionPlan.macro_name)), startLabel)};
end

function [segments, groups] = append_movement_run( ...
        segments, groups, segmentTemplate, groupTemplate, runQ, runT, ...
        runStepIndices, runProvenance, sourceIndex, motionPlan)
    if isempty(runStepIndices)
        return;
    end
    groupIndex = numel(groups) + 1;
    segmentId = double(motionPlan.plan_id) * 1000 + groupIndex;
    segments(end + 1) = struct( ...
        'segment_index', segmentId, ...
        'ik_success_segment_index', segmentId, ...
        'preik_segment_index', segmentId, ...
        'source_indices', sourceIndex, ...
        'waypoints', make_waypoints(runProvenance), ...
        'q_rad', runQ, ...
        't_s', runT);
    groups(end + 1) = struct( ...
        'group_index', groupIndex, ...
        'kind', 'MOVE_RUN', ...
        'source_step_indices', runStepIndices, ...
        'requested_duration_s', runT(end), ...
        'segmentation_reason', 'MAXIMAL_NONHOLD_RUN');
end

function [segments, groups] = append_hold_segment( ...
        segments, groups, segmentTemplate, groupTemplate, currentQ, durationS, ...
        stepIndex, provenance, sourceIndex, motionPlan)
    groupIndex = numel(groups) + 1;
    segmentId = double(motionPlan.plan_id) * 1000 + groupIndex;
    segments(end + 1) = struct( ...
        'segment_index', segmentId, ...
        'ik_success_segment_index', segmentId, ...
        'preik_segment_index', segmentId, ...
        'source_indices', sourceIndex, ...
        'waypoints', make_waypoints({[provenance '_start']; provenance}), ...
        'q_rad', [currentQ; currentQ], ...
        't_s', [0.0; durationS]);
    groups(end + 1) = struct( ...
        'group_index', groupIndex, ...
        'kind', 'HOLD', ...
        'source_step_indices', stepIndex, ...
        'requested_duration_s', durationS, ...
        'segmentation_reason', 'EXPLICIT_HOLD');
end

function waypoints = make_waypoints(provenance)
    waypoints = repmat(struct('provenance', ''), numel(provenance), 1);
    for index = 1:numel(provenance)
        waypoints(index).provenance = provenance{index};
    end
end

function validate_motion_plan(plan)
    required = {'schema_version', 'plan_id', 'source_behavior', 'macro_name', ...
        'variant', 'motion_steps', 'available_t_ms'};
    if ~isstruct(plan) || ~isscalar(plan) || ~all(isfield(plan, required)) || ...
            ~strcmp(string(plan.schema_version), "banter_motion_plan_v1") || ...
            ~isscalar(plan.plan_id) || ~isfinite(double(plan.plan_id)) || ...
            double(plan.plan_id) < 1 || double(plan.plan_id) ~= floor(double(plan.plan_id)) || ...
            ~isstruct(plan.source_behavior) || ~isfield(plan.source_behavior, 'behavior_id') || ...
            ~isstruct(plan.motion_steps) || isempty(plan.motion_steps)
        error('MonoTeach:BanterInvalidMotionPlan', ...
            'Task 5 requires one valid JSON-decoded banter_motion_plan_v1 struct.');
    end
    if ~strcmp(string(plan.motion_steps(end).kind), "RETURN_NEUTRAL") || ...
            ~strcmp(string(plan.motion_steps(end).target_pose_name), "NEUTRAL")
        error('MonoTeach:BanterInvalidMotionPlanReturn', ...
            'MotionPlan must end with RETURN_NEUTRAL targeting NEUTRAL.');
    end
    for index = 1:numel(plan.motion_steps)
        step = plan.motion_steps(index);
        if ~all(isfield(step, {'kind', 'target_pose_name', 'duration_ms'})) || ...
                ~any(strcmp(string(step.kind), ["MOVE_POSE", "HOLD", "RETURN_NEUTRAL"])) || ...
                ~isfinite(double(step.duration_ms)) || double(step.duration_ms) <= 0
            error('MonoTeach:BanterInvalidMotionStep', ...
                'Every MotionPlan step requires a finite positive duration.');
        end
    end
end
