function result = generate_guarded_banter_quintic_segment( ...
        timedSegment, baselineSegment, timingConfig, robotContext)
%GENERATE_GUARDED_BANTER_QUINTIC_SEGMENT Local overshoot guard for Banter runs.
%   This is a Banter-only adapter over MATLAB quinticpolytraj.  It keeps every
%   named waypoint and the existing Stage 3 timing limits unchanged.  It is
%   called only after the frozen Stage 3 quintic has rejected a maximal MOVE
%   run for sampled joint-envelope overshoot.  Reversal qd is zeroed first;
%   only then are affected qdd boundaries deterministically damped.

    validate_inputs(timedSegment, baselineSegment, timingConfig, robotContext);
    before = baselineSegment.overshoot_evidence;
    result = empty_result(baselineSegment, before, robotContext.dof);
    if ~before.has_overshoot
        result.status = 'NOT_NEEDED';
        return;
    end

    [affected, reversal] = affected_boundary_points( ...
        before.records, timedSegment.q_rad);
    qdZeroMask = affected & reversal;
    if ~any(qdZeroMask, 'all')
        result.status = 'NO_REVERSAL_BOUNDARY';
        result.evidence.affected_joint_waypoint_indices = find_indices(affected);
        return;
    end

    current = baselineSegment;
    currentEvidence = before;
    qddDamping = ones(size(affected));
    candidate = generate_candidate(timedSegment, qdZeroMask, qddDamping, ...
        timingConfig, robotContext);
    if banter_overshoot_evidence_is_better(candidate.overshoot_evidence, currentEvidence) && ...
            candidate.all_safety_checks_satisfied
        current = candidate;
        currentEvidence = candidate.overshoot_evidence;
        if ~currentEvidence.has_overshoot
            result = accepted_result(result, baselineSegment, current, before, ...
                affected, reversal, qdZeroMask, qddDamping, 'REVERSAL_QD_ZERO');
            return;
        end
    else
        result.status = 'QD_ZERO_NOT_ACCEPTED';
        result.evidence.affected_joint_waypoint_indices = find_indices(affected);
        result.evidence.reversal_joint_waypoint_indices = find_indices(qdZeroMask);
        return;
    end

    % The exact sequence is intentionally small and deterministic.  It uses
    % the existing Stage 3 default factor first, then one stronger step, then
    % zero acceleration as the final local limit.
    for factor = [0.5, 0.25, 0.0]
        candidateDamping = ones(size(affected));
        candidateDamping(affected) = factor;
        candidate = generate_candidate(timedSegment, qdZeroMask, candidateDamping, ...
            timingConfig, robotContext);
        if ~banter_overshoot_evidence_is_better(candidate.overshoot_evidence, currentEvidence) || ...
                ~candidate.all_safety_checks_satisfied
            continue;
        end
        current = candidate;
        currentEvidence = candidate.overshoot_evidence;
        qddDamping = candidateDamping;
        if ~currentEvidence.has_overshoot
            result = accepted_result(result, baselineSegment, current, before, ...
                affected, reversal, qdZeroMask, qddDamping, ...
                sprintf('REVERSAL_QD_ZERO_QDD_DAMP_%.2f', factor));
            return;
        end
    end
    result.status = 'QDD_DAMPING_INSUFFICIENT';
    result.evidence.affected_joint_waypoint_indices = find_indices(affected);
    result.evidence.reversal_joint_waypoint_indices = find_indices(qdZeroMask);
    result.evidence.overshoot_after = currentEvidence;
end

function candidate = generate_candidate(timedSegment, qdZeroMask, qddDamping, config, context)
    initialTimes = timedSegment.t_s(:)';
    currentTimes = initialTimes;
    initialDuration = initialTimes(end) - initialTimes(1);
    initialVelocityRatio = NaN;
    initialAccelerationRatio = NaN;
    initialPeakVelocity = NaN(1, context.dof);
    initialPeakAcceleration = NaN(1, context.dof);
    for iteration = 0:config.max_time_stretch_iterations
        [baseQd, baseQdd] = finite_difference_boundaries( ...
            timedSegment.q_rad, currentTimes);
        qdBoundary = baseQd;
        qddBoundary = baseQdd;
        qdBoundary(qdZeroMask) = 0.0;
        qddBoundary = qddBoundary .* qddDamping;
        generated = evaluate_profile(timedSegment.q_rad, currentTimes, ...
            qdBoundary, qddBoundary, config);
        evidence = safety_evidence(generated, config, context.joint_limits);
        if iteration == 0
            initialVelocityRatio = evidence.velocity_ratio;
            initialAccelerationRatio = evidence.acceleration_ratio;
            initialPeakVelocity = evidence.peak_velocity_rad_s;
            initialPeakAcceleration = evidence.peak_acceleration_rad_s2;
        end
        if evidence.velocity_limits_satisfied && evidence.acceleration_limits_satisfied
            candidate = assemble_segment(timedSegment, generated, initialTimes, ...
                currentTimes, initialDuration, iteration, evidence, ...
                initialVelocityRatio, initialAccelerationRatio, ...
                initialPeakVelocity, initialPeakAcceleration);
            return;
        end
        if iteration == config.max_time_stretch_iterations
            error('MonoTeach:BanterGuardTimeStretchLimit', ...
                'Local Banter quintic guard exceeded the existing Stage 3 stretch cap.');
        end
        scale = max([1.0, evidence.velocity_ratio, sqrt(evidence.acceleration_ratio)]);
        currentTimes = currentTimes(1) + (currentTimes - currentTimes(1)) * ...
            (scale * (1.0 + 1.0e-10));
    end
end

function generated = evaluate_profile(waypointQ, waypointTimes, velocityBoundary, accelerationBoundary, config)
    sampleTimes = trajectory_sample_times(waypointTimes, config.continuous_sample_period_s);
    [~, ~, ~, pp] = quinticpolytraj(waypointQ', waypointTimes, sampleTimes, ...
        VelocityBoundaryCondition=velocityBoundary', ...
        AccelerationBoundaryCondition=accelerationBoundary');
    guardTimes = trajectory_sample_times(waypointTimes, config.overshoot_guard_sample_period_s);
    generated = struct( ...
        'sample_t_s', sampleTimes(:), ...
        'q_rad', ppval(pp, sampleTimes)', ...
        'qd_rad_s', ppval(fnder(pp, 1), sampleTimes)', ...
        'qdd_rad_s2', ppval(fnder(pp, 2), sampleTimes)', ...
        'qddd_rad_s3', ppval(fnder(pp, 3), sampleTimes)', ...
        'waypoint_qd_rad_s', ppval(fnder(pp, 1), waypointTimes)', ...
        'waypoint_qdd_rad_s2', ppval(fnder(pp, 2), waypointTimes)', ...
        'velocity_boundary_condition_rad_s', velocityBoundary, ...
        'acceleration_boundary_condition_rad_s2', accelerationBoundary, ...
        'piecewise_polynomial', pp, ...
        'overshoot_evidence', detect_joint_interval_overshoot( ...
            guardTimes, ppval(pp, guardTimes)', waypointTimes(:), waypointQ, ...
            config.overshoot_numerical_epsilon_rad));
end

function [velocity, acceleration] = finite_difference_boundaries(waypointQ, times)
    count = size(waypointQ, 1);
    velocity = zeros(count, size(waypointQ, 2));
    acceleration = zeros(count, size(waypointQ, 2));
    for index = 2:count - 1
        previousDt = times(index) - times(index - 1);
        nextDt = times(index + 1) - times(index);
        velocity(index, :) = (waypointQ(index + 1, :) - waypointQ(index - 1, :)) / ...
            (times(index + 1) - times(index - 1));
        acceleration(index, :) = 2.0 * ( ...
            (waypointQ(index + 1, :) - waypointQ(index, :)) / nextDt - ...
            (waypointQ(index, :) - waypointQ(index - 1, :)) / previousDt) / ...
            (previousDt + nextDt);
    end
end

function evidence = safety_evidence(generated, config, limits)
    evidence = struct();
    evidence.peak_velocity_rad_s = max(abs(generated.qd_rad_s), [], 1);
    evidence.peak_acceleration_rad_s2 = max(abs(generated.qdd_rad_s2), [], 1);
    evidence.velocity_ratio = max(evidence.peak_velocity_rad_s ./ config.max_velocity_rad_s);
    evidence.acceleration_ratio = max(evidence.peak_acceleration_rad_s2 ./ config.max_acceleration_rad_s2);
    evidence.velocity_limits_satisfied = evidence.velocity_ratio <= 1.0 + 1.0e-10;
    evidence.acceleration_limits_satisfied = evidence.acceleration_ratio <= 1.0 + 1.0e-10;
    evidence.within_joint_limits = all(generated.q_rad >= limits(:, 1)' - 1.0e-10 & ...
        generated.q_rad <= limits(:, 2)' + 1.0e-10, 2);
    evidence.joint_limit_margin = min(generated.q_rad - limits(:, 1)', ...
        limits(:, 2)' - generated.q_rad);
    evidence.minimum_joint_limit_margin = min(evidence.joint_limit_margin, [], 'all');
    evidence.joint_limits_satisfied = all(evidence.within_joint_limits);
    evidence.all_finite = all(isfinite(generated.q_rad), 'all') && ...
        all(isfinite(generated.qd_rad_s), 'all') && ...
        all(isfinite(generated.qdd_rad_s2), 'all') && ...
        all(isfinite(generated.qddd_rad_s3), 'all');
    evidence.all_safety_checks_satisfied = evidence.all_finite && ...
        evidence.velocity_limits_satisfied && evidence.acceleration_limits_satisfied && ...
        evidence.joint_limits_satisfied;
    evidence.overshoot_evidence = generated.overshoot_evidence;
end

function segment = assemble_segment(timedSegment, generated, initialTimes, finalTimes, ...
        initialDuration, iteration, evidence, initialVelocityRatio, initialAccelerationRatio, ...
        initialPeakVelocity, initialPeakAcceleration)
    segment = struct( ...
        'segment_index', timedSegment.segment_index, ...
        'ik_success_segment_index', timedSegment.ik_success_segment_index, ...
        'preik_segment_index', timedSegment.preik_segment_index, ...
        'source_indices', timedSegment.source_indices, ...
        'waypoint_q_rad', timedSegment.q_rad, ...
        'initial_waypoint_t_s', initialTimes(:), ...
        'waypoint_t_s', finalTimes(:), ...
        'waypoint_indices', (1:numel(finalTimes))', ...
        'waypoint_provenance', {cell(0, 1)}, ...
        'waypoint_qd_rad_s', generated.waypoint_qd_rad_s, ...
        'waypoint_qdd_rad_s2', generated.waypoint_qdd_rad_s2, ...
        'velocity_boundary_condition_rad_s', generated.velocity_boundary_condition_rad_s, ...
        'acceleration_boundary_condition_rad_s2', generated.acceleration_boundary_condition_rad_s2, ...
        't_s', generated.sample_t_s, 'q_rad', generated.q_rad, ...
        'qd_rad_s', generated.qd_rad_s, 'qdd_rad_s2', generated.qdd_rad_s2, ...
        'qddd_rad_s3', generated.qddd_rad_s3, ...
        'piecewise_polynomial', generated.piecewise_polynomial, ...
        'overshoot_evidence', evidence.overshoot_evidence, ...
        'initial_duration_s', initialDuration, ...
        'duration_s', finalTimes(end) - finalTimes(1), ...
        'time_stretch_iterations', iteration, ...
        'time_stretch_factor', (finalTimes(end) - finalTimes(1)) / initialDuration, ...
        'was_time_stretched', iteration > 0, ...
        'initial_velocity_limit_ratio', initialVelocityRatio, ...
        'initial_acceleration_limit_ratio', initialAccelerationRatio, ...
        'initial_peak_velocity_rad_s', initialPeakVelocity, ...
        'initial_peak_acceleration_rad_s2', initialPeakAcceleration, ...
        'max_observed_abs_velocity_rad_s', evidence.peak_velocity_rad_s, ...
        'max_observed_abs_acceleration_rad_s2', evidence.peak_acceleration_rad_s2, ...
        'max_observed_abs_jerk_rad_s3', max(abs(generated.qddd_rad_s3), [], 1), ...
        'velocity_limits_satisfied', evidence.velocity_limits_satisfied, ...
        'acceleration_limits_satisfied', evidence.acceleration_limits_satisfied, ...
        'within_joint_limits', evidence.within_joint_limits, ...
        'joint_limit_margin', evidence.joint_limit_margin, ...
        'minimum_joint_limit_margin', evidence.minimum_joint_limit_margin, ...
        'joint_limits_satisfied', evidence.joint_limits_satisfied, ...
        'all_safety_checks_satisfied', evidence.all_safety_checks_satisfied);
    segment.waypoint_provenance = {timedSegment.waypoints.provenance}';
end

function [affected, reversal] = affected_boundary_points(records, waypointQ)
    affected = false(size(waypointQ));
    reversal = false(size(waypointQ));
    for index = 1:numel(records)
        record = records(index);
        for waypoint = [record.interval_index, record.interval_index + 1]
            if waypoint <= 1 || waypoint >= size(waypointQ, 1)
                continue;
            end
            joint = record.joint_index;
            affected(waypoint, joint) = true;
            before = waypointQ(waypoint, joint) - waypointQ(waypoint - 1, joint);
            after = waypointQ(waypoint + 1, joint) - waypointQ(waypoint, joint);
            reversal(waypoint, joint) = reversal(waypoint, joint) || before * after <= 0.0;
        end
    end
end

function result = accepted_result(result, baseline, candidate, before, affected, reversal, ...
        qdZeroMask, qddDamping, stage)
    result.applied = true;
    result.status = 'APPLIED';
    result.segment = candidate;
    result.evidence = struct( ...
        'method', 'BANTER_QUINTIC_LOCAL_BOUNDARY_GUARD_V1', ...
        'stage', stage, 'overshoot_before', before, ...
        'overshoot_after', candidate.overshoot_evidence, ...
        'affected_joint_waypoint_indices', find_indices(affected), ...
        'reversal_joint_waypoint_indices', find_indices(reversal), ...
        'velocity_boundary_before_rad_s', baseline.velocity_boundary_condition_rad_s, ...
        'velocity_boundary_after_rad_s', candidate.velocity_boundary_condition_rad_s, ...
        'acceleration_boundary_before_rad_s2', baseline.acceleration_boundary_condition_rad_s2, ...
        'acceleration_boundary_after_rad_s2', candidate.acceleration_boundary_condition_rad_s2, ...
        'velocity_zeroed_mask', qdZeroMask, ...
        'acceleration_damping_factor', qddDamping);
end

function result = empty_result(baseline, before, dof)
    result = struct('applied', false, 'status', 'NOT_ATTEMPTED', ...
        'segment', baseline, 'evidence', struct( ...
            'method', 'BANTER_QUINTIC_LOCAL_BOUNDARY_GUARD_V1', ...
            'stage', '', 'overshoot_before', before, 'overshoot_after', before, ...
            'affected_joint_waypoint_indices', zeros(0, 2), ...
            'reversal_joint_waypoint_indices', zeros(0, 2), ...
            'velocity_boundary_before_rad_s', zeros(0, dof), ...
            'velocity_boundary_after_rad_s', zeros(0, dof), ...
            'acceleration_boundary_before_rad_s2', zeros(0, dof), ...
            'acceleration_boundary_after_rad_s2', zeros(0, dof), ...
            'velocity_zeroed_mask', false(0, dof), ...
            'acceleration_damping_factor', zeros(0, dof)));
end

function better = banter_overshoot_evidence_is_better(candidate, incumbent)
    tolerance = 1.0e-15;
    better = candidate.max_overshoot_magnitude_rad < ...
        incumbent.max_overshoot_magnitude_rad - tolerance || ...
        (abs(candidate.max_overshoot_magnitude_rad - ...
        incumbent.max_overshoot_magnitude_rad) <= tolerance && ...
        candidate.count < incumbent.count);
end

function indices = find_indices(mask)
    [waypoint, joint] = find(mask);
    indices = [joint, waypoint];
end

function times = trajectory_sample_times(waypointTimes, period)
    times = unique([waypointTimes(1):period:waypointTimes(end), ...
        waypointTimes, waypointTimes(end)]);
end

function validate_inputs(timed, baseline, config, context)
    requiredTimed = {'segment_index', 'ik_success_segment_index', ...
        'preik_segment_index', 'source_indices', 'waypoints', 'q_rad', 't_s'};
    requiredBaseline = {'overshoot_evidence', ...
        'velocity_boundary_condition_rad_s', 'acceleration_boundary_condition_rad_s2'};
    if ~isstruct(timed) || ~isscalar(timed) || ...
            ~all(isfield(timed, requiredTimed)) || size(timed.q_rad, 1) < 3 || ...
            ~isstruct(baseline) || ~isscalar(baseline) || ...
            ~all(isfield(baseline, requiredBaseline)) || ...
            ~isstruct(config) || ~all(isfield(config, ...
            {'max_velocity_rad_s', 'max_acceleration_rad_s2', ...
            'continuous_sample_period_s', 'overshoot_guard_sample_period_s', ...
            'overshoot_numerical_epsilon_rad', 'max_time_stretch_iterations'})) || ...
            ~isstruct(context) || ~all(isfield(context, {'dof', 'joint_limits'}))
        error('MonoTeach:BanterInvalidGuardInput', ...
            'Banter local quintic guard requires one unsafe multi-waypoint run.');
    end
end
