function demo = demo_real_position_only_timed_animation(jsonPath, playbackRate)
%DEMO_REAL_POSITION_ONLY_TIMED_ANIMATION Timed Legacy5 E2E visualization.
%
% playbackRate changes wall-clock display speed only; q(t) and t_s remain the
% untouched Quintic V1 artifact generated by run_real_position_only_timed_e2e.

    if nargin < 2 || isempty(playbackRate), playbackRate = 1.0; end
    if nargin < 1, jsonPath = []; end
    if ~isscalar(playbackRate) || ~isfinite(playbackRate) || playbackRate <= 0
        error('MonoTeach:InvalidAnimationPlaybackRate', ...
            'playbackRate must be a finite positive scalar.');
    end
    if isempty(jsonPath)
        e2e = run_real_position_only_timed_e2e();
    else
        e2e = run_real_position_only_timed_e2e(jsonPath);
    end
    validate_animation_input(e2e);

    segment = e2e.continuous_joint_trajectory.segments(1);
    geometry = e2e.position_only_geometry;
    robot = e2e.robot_context.model;
    figureHandle = figure('Name', 'MonoTeach Stage 3.3 Position-Only Timed E2E');
    axesHandle = axes(figureHandle);
    hold(axesHandle, 'on'); grid(axesHandle, 'on'); axis(axesHandle, 'equal');
    plot3(axesHandle, geometry.reference_xyz_m(:,1), geometry.reference_xyz_m(:,2), ...
        geometry.reference_xyz_m(:,3), 'k--', 'LineWidth', 1.4, ...
        'DisplayName', 'Desired Position-Only task path');
    trailHandle = plot3(axesHandle, NaN, NaN, NaN, 'g-', 'LineWidth', 1.8, ...
        'DisplayName', 'Executed FK trail');
    xlabel(axesHandle, 'Base X [m]'); ylabel(axesHandle, 'Base Y [m]');
    zlabel(axesHandle, 'Base Z [m]');
    title(axesHandle, 'Legacy5 Position-Only Quintic V1 timed playback');

    textHandle = text(axesHandle, 0.02, 0.98, '', 'Units', 'normalized', ...
        'VerticalAlignment', 'top', 'FontWeight', 'bold');
    robotDisplayPoints = robot_display_points(robot, segment.q_rad);
    displayPoints = [geometry.reference_xyz_m; geometry.fk_xyz_m; robotDisplayPoints];
    set_base_limits(axesHandle, displayPoints);

    robotHandles = render_robot(robot, segment.q_rad(1, :), axesHandle);
    skeletonHandle = render_legacy5_skeleton(robot, segment.q_rad(1, :), axesHandle);
    axis(axesHandle, 'equal');
    set_base_limits(axesHandle, displayPoints);
    view(axesHandle, 3);
    startTime = segment.t_s(1);
    wallClock = tic;
    for index = 1:numel(segment.t_s)
        desiredWallTime = (segment.t_s(index) - startTime) / playbackRate;
        remaining = desiredWallTime - toc(wallClock);
        if remaining > 0, pause(remaining); end
        delete(robotHandles(isgraphics(robotHandles)));
        robotHandles = render_robot(robot, segment.q_rad(index, :), axesHandle);
        update_legacy5_skeleton(skeletonHandle, robot, segment.q_rad(index, :));
        axis(axesHandle, 'equal');
        set_base_limits(axesHandle, displayPoints);
        view(axesHandle, 3);
        set(trailHandle, 'XData', geometry.fk_xyz_m(1:index,1), ...
            'YData', geometry.fk_xyz_m(1:index,2), ...
            'ZData', geometry.fk_xyz_m(1:index,3));
        set(textHandle, 'String', sprintf('t = %.3f / %.3f s  |  playback %.2fx', ...
            segment.t_s(index), segment.t_s(end), playbackRate));

        drawnow;
    end
    demo = struct('e2e', e2e, 'playback_rate', playbackRate, ...
        'figure', figureHandle, 'axes', axesHandle, ...
        'robot_skeleton', skeletonHandle, 'executed_fk_trail', trailHandle);
end


function validate_animation_input(e2e)

    required = {'execution_baseline', 'continuous_joint_trajectory', ...
        'position_only_geometry', 'summary'};
    if ~isstruct(e2e) || ~all(isfield(e2e, required)) || ...
            ~strcmp(string(e2e.execution_baseline), ...
                'position_only_29_of_29_real_2mm_triangle') || ...
            e2e.summary.position_only_success_point_count ~= 29 || ...
            e2e.summary.position_only_failure_count ~= 0 || ...
            e2e.summary.execution_segment_count ~= 1 || ...
            ~e2e.summary.velocity_limits_satisfied || ...
            ~e2e.summary.acceleration_limits_satisfied || ...
            ~e2e.summary.joint_limits_satisfied
        error('MonoTeach:InvalidPositionOnlyAnimationInput', ...
            'Animation requires the validated one-segment Position-Only E2E artifact.');
    end
end


function set_base_limits(ax, points)

    lower = min(points, [], 1); upper = max(points, [], 1);
    padding = max(0.15 * (upper - lower), 0.02);
    xlim(ax, [lower(1) - padding(1), upper(1) + padding(1)]);
    ylim(ax, [lower(2) - padding(2), upper(2) + padding(2)]);
    zlim(ax, [lower(3) - padding(3), upper(3) + padding(3)]);
end


function points = robot_display_points(robot, qTrajectory)

    bodyCount = robot.NumBodies;
    sampleIndices = unique([1:10:size(qTrajectory, 1), size(qTrajectory, 1)]);
    points = zeros(1 + numel(sampleIndices) * bodyCount, 3);
    nextIndex = 1;
    points(nextIndex, :) = [0, 0, 0];
    for sampleIndex = sampleIndices
        q = qTrajectory(sampleIndex, :);
        for bodyIndex = 1:bodyCount
            nextIndex = nextIndex + 1;
            pose = getTransform(robot, q, robot.Bodies{bodyIndex}.Name);
            points(nextIndex, :) = pose(1:3, 4)';
        end
    end
    points = points(1:nextIndex, :);
end

function robotHandles = render_robot(robot, q, ax)

    existingChildren = ax.Children;
    show(robot, q, 'Parent', ax, 'PreservePlot', true, 'Frames', 'off');
    currentChildren = ax.Children;
    robotHandles = currentChildren(~ismember(currentChildren, existingChildren));
end

function skeletonHandle = render_legacy5_skeleton(robot, q, ax)

    points = body_origin_points(robot, q);
    skeletonHandle = plot3(ax, points(:,1), points(:,2), points(:,3), '-o', ...
        'Color', [0.10, 0.35, 0.85], 'LineWidth', 5.0, 'MarkerSize', 8.0, ...
        'MarkerFaceColor', [1.00, 0.55, 0.10], 'MarkerEdgeColor', [0.05, 0.05, 0.05], ...
        'HandleVisibility', 'off');
end


function update_legacy5_skeleton(skeletonHandle, robot, q)

    points = body_origin_points(robot, q);
    set(skeletonHandle, 'XData', points(:,1), 'YData', points(:,2), ...
        'ZData', points(:,3));
end


function points = body_origin_points(robot, q)

    points = zeros(robot.NumBodies + 1, 3);
    for bodyIndex = 1:robot.NumBodies
        pose = getTransform(robot, q, robot.Bodies{bodyIndex}.Name);
        points(bodyIndex + 1, :) = pose(1:3, 4)';
    end
end
