function demo = demo_quintic_continuous_writing_geometry(jsonPath, timingConfig)
%DEMO_QUINTIC_CONTINUOUS_WRITING_GEOMETRY Longest real 2 mm segment FK check.

    if nargin < 2 || isempty(timingConfig)
        timingConfig = default_timed_joint_trajectory_config();
    end
    if nargin < 1, jsonPath = []; end
    if isempty(jsonPath)
        run = run_real_resampled_task_path_ik_ab();
    else
        run = run_real_resampled_task_path_ik_ab(jsonPath);
    end
    robot = build_legacy_robot();
    timed = time_parameterize_ik_success_segments( ...
        run.resampled_writing_result_set, timingConfig);
    [~, selectedInputIndex] = max(arrayfun( ...
        @(segment) numel(segment.waypoints), timed.segments));
    selectedTimed = timed;
    selectedTimed.segments = timed.segments(selectedInputIndex);
    continuous = generate_quintic_continuous_joint_trajectory( ...
        selectedTimed, timingConfig);
    posture = default_writing_posture_config();
    validation = validate_continuous_writing_task_geometry(robot, continuous, ...
        run.resampled_writing_result_set, ...
        run.raw_frame_driven_baseline.candidate_task_plane_config, ...
        run.raw_frame_driven_baseline.candidate_config, posture);
    segment = continuous.segments(1);
    geometry = validation.segments(1);

    fprintf(['Quintic segment %d: %d waypoints, %d samples, initial/final ' ...
        'duration %.9g / %.9g s, stretch %.9g (%d iteration(s))\n'], ...
        segment.segment_index, size(segment.waypoint_q_rad, 1), ...
        numel(segment.t_s), segment.initial_duration_s, segment.duration_s, ...
        segment.time_stretch_factor, segment.time_stretch_iterations);
    fprintf('Peak velocity [rad/s]: %s\n', ...
        mat2str(segment.max_observed_abs_velocity_rad_s, 8));
    fprintf('Peak acceleration [rad/s^2]: %s\n', ...
        mat2str(segment.max_observed_abs_acceleration_rad_s2, 8));
    fprintf('Initial peak velocity [rad/s]: %s\n', ...
        mat2str(segment.initial_peak_velocity_rad_s, 8));
    fprintf('Initial peak acceleration [rad/s^2]: %s\n', ...
        mat2str(segment.initial_peak_acceleration_rad_s2, 8));
    fprintf('Max joint overshoot: %.9g rad; all safety checks=%d\n', ...
        segment.overshoot_evidence.max_overshoot_magnitude_rad, ...
        segment.all_safety_checks_satisfied);
    fprintf(['FK mean/max deviation %.9g / %.9g m; max tool-Z %.6f deg; ' ...
        'min joint margin %.9g rad; joint-limit violation=%d\n'], ...
        geometry.mean_position_deviation_m, geometry.max_position_deviation_m, ...
        geometry.max_tool_direction_error_deg, geometry.minimum_joint_limit_margin, ...
        geometry.has_joint_limit_violation);

    figure('Name', 'Quintic V1 task-space reference versus FK');
    plot3(geometry.reference_xyz_m(:,1), geometry.reference_xyz_m(:,2), ...
        geometry.reference_xyz_m(:,3), 'k--', 'LineWidth', 1.5); hold on;
    plot3(geometry.fk_xyz_m(:,1), geometry.fk_xyz_m(:,2), ...
        geometry.fk_xyz_m(:,3), 'g-', 'LineWidth', 1.2);
    grid on; axis equal;
    xlabel('Base X [m]'); ylabel('Base Y [m]'); zlabel('Base Z [m]');
    legend({'Linear Writing reference', 'Quintic V1 FK body5'}, ...
        'Location', 'best');
    title(sprintf('IK-success segment %d', segment.segment_index));

    demo = struct('source_run', run, 'timed_trajectory', timed, ...
        'selected_input_segment_index', selectedInputIndex, ...
        'continuous_trajectory', continuous, 'validation', validation, ...
        'selected_segment', segment, 'selected_geometry', geometry);
end
