function demo_preik_segments(jsonPath)
%DEMO_PREIK_SEGMENTS Visualize pre-IK candidate segments without solving IK.
%
% Input:
%   jsonPath - Stage 2.3 WorkspaceTrajectory JSON path
%
% The demo reads, retargets, and displays existing data only. It does not
% interpolate gaps, plan velocity, move the robot, or produce IK solutions.

    if nargin ~= 1
        error( ...
            'MonoTeach:InvalidArgumentCount', ...
            'demo_preik_segments requires exactly one JSON path.');
    end

    stage3Dir = fileparts(fileparts(mfilename('fullpath')));
    repoRoot = fileparts(stage3Dir);
    stage1Dir = fullfile(repoRoot, 'stage1');

    addpath(genpath(stage3Dir));
    addpath(stage1Dir);

    % Preserve the data-flow order used by the future IK stage.
    workspaceTrajectory = load_workspace_trajectory(jsonPath);
    config = default_task_plane_config();
    taskTrajectory = workspace_to_task_trajectory( ...
        workspaceTrajectory, ...
        config);
    segmentSet = build_preik_segments(taskTrajectory);

    print_segment_summary(segmentSet);
    draw_workspace_segments(workspaceTrajectory, segmentSet);
    draw_robot_base_segments(taskTrajectory, segmentSet, config);
end


function print_segment_summary(segmentSet)

    summary = segmentSet.summary;

    fprintf('============================================\n');
    fprintf('MonoTeach Stage 3.1B Pre-IK Segment Summary\n');
    fprintf('============================================\n');
    fprintf('Total samples   : %d\n', summary.total_sample_count);
    fprintf('Eligible samples: %d\n', summary.eligible_sample_count);
    fprintf('Segments        : %d\n', summary.segment_count);

    for i = 1:numel(segmentSet.segments)
        segment = segmentSet.segments(i);

        fprintf( ...
            'Segment %d: source_indices=%s, points=%d, t_ms=%.3f -> %.3f\n', ...
            i, ...
            mat2str(segment.source_indices), ...
            numel(segment.samples), ...
            segment.start_t_ms, ...
            segment.end_t_ms);
    end
end


function draw_workspace_segments(workspaceTrajectory, segmentSet)

    metadata = workspaceTrajectory.metadata;
    sourceSamples = workspaceTrajectory.samples;
    colors = lines(max(numel(segmentSet.segments), 1));

    figure('Name', 'MonoTeach Pre-IK Segments in Workspace');
    ax = axes;
    hold(ax, 'on');

    % This view stays in the original Stage 2.3 workspace coordinate frame [mm].
    hBoundary = plot( ...
        ax, ...
        [0, metadata.width_mm, metadata.width_mm, 0, 0], ...
        [0, 0, metadata.height_mm, metadata.height_mm, 0], ...
        'k-', ...
        'LineWidth', 1.5, ...
        'DisplayName', 'Workspace boundary');

    segmentHandles = gobjects(1, numel(segmentSet.segments));

    for i = 1:numel(segmentSet.segments)
        segment = segmentSet.segments(i);
        sourceIndices = segment.source_indices;
        xMm = [sourceSamples(sourceIndices).x_mm];
        yMm = [sourceSamples(sourceIndices).y_mm];

        % Each contiguous candidate is plotted independently. There is no line
        % from this segment to the next because a barrier lies between them.
        segmentHandles(i) = plot( ...
            ax, ...
            xMm, ...
            yMm, ...
            'o-', ...
            'Color', colors(i, :), ...
            'MarkerFaceColor', colors(i, :), ...
            'LineWidth', 1.8, ...
            'DisplayName', sprintf( ...
                'Segment %d, source %s', ...
                i, ...
                mat2str(sourceIndices)));
    end

    outsideMask = [sourceSamples.valid] & ...
        ~[sourceSamples.inside_workspace];
    outsideSamples = sourceSamples(outsideMask);

    hOutside = plot( ...
        ax, ...
        [outsideSamples.x_mm], ...
        [outsideSamples.y_mm], ...
        'rd', ...
        'MarkerFaceColor', 'r', ...
        'MarkerSize', 7, ...
        'DisplayName', 'Valid but outside (barrier)');

    invalidIndices = find(~[sourceSamples.valid]);

    if ~isempty(invalidIndices)
        % Invalid samples have no position, so a label is more honest than
        % inventing a marker position in the workspace.
        text( ...
            ax, ...
            5, ...
            metadata.height_mm - 5, ...
            sprintf('Invalid barrier source indices: %s', mat2str(invalidIndices)), ...
            'Color', [0.70, 0.00, 0.00], ...
            'FontWeight', 'bold');
    end

    axis(ax, 'equal');
    xlim(ax, [0, metadata.width_mm]);
    ylim(ax, [0, metadata.height_mm]);
    set(ax, 'YDir', 'reverse');
    grid(ax, 'on');
    xlabel(ax, 'Workspace X (mm)');
    ylabel(ax, 'Workspace Y (mm)');
    title(ax, 'Stage 3.1B Pre-IK Eligibility in Workspace');
    legend( ...
        ax, ...
        [hBoundary, segmentHandles, hOutside], ...
        'Location', 'best');
end


function draw_robot_base_segments(taskTrajectory, segmentSet, config)

    robot = build_legacy_robot();
    qHome = homeConfiguration(robot);
    colors = lines(max(numel(segmentSet.segments), 1));

    figure('Name', 'MonoTeach Pre-IK Segments in Robot Base');
    ax = axes;
    plot_legacy_robot(robot, qHome, ax);
    hold(ax, 'on');

    % Robot, plane, anchor, and segment XYZ are all in robot base frame [m].
    taskPlaneCornersM = task_plane_corners_base_m(config);
    hPlane = plot3( ...
        ax, ...
        taskPlaneCornersM(:, 1), ...
        taskPlaneCornersM(:, 2), ...
        taskPlaneCornersM(:, 3), ...
        'm-', ...
        'LineWidth', 2, ...
        'DisplayName', 'Scaled task plane');

    hAnchor = plot3( ...
        ax, ...
        config.robot_anchor_m(1), ...
        config.robot_anchor_m(2), ...
        config.robot_anchor_m(3), ...
        'kp', ...
        'MarkerSize', 12, ...
        'LineWidth', 2, ...
        'DisplayName', 'Task-plane anchor');

    segmentHandles = gobjects(1, numel(segmentSet.segments));

    for i = 1:numel(segmentSet.segments)
        segment = segmentSet.segments(i);
        segmentSamples = segment.samples;
        xM = [segmentSamples.x_m];
        yM = [segmentSamples.y_m];
        zM = [segmentSamples.z_m];

        % source_indices identify these points in the unmodified TaskTrajectory.
        % A separate plot call per segment forbids cross-barrier connections.
        segmentHandles(i) = plot3( ...
            ax, ...
            xM, ...
            yM, ...
            zM, ...
            'o-', ...
            'Color', colors(i, :), ...
            'MarkerFaceColor', colors(i, :), ...
            'LineWidth', 1.8, ...
            'DisplayName', sprintf( ...
                'Segment %d, source %s', ...
                i, ...
                mat2str(segment.source_indices)));
    end

    sourceSamples = taskTrajectory.samples;
    outsideMask = [sourceSamples.valid] & ...
        ~[sourceSamples.inside_workspace];
    outsideSamples = sourceSamples(outsideMask);

    hOutside = plot3( ...
        ax, ...
        [outsideSamples.x_m], ...
        [outsideSamples.y_m], ...
        [outsideSamples.z_m], ...
        'rd', ...
        'MarkerFaceColor', 'r', ...
        'MarkerSize', 7, ...
        'DisplayName', 'Valid but outside (not segmented)');

    invalidIndices = find(~[sourceSamples.valid]);

    if ~isempty(invalidIndices)
        % Invalid source samples intentionally have empty XYZ, so no base-frame
        % point is fabricated. The text records their barrier identity instead.
        text( ...
            ax, ...
            config.robot_anchor_m(1), ...
            config.robot_anchor_m(2), ...
            config.robot_anchor_m(3) + 0.025, ...
            sprintf('Invalid barriers: source %s', mat2str(invalidIndices)), ...
            'Color', [0.70, 0.00, 0.00], ...
            'FontWeight', 'bold');
    end

    axis(ax, 'equal');
    grid(ax, 'on');
    xlabel(ax, 'Base X (m)');
    ylabel(ax, 'Base Y (m)');
    zlabel(ax, 'Base Z (m)');
    title(ax, 'Stage 3.1B Pre-IK Segments in Legacy Robot Base Frame');
    view(ax, 3);
    legend( ...
        ax, ...
        [hPlane, hAnchor, segmentHandles, hOutside], ...
        'Location', 'best');
end


function cornersBaseM = task_plane_corners_base_m(config)

    halfWidthM = config.workspace_width_mm * config.scale / 2;
    halfHeightM = config.workspace_height_mm * config.scale / 2;

    cornersTaskPlaneM = [ ...
        -halfWidthM, -halfHeightM, 0; ...
         halfWidthM, -halfHeightM, 0; ...
         halfWidthM,  halfHeightM, 0; ...
        -halfWidthM,  halfHeightM, 0; ...
        -halfWidthM, -halfHeightM, 0];

    RBaseTaskplane = config.T_base_taskplane(1:3, 1:3);
    anchorBaseM = config.T_base_taskplane(1:3, 4)';

    cornersBaseM = ...
        (RBaseTaskplane * cornersTaskPlaneM' + anchorBaseM')';
end
