function demo = demo_validate_minimum_jerk_writing_geometry(jsonPath, timingConfig)
%DEMO_VALIDATE_MINIMUM_JERK_WRITING_GEOMETRY FK-validate longest real segment.

    if nargin < 2 || isempty(timingConfig)
        timingConfig = default_timed_joint_trajectory_config();
    end
    if nargin < 1, jsonPath = []; end
    if isempty(jsonPath)
        run = run_real_resampled_task_path_ik_ab();
    else
        run = run_real_resampled_task_path_ik_ab(jsonPath);
    end
    robot = build_legacy_robot();
    timed = time_parameterize_ik_success_segments( ...
        run.resampled_writing_result_set, timingConfig);
    [~, selectedInputIndex] = max(arrayfun( ...
        @(segment) numel(segment.waypoints), timed.segments));
    selectedTimed = timed;
    selectedTimed.segments = timed.segments(selectedInputIndex);
    continuous = generate_minimum_jerk_continuous_joint_trajectory( ...
        selectedTimed, timingConfig);
    posture = default_writing_posture_config();
    validation = validate_continuous_writing_task_geometry(robot, continuous, ...
        run.resampled_writing_result_set, ...
        run.raw_frame_driven_baseline.candidate_task_plane_config, ...
        run.raw_frame_driven_baseline.candidate_config, posture);
    segment = validation.segments(1);

    fprintf(['Geometry validation segment %d: mean/max path deviation ' ...
        '%.9g / %.9g m, max tool-Z error %.6f deg, min joint margin ' ...
        '%.9g rad, limit violation=%d, worst path sample=%d at %.6f s, ' ...
        'worst tool sample=%d at %.6f s\n'], ...
        segment.segment_index, segment.mean_position_deviation_m, ...
        segment.max_position_deviation_m, segment.max_tool_direction_error_deg, ...
        segment.minimum_joint_limit_margin, segment.has_joint_limit_violation, ...
        segment.worst_position_sample_index, segment.worst_position_time_s, ...
        segment.worst_tool_direction_sample_index, ...
        segment.worst_tool_direction_time_s);

    figure('Name', 'Minimum-jerk task-space reference versus FK');
    plot3(segment.reference_xyz_m(:,1), segment.reference_xyz_m(:,2), ...
        segment.reference_xyz_m(:,3), 'k--', 'LineWidth', 1.5); hold on;
    plot3(segment.fk_xyz_m(:,1), segment.fk_xyz_m(:,2), ...
        segment.fk_xyz_m(:,3), 'b-', 'LineWidth', 1.2);
    grid on; axis equal;
    xlabel('Base X [m]'); ylabel('Base Y [m]'); zlabel('Base Z [m]');
    legend({'Linear Writing reference', 'Continuous FK body5'}, 'Location', 'best');
    title(sprintf('IK-success segment %d', segment.segment_index));

    demo = struct('source_run', run, 'timed_trajectory', timed, ...
        'selected_input_segment_index', selectedInputIndex, ...
        'continuous_trajectory', continuous, 'validation', validation, ...
        'selected_segment', segment);
end
