function demo = demo_quintic_all_writing_segments(jsonPath, timingConfig)
%DEMO_QUINTIC_ALL_WRITING_SEGMENTS Full pre-transition Quintic V1 review.
%
% Runs every current Writing IK-success segment independently.  The figure
% intentionally issues one plot call per segment, so it never draws a line
% through an IK failure gap or invents a global execution timeline.

    if nargin < 2 || isempty(timingConfig)
        timingConfig = default_timed_joint_trajectory_config();
    end
    if nargin < 1, jsonPath = []; end
    if isempty(jsonPath)
        run = run_real_resampled_task_path_ik_ab();
    else
        run = run_real_resampled_task_path_ik_ab(jsonPath);
    end
    robot = build_legacy_robot();
    timed = time_parameterize_ik_success_segments( ...
        run.resampled_writing_result_set, timingConfig);
    continuous = generate_quintic_continuous_joint_trajectory(timed, timingConfig);
    posture = default_writing_posture_config();
    validation = validate_continuous_writing_task_geometry(robot, continuous, ...
        run.resampled_writing_result_set, ...
        run.raw_frame_driven_baseline.candidate_task_plane_config, ...
        run.raw_frame_driven_baseline.candidate_config, posture);
    summary = summarize_quintic_continuous_trajectory(continuous, validation);
    print_summary(summary);
    plot_all_segments(validation);

    demo = struct('source_run', run, 'timed_trajectory', timed, ...
        'continuous_trajectory', continuous, 'validation', validation, ...
        'pre_transition_summary', summary);
end


function print_summary(summary)

    fprintf(['Quintic V1 pre-transition: %d independent IK-success segments, ' ...
        '%d accepted waypoints, %.9g s summed local duration; global timeline=%d\n'], ...
        summary.ik_success_segment_count, summary.total_accepted_waypoint_count, ...
        summary.total_independent_quintic_duration_s, summary.execution_timeline_exists);
    fprintf(['All limits [velocity acceleration joint]=[%d %d %d]; worst Cartesian ' ...
        'segment=%d (%.9g m), worst tool-Z segment=%d (%.6f deg), smallest ' ...
        'margin segment=%d (%.9g rad)\n'], ...
        summary.all_velocity_limits_satisfied, ...
        summary.all_acceleration_limits_satisfied, summary.all_joint_limits_satisfied, ...
        summary.worst_cartesian.segment_index, summary.worst_cartesian.value, ...
        summary.worst_tool_direction.segment_index, ...
        summary.worst_tool_direction.value, ...
        summary.smallest_joint_limit_margin.segment_index, ...
        summary.smallest_joint_limit_margin.value);
    fprintf([' seg  wp  samples  initial_s   final_s  stretch  overshoot_rad  ' ...
        'cart_mean_m  cart_max_m  tool_deg  margin_rad  limits[V A J]\n']);
    for index = 1:numel(summary.segment_records)
        record = summary.segment_records(index);
        fprintf(['%4d %3d %8d %10.6f %9.6f %8.4f %14.6g %12.6g %11.6g ' ...
            '%9.4f %11.6f [%d %d %d]\n'], ...
            record.segment_index, record.waypoint_count, ...
            record.continuous_sample_count, record.initial_duration_s, ...
            record.final_duration_s, record.time_stretch_factor, ...
            record.max_joint_overshoot_rad, record.cartesian_mean_deviation_m, ...
            record.cartesian_max_deviation_m, record.max_tool_direction_error_deg, ...
            record.minimum_joint_limit_margin_rad, ...
            record.velocity_limits_satisfied, record.acceleration_limits_satisfied, ...
            record.joint_limits_satisfied);
    end
end


function plot_all_segments(validation)

    figure('Name', 'Quintic V1 all Writing IK-success segments');
    hold on;
    for index = 1:numel(validation.segments)
        segment = validation.segments(index);
        if index == 1
            plot3(segment.reference_xyz_m(:,1), segment.reference_xyz_m(:,2), ...
                segment.reference_xyz_m(:,3), 'k--', 'LineWidth', 1.3, ...
                'DisplayName', 'Writing reference segments');
            plot3(segment.fk_xyz_m(:,1), segment.fk_xyz_m(:,2), ...
                segment.fk_xyz_m(:,3), 'g-', 'LineWidth', 1.1, ...
                'DisplayName', 'Quintic V1 FK segments');
        else
            plot3(segment.reference_xyz_m(:,1), segment.reference_xyz_m(:,2), ...
                segment.reference_xyz_m(:,3), 'k--', 'LineWidth', 1.3, ...
                'HandleVisibility', 'off');
            plot3(segment.fk_xyz_m(:,1), segment.fk_xyz_m(:,2), ...
                segment.fk_xyz_m(:,3), 'g-', 'LineWidth', 1.1, ...
                'HandleVisibility', 'off');
        end
    end
    grid on; axis equal;
    xlabel('Base X [m]'); ylabel('Base Y [m]'); zlabel('Base Z [m]');
    legend('Location', 'best');
    title('All independent Quintic V1 Writing IK-success segments');
end
